new Text: ElektronikTD[36];

CreateElektronik()
{
    ElektronikTD[0] = TextDrawCreate(176.000, 167.000, "LD_SPAC:white");
    TextDrawTextSize(ElektronikTD[0], 75.000, 55.000);
    TextDrawAlignment(ElektronikTD[0], 1);
    TextDrawColor(ElektronikTD[0], -121583496);
    TextDrawSetShadow(ElektronikTD[0], 0);
    TextDrawSetOutline(ElektronikTD[0], 0);
    TextDrawBackgroundColor(ElektronikTD[0], 255);
    TextDrawFont(ElektronikTD[0], 4);
    TextDrawSetProportional(ElektronikTD[0], 1);

    ElektronikTD[1] = TextDrawCreate(178.000, 169.000, "LD_SPAC:white");
    TextDrawTextSize(ElektronikTD[1], 71.000, 51.000);
    TextDrawAlignment(ElektronikTD[1], 1);
    TextDrawColor(ElektronikTD[1], -121583361);
    TextDrawSetShadow(ElektronikTD[1], 0);
    TextDrawSetOutline(ElektronikTD[1], 0);
    TextDrawBackgroundColor(ElektronikTD[1], 255);
    TextDrawFont(ElektronikTD[1], 4);
    TextDrawSetProportional(ElektronikTD[1], 1);

    ElektronikTD[2] = TextDrawCreate(279.000, 167.000, "LD_SPAC:white");
    TextDrawTextSize(ElektronikTD[2], 54.000, 75.000);
    TextDrawAlignment(ElektronikTD[2], 1);
    TextDrawColor(ElektronikTD[2], 100);
    TextDrawSetShadow(ElektronikTD[2], 0);
    TextDrawSetOutline(ElektronikTD[2], 0);
    TextDrawBackgroundColor(ElektronikTD[2], 255);
    TextDrawFont(ElektronikTD[2], 4);
    TextDrawSetProportional(ElektronikTD[2], 1);
    TextDrawSetSelectable(ElektronikTD[2], 1);

    ElektronikTD[3] = TextDrawCreate(340.000, 167.000, "LD_SPAC:white");
    TextDrawTextSize(ElektronikTD[3], 54.000, 75.000);
    TextDrawAlignment(ElektronikTD[3], 1);
    TextDrawColor(ElektronikTD[3], 100);
    TextDrawSetShadow(ElektronikTD[3], 0);
    TextDrawSetOutline(ElektronikTD[3], 0);
    TextDrawBackgroundColor(ElektronikTD[3], 255);
    TextDrawFont(ElektronikTD[3], 4);
    TextDrawSetProportional(ElektronikTD[3], 1);
    TextDrawSetSelectable(ElektronikTD[3], 1);

    ElektronikTD[4] = TextDrawCreate(402.000, 167.000, "LD_SPAC:white");
    TextDrawTextSize(ElektronikTD[4], 54.000, 75.000);
    TextDrawAlignment(ElektronikTD[4], 1);
    TextDrawColor(ElektronikTD[4], 100);
    TextDrawSetShadow(ElektronikTD[4], 0);
    TextDrawSetOutline(ElektronikTD[4], 0);
    TextDrawBackgroundColor(ElektronikTD[4], 255);
    TextDrawFont(ElektronikTD[4], 4);
    TextDrawSetProportional(ElektronikTD[4], 1);
    TextDrawSetSelectable(ElektronikTD[4], 1);

    ElektronikTD[5] = TextDrawCreate(279.000, 254.000, "LD_SPAC:white");
    TextDrawTextSize(ElektronikTD[5], 54.000, 75.000);
    TextDrawAlignment(ElektronikTD[5], 1);
    TextDrawColor(ElektronikTD[5], 100);
    TextDrawSetShadow(ElektronikTD[5], 0);
    TextDrawSetOutline(ElektronikTD[5], 0);
    TextDrawBackgroundColor(ElektronikTD[5], 255);
    TextDrawFont(ElektronikTD[5], 4);
    TextDrawSetProportional(ElektronikTD[5], 1);
    TextDrawSetSelectable(ElektronikTD[5], 1);

    ElektronikTD[6] = TextDrawCreate(340.000, 254.000, "LD_SPAC:white");
    TextDrawTextSize(ElektronikTD[6], 54.000, 75.000);
    TextDrawAlignment(ElektronikTD[6], 1);
    TextDrawColor(ElektronikTD[6], 100);
    TextDrawSetShadow(ElektronikTD[6], 0);
    TextDrawSetOutline(ElektronikTD[6], 0);
    TextDrawBackgroundColor(ElektronikTD[6], 255);
    TextDrawFont(ElektronikTD[6], 4);
    TextDrawSetProportional(ElektronikTD[6], 1);
    TextDrawSetSelectable(ElektronikTD[6], 1);

    ElektronikTD[7] = TextDrawCreate(179.000, 135.000, "LD_BEAT:chit");
    TextDrawTextSize(ElektronikTD[7], 11.000, 17.000);
    TextDrawAlignment(ElektronikTD[7], 1);
    TextDrawColor(ElektronikTD[7], -121583361);
    TextDrawSetShadow(ElektronikTD[7], 0);
    TextDrawSetOutline(ElektronikTD[7], 0);
    TextDrawBackgroundColor(ElektronikTD[7], 255);
    TextDrawFont(ElektronikTD[7], 4);
    TextDrawSetProportional(ElektronikTD[7], 1);

    ElektronikTD[8] = TextDrawCreate(279.000, 240.000, "LD_SPAC:white");
    TextDrawTextSize(ElektronikTD[8], 54.000, 2.000);
    TextDrawAlignment(ElektronikTD[8], 1);
    TextDrawColor(ElektronikTD[8], -121583361);
    TextDrawSetShadow(ElektronikTD[8], 0);
    TextDrawSetOutline(ElektronikTD[8], 0);
    TextDrawBackgroundColor(ElektronikTD[8], 255);
    TextDrawFont(ElektronikTD[8], 4);
    TextDrawSetProportional(ElektronikTD[8], 1);

    ElektronikTD[9] = TextDrawCreate(340.000, 240.000, "LD_SPAC:white");
    TextDrawTextSize(ElektronikTD[9], 54.000, 2.000);
    TextDrawAlignment(ElektronikTD[9], 1);
    TextDrawColor(ElektronikTD[9], -121583361);
    TextDrawSetShadow(ElektronikTD[9], 0);
    TextDrawSetOutline(ElektronikTD[9], 0);
    TextDrawBackgroundColor(ElektronikTD[9], 255);
    TextDrawFont(ElektronikTD[9], 4);
    TextDrawSetProportional(ElektronikTD[9], 1);

    ElektronikTD[10] = TextDrawCreate(402.000, 240.000, "LD_SPAC:white");
    TextDrawTextSize(ElektronikTD[10], 54.000, 2.000);
    TextDrawAlignment(ElektronikTD[10], 1);
    TextDrawColor(ElektronikTD[10], -121583361);
    TextDrawSetShadow(ElektronikTD[10], 0);
    TextDrawSetOutline(ElektronikTD[10], 0);
    TextDrawBackgroundColor(ElektronikTD[10], 255);
    TextDrawFont(ElektronikTD[10], 4);
    TextDrawSetProportional(ElektronikTD[10], 1);

    ElektronikTD[11] = TextDrawCreate(279.000, 327.000, "LD_SPAC:white");
    TextDrawTextSize(ElektronikTD[11], 54.000, 2.000);
    TextDrawAlignment(ElektronikTD[11], 1);
    TextDrawColor(ElektronikTD[11], -121583361);
    TextDrawSetShadow(ElektronikTD[11], 0);
    TextDrawSetOutline(ElektronikTD[11], 0);
    TextDrawBackgroundColor(ElektronikTD[11], 255);
    TextDrawFont(ElektronikTD[11], 4);
    TextDrawSetProportional(ElektronikTD[11], 1);

    ElektronikTD[12] = TextDrawCreate(340.000, 327.000, "LD_SPAC:white");
    TextDrawTextSize(ElektronikTD[12], 54.000, 2.000);
    TextDrawAlignment(ElektronikTD[12], 1);
    TextDrawColor(ElektronikTD[12], -121583361);
    TextDrawSetShadow(ElektronikTD[12], 0);
    TextDrawSetOutline(ElektronikTD[12], 0);
    TextDrawBackgroundColor(ElektronikTD[12], 255);
    TextDrawFont(ElektronikTD[12], 4);
    TextDrawSetProportional(ElektronikTD[12], 1);

    ElektronikTD[13] = TextDrawCreate(177.000, 148.000, "LD_BEAT:chit");
    TextDrawTextSize(ElektronikTD[13], 16.000, 16.000);
    TextDrawAlignment(ElektronikTD[13], 1);
    TextDrawColor(ElektronikTD[13], -121583361);
    TextDrawSetShadow(ElektronikTD[13], 0);
    TextDrawSetOutline(ElektronikTD[13], 0);
    TextDrawBackgroundColor(ElektronikTD[13], 255);
    TextDrawFont(ElektronikTD[13], 4);
    TextDrawSetProportional(ElektronikTD[13], 1);

    ElektronikTD[14] = TextDrawCreate(196.000, 146.000, "Hallo - Welcome");
    TextDrawLetterSize(ElektronikTD[14], 0.210, 1.199);
    TextDrawAlignment(ElektronikTD[14], 1);
    TextDrawColor(ElektronikTD[14], -1);
    TextDrawSetShadow(ElektronikTD[14], 0);
    TextDrawSetOutline(ElektronikTD[14], 0);
    TextDrawBackgroundColor(ElektronikTD[14], 150);
    TextDrawFont(ElektronikTD[14], 1);
    TextDrawSetProportional(ElektronikTD[14], 1);

    ElektronikTD[15] = TextDrawCreate(188.000, 172.000, "Elektronik Market");
    TextDrawLetterSize(ElektronikTD[15], 0.210, 1.199);
    TextDrawAlignment(ElektronikTD[15], 1);
    TextDrawColor(ElektronikTD[15], 1768516095);
    TextDrawSetShadow(ElektronikTD[15], 0);
    TextDrawSetOutline(ElektronikTD[15], 0);
    TextDrawBackgroundColor(ElektronikTD[15], 150);
    TextDrawFont(ElektronikTD[15], 1);
    TextDrawSetProportional(ElektronikTD[15], 1);

    ElektronikTD[16] = TextDrawCreate(183.000, 187.000, "Silahkan pilih Sesuai");
    TextDrawLetterSize(ElektronikTD[16], 0.160, 0.799);
    TextDrawAlignment(ElektronikTD[16], 1);
    TextDrawColor(ElektronikTD[16], 1768516095);
    TextDrawSetShadow(ElektronikTD[16], 0);
    TextDrawSetOutline(ElektronikTD[16], 0);
    TextDrawBackgroundColor(ElektronikTD[16], 150);
    TextDrawFont(ElektronikTD[16], 1);
    TextDrawSetProportional(ElektronikTD[16], 1);

    ElektronikTD[17] = TextDrawCreate(196.000, 195.000, "Keperluan");
    TextDrawLetterSize(ElektronikTD[17], 0.160, 0.799);
    TextDrawAlignment(ElektronikTD[17], 1);
    TextDrawColor(ElektronikTD[17], 1768516095);
    TextDrawSetShadow(ElektronikTD[17], 0);
    TextDrawSetOutline(ElektronikTD[17], 0);
    TextDrawBackgroundColor(ElektronikTD[17], 150);
    TextDrawFont(ElektronikTD[17], 1);
    TextDrawSetProportional(ElektronikTD[17], 1);

    ElektronikTD[18] = TextDrawCreate(187.000, 204.000, "Anda");
    TextDrawLetterSize(ElektronikTD[18], 0.160, 0.799);
    TextDrawAlignment(ElektronikTD[18], 1);
    TextDrawColor(ElektronikTD[18], 1768516095);
    TextDrawSetShadow(ElektronikTD[18], 0);
    TextDrawSetOutline(ElektronikTD[18], 0);
    TextDrawBackgroundColor(ElektronikTD[18], 150);
    TextDrawFont(ElektronikTD[18], 1);
    TextDrawSetProportional(ElektronikTD[18], 1);

    ElektronikTD[19] = TextDrawCreate(193.000, 248.000, "LD_SPAC:white");
    TextDrawTextSize(ElektronikTD[19], 42.000, 22.000);
    TextDrawAlignment(ElektronikTD[19], 1);
    TextDrawColor(ElektronikTD[19], -16776534);
    TextDrawSetShadow(ElektronikTD[19], 0);
    TextDrawSetOutline(ElektronikTD[19], 0);
    TextDrawBackgroundColor(ElektronikTD[19], 255);
    TextDrawFont(ElektronikTD[19], 4);
    TextDrawSetProportional(ElektronikTD[19], 1);
    TextDrawSetSelectable(ElektronikTD[19], 1);

    ElektronikTD[20] = TextDrawCreate(209.000, 252.000, "Exit");
    TextDrawLetterSize(ElektronikTD[20], 0.210, 1.199);
    TextDrawAlignment(ElektronikTD[20], 1);
    TextDrawColor(ElektronikTD[20], -1);
    TextDrawSetShadow(ElektronikTD[20], 0);
    TextDrawSetOutline(ElektronikTD[20], 0);
    TextDrawBackgroundColor(ElektronikTD[20], 150);
    TextDrawFont(ElektronikTD[20], 1);
    TextDrawSetProportional(ElektronikTD[20], 1);

    ElektronikTD[21] = TextDrawCreate(290.000, 227.000, "Smartphone");
    TextDrawLetterSize(ElektronikTD[21], 0.210, 1.199);
    TextDrawAlignment(ElektronikTD[21], 1);
    TextDrawColor(ElektronikTD[21], -121583361);
    TextDrawSetShadow(ElektronikTD[21], 0);
    TextDrawSetOutline(ElektronikTD[21], 0);
    TextDrawBackgroundColor(ElektronikTD[21], 150);
    TextDrawFont(ElektronikTD[21], 1);
    TextDrawSetProportional(ElektronikTD[21], 1);

    ElektronikTD[22] = TextDrawCreate(359.000, 227.000, "Radio");
    TextDrawLetterSize(ElektronikTD[22], 0.210, 1.199);
    TextDrawAlignment(ElektronikTD[22], 1);
    TextDrawColor(ElektronikTD[22], -121583361);
    TextDrawSetShadow(ElektronikTD[22], 0);
    TextDrawSetOutline(ElektronikTD[22], 0);
    TextDrawBackgroundColor(ElektronikTD[22], 150);
    TextDrawFont(ElektronikTD[22], 1);
    TextDrawSetProportional(ElektronikTD[22], 1);

    ElektronikTD[23] = TextDrawCreate(417.000, 226.000, "Earphone");
    TextDrawLetterSize(ElektronikTD[23], 0.210, 1.199);
    TextDrawAlignment(ElektronikTD[23], 1);
    TextDrawColor(ElektronikTD[23], -121583361);
    TextDrawSetShadow(ElektronikTD[23], 0);
    TextDrawSetOutline(ElektronikTD[23], 0);
    TextDrawBackgroundColor(ElektronikTD[23], 150);
    TextDrawFont(ElektronikTD[23], 1);
    TextDrawSetProportional(ElektronikTD[23], 1);

    ElektronikTD[24] = TextDrawCreate(293.000, 314.000, "Boombox");
    TextDrawLetterSize(ElektronikTD[24], 0.210, 1.199);
    TextDrawAlignment(ElektronikTD[24], 1);
    TextDrawColor(ElektronikTD[24], -121583361);
    TextDrawSetShadow(ElektronikTD[24], 0);
    TextDrawSetOutline(ElektronikTD[24], 0);
    TextDrawBackgroundColor(ElektronikTD[24], 150);
    TextDrawFont(ElektronikTD[24], 1);
    TextDrawSetProportional(ElektronikTD[24], 1);

    ElektronikTD[25] = TextDrawCreate(359.000, 314.000, "Vape");
    TextDrawLetterSize(ElektronikTD[25], 0.210, 1.199);
    TextDrawAlignment(ElektronikTD[25], 1);
    TextDrawColor(ElektronikTD[25], -121583361);
    TextDrawSetShadow(ElektronikTD[25], 0);
    TextDrawSetOutline(ElektronikTD[25], 0);
    TextDrawBackgroundColor(ElektronikTD[25], 150);
    TextDrawFont(ElektronikTD[25], 1);
    TextDrawSetProportional(ElektronikTD[25], 1);

    ElektronikTD[26] = TextDrawCreate(280.000, 168.000, "$1,500");
    TextDrawLetterSize(ElektronikTD[26], 0.160, 1.099);
    TextDrawAlignment(ElektronikTD[26], 1);
    TextDrawColor(ElektronikTD[26], -121583361);
    TextDrawSetShadow(ElektronikTD[26], 0);
    TextDrawSetOutline(ElektronikTD[26], 0);
    TextDrawBackgroundColor(ElektronikTD[26], 150);
    TextDrawFont(ElektronikTD[26], 1);
    TextDrawSetProportional(ElektronikTD[26], 1);

    ElektronikTD[27] = TextDrawCreate(341.000, 168.000, "$500");
    TextDrawLetterSize(ElektronikTD[27], 0.160, 1.099);
    TextDrawAlignment(ElektronikTD[27], 1);
    TextDrawColor(ElektronikTD[27], -121583361);
    TextDrawSetShadow(ElektronikTD[27], 0);
    TextDrawSetOutline(ElektronikTD[27], 0);
    TextDrawBackgroundColor(ElektronikTD[27], 150);
    TextDrawFont(ElektronikTD[27], 1);
    TextDrawSetProportional(ElektronikTD[27], 1);

    ElektronikTD[28] = TextDrawCreate(403.000, 168.000, "$500");
    TextDrawLetterSize(ElektronikTD[28], 0.160, 1.099);
    TextDrawAlignment(ElektronikTD[28], 1);
    TextDrawColor(ElektronikTD[28], -121583361);
    TextDrawSetShadow(ElektronikTD[28], 0);
    TextDrawSetOutline(ElektronikTD[28], 0);
    TextDrawBackgroundColor(ElektronikTD[28], 150);
    TextDrawFont(ElektronikTD[28], 1);
    TextDrawSetProportional(ElektronikTD[28], 1);

    ElektronikTD[29] = TextDrawCreate(280.000, 255.000, "$3,000");
    TextDrawLetterSize(ElektronikTD[29], 0.160, 1.099);
    TextDrawAlignment(ElektronikTD[29], 1);
    TextDrawColor(ElektronikTD[29], -121583361);
    TextDrawSetShadow(ElektronikTD[29], 0);
    TextDrawSetOutline(ElektronikTD[29], 0);
    TextDrawBackgroundColor(ElektronikTD[29], 150);
    TextDrawFont(ElektronikTD[29], 1);
    TextDrawSetProportional(ElektronikTD[29], 1);

    ElektronikTD[30] = TextDrawCreate(341.000, 255.000, "$1,500");
    TextDrawLetterSize(ElektronikTD[30], 0.160, 1.099);
    TextDrawAlignment(ElektronikTD[30], 1);
    TextDrawColor(ElektronikTD[30], -121583361);
    TextDrawSetShadow(ElektronikTD[30], 0);
    TextDrawSetOutline(ElektronikTD[30], 0);
    TextDrawBackgroundColor(ElektronikTD[30], 150);
    TextDrawFont(ElektronikTD[30], 1);
    TextDrawSetProportional(ElektronikTD[30], 1);

    ElektronikTD[31] = TextDrawCreate(251.000, 160.000, "_");
    TextDrawTextSize(ElektronikTD[31], 90.000, 90.000);
    TextDrawAlignment(ElektronikTD[31], 1);
    TextDrawColor(ElektronikTD[31], -1);
    TextDrawSetShadow(ElektronikTD[31], 0);
    TextDrawSetOutline(ElektronikTD[31], 0);
    TextDrawBackgroundColor(ElektronikTD[31], 512);
    TextDrawFont(ElektronikTD[31], 5);
    TextDrawSetProportional(ElektronikTD[31], 0);
    TextDrawSetPreviewModel(ElektronikTD[31], 18867);
    TextDrawSetPreviewRot(ElektronikTD[31], 88.000, 180.000, 0.000, 1.500);
    TextDrawSetPreviewVehCol(ElektronikTD[31], 0, 0);

    ElektronikTD[32] = TextDrawCreate(321.000, 152.000, "_");
    TextDrawTextSize(ElektronikTD[32], 90.000, 90.000);
    TextDrawAlignment(ElektronikTD[32], 1);
    TextDrawColor(ElektronikTD[32], -1);
    TextDrawSetShadow(ElektronikTD[32], 0);
    TextDrawSetOutline(ElektronikTD[32], 0);
    TextDrawBackgroundColor(ElektronikTD[32], 512);
    TextDrawFont(ElektronikTD[32], 5);
    TextDrawSetProportional(ElektronikTD[32], 0);
    TextDrawSetPreviewModel(ElektronikTD[32], 19942);
    TextDrawSetPreviewRot(ElektronikTD[32], 178.000, 180.000, 0.000, 1.399);
    TextDrawSetPreviewVehCol(ElektronikTD[32], 0, 0);

    ElektronikTD[33] = TextDrawCreate(364.000, 93.000, "_");
    TextDrawTextSize(ElektronikTD[33], 140.000, 139.000);
    TextDrawAlignment(ElektronikTD[33], 1);
    TextDrawColor(ElektronikTD[33], -1);
    TextDrawSetShadow(ElektronikTD[33], 0);
    TextDrawSetOutline(ElektronikTD[33], 0);
    TextDrawBackgroundColor(ElektronikTD[33], 0);
    TextDrawFont(ElektronikTD[33], 5);
    TextDrawSetProportional(ElektronikTD[33], 0);
    TextDrawSetPreviewModel(ElektronikTD[33], 19421);
    TextDrawSetPreviewRot(ElektronikTD[33], 102.000, 7.000, 0.000, 1.100);
    TextDrawSetPreviewVehCol(ElektronikTD[33], 0, 0);

    ElektronikTD[34] = TextDrawCreate(260.000, 244.000, "_");
    TextDrawTextSize(ElektronikTD[34], 90.000, 90.000);
    TextDrawAlignment(ElektronikTD[34], 1);
    TextDrawColor(ElektronikTD[34], -1);
    TextDrawSetShadow(ElektronikTD[34], 0);
    TextDrawSetOutline(ElektronikTD[34], 0);
    TextDrawBackgroundColor(ElektronikTD[34], 768);
    TextDrawFont(ElektronikTD[34], 5);
    TextDrawSetProportional(ElektronikTD[34], 0);
    TextDrawSetPreviewModel(ElektronikTD[34], 2103);
    TextDrawSetPreviewRot(ElektronikTD[34], 0.000, 0.000, 184.000, 1.800);
    TextDrawSetPreviewVehCol(ElektronikTD[34], 0, 0);

    ElektronikTD[35] = TextDrawCreate(320.000, 244.000, "_");
    TextDrawTextSize(ElektronikTD[35], 90.000, 90.000);
    TextDrawAlignment(ElektronikTD[35], 1);
    TextDrawColor(ElektronikTD[35], -1);
    TextDrawSetShadow(ElektronikTD[35], 0);
    TextDrawSetOutline(ElektronikTD[35], 0);
    TextDrawBackgroundColor(ElektronikTD[35], 0);
    TextDrawFont(ElektronikTD[35], 5);
    TextDrawSetProportional(ElektronikTD[35], 0);
    TextDrawSetPreviewModel(ElektronikTD[35], 19823);
    TextDrawSetPreviewRot(ElektronikTD[35], 0.000, 0.000, 0.000, 1.800);
    TextDrawSetPreviewVehCol(ElektronikTD[35], 0, 0);
}

ShowElektronik(playerid)
{
	HideServerNameTD(playerid);
	HideStatsTD(playerid);
	//HideSpeedoTD(playerid);
	HideHBETD(playerid);

    TextDrawShowForPlayer(playerid, ElektronikTD[0]);
    TextDrawShowForPlayer(playerid, ElektronikTD[1]);
    TextDrawShowForPlayer(playerid, ElektronikTD[2]);
    TextDrawShowForPlayer(playerid, ElektronikTD[3]);
    TextDrawShowForPlayer(playerid, ElektronikTD[4]);
    TextDrawShowForPlayer(playerid, ElektronikTD[5]);
    TextDrawShowForPlayer(playerid, ElektronikTD[6]);
    TextDrawShowForPlayer(playerid, ElektronikTD[7]);
    TextDrawShowForPlayer(playerid, ElektronikTD[8]);
    TextDrawShowForPlayer(playerid, ElektronikTD[9]);
    TextDrawShowForPlayer(playerid, ElektronikTD[10]);
    TextDrawShowForPlayer(playerid, ElektronikTD[11]);
    TextDrawShowForPlayer(playerid, ElektronikTD[12]);
    TextDrawShowForPlayer(playerid, ElektronikTD[13]);
    TextDrawShowForPlayer(playerid, ElektronikTD[14]);
    TextDrawShowForPlayer(playerid, ElektronikTD[15]);
    TextDrawShowForPlayer(playerid, ElektronikTD[16]);
    TextDrawShowForPlayer(playerid, ElektronikTD[17]);
    TextDrawShowForPlayer(playerid, ElektronikTD[18]);
    TextDrawShowForPlayer(playerid, ElektronikTD[19]);
    TextDrawShowForPlayer(playerid, ElektronikTD[20]);
    TextDrawShowForPlayer(playerid, ElektronikTD[21]);
    TextDrawShowForPlayer(playerid, ElektronikTD[22]);
    TextDrawShowForPlayer(playerid, ElektronikTD[23]);
    TextDrawShowForPlayer(playerid, ElektronikTD[24]);
    TextDrawShowForPlayer(playerid, ElektronikTD[25]);
    TextDrawShowForPlayer(playerid, ElektronikTD[26]);
    TextDrawShowForPlayer(playerid, ElektronikTD[27]);
    TextDrawShowForPlayer(playerid, ElektronikTD[28]);
    TextDrawShowForPlayer(playerid, ElektronikTD[29]);
    TextDrawShowForPlayer(playerid, ElektronikTD[30]);
    TextDrawShowForPlayer(playerid, ElektronikTD[31]);
    TextDrawShowForPlayer(playerid, ElektronikTD[32]);
    TextDrawShowForPlayer(playerid, ElektronikTD[33]);
    TextDrawShowForPlayer(playerid, ElektronikTD[34]);
    TextDrawShowForPlayer(playerid, ElektronikTD[35]);
	SelectTextDraw(playerid, 0xff91a4cc);
}

HideElektronik(playerid)
{
    TextDrawHideForPlayer(playerid, ElektronikTD[0]);
    TextDrawHideForPlayer(playerid, ElektronikTD[1]);
    TextDrawHideForPlayer(playerid, ElektronikTD[2]);
    TextDrawHideForPlayer(playerid, ElektronikTD[3]);
    TextDrawHideForPlayer(playerid, ElektronikTD[4]);
    TextDrawHideForPlayer(playerid, ElektronikTD[5]);
    TextDrawHideForPlayer(playerid, ElektronikTD[6]);
    TextDrawHideForPlayer(playerid, ElektronikTD[7]);
    TextDrawHideForPlayer(playerid, ElektronikTD[8]);
    TextDrawHideForPlayer(playerid, ElektronikTD[9]);
    TextDrawHideForPlayer(playerid, ElektronikTD[10]);
    TextDrawHideForPlayer(playerid, ElektronikTD[11]);
    TextDrawHideForPlayer(playerid, ElektronikTD[12]);
    TextDrawHideForPlayer(playerid, ElektronikTD[13]);
    TextDrawHideForPlayer(playerid, ElektronikTD[14]);
    TextDrawHideForPlayer(playerid, ElektronikTD[15]);
    TextDrawHideForPlayer(playerid, ElektronikTD[16]);
    TextDrawHideForPlayer(playerid, ElektronikTD[17]);
    TextDrawHideForPlayer(playerid, ElektronikTD[18]);
    TextDrawHideForPlayer(playerid, ElektronikTD[19]);
    TextDrawHideForPlayer(playerid, ElektronikTD[20]);
    TextDrawHideForPlayer(playerid, ElektronikTD[21]);
    TextDrawHideForPlayer(playerid, ElektronikTD[22]);
    TextDrawHideForPlayer(playerid, ElektronikTD[23]);
    TextDrawHideForPlayer(playerid, ElektronikTD[24]);
    TextDrawHideForPlayer(playerid, ElektronikTD[25]);
    TextDrawHideForPlayer(playerid, ElektronikTD[26]);
    TextDrawHideForPlayer(playerid, ElektronikTD[27]);
    TextDrawHideForPlayer(playerid, ElektronikTD[28]);
    TextDrawHideForPlayer(playerid, ElektronikTD[29]);
    TextDrawHideForPlayer(playerid, ElektronikTD[30]);
    TextDrawHideForPlayer(playerid, ElektronikTD[31]);
    TextDrawHideForPlayer(playerid, ElektronikTD[32]);
    TextDrawHideForPlayer(playerid, ElektronikTD[33]);
    TextDrawHideForPlayer(playerid, ElektronikTD[34]);
    TextDrawHideForPlayer(playerid, ElektronikTD[35]);
    CancelSelectTextDraw(playerid);
}