new 
    Text:JobCenterTD[35],
	Text:JobCenterTD2[40];

CreateJobCenterTD()
{
	JobCenterTD[0] = TextDrawCreate(381.000, 107.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD[0], 84.000, 17.000);
	TextDrawAlignment(JobCenterTD[0], 1);
	TextDrawColor(JobCenterTD[0], -849584897);
	TextDrawSetShadow(JobCenterTD[0], 0);
	TextDrawSetOutline(JobCenterTD[0], 0);
	TextDrawBackgroundColor(JobCenterTD[0], 255);
	TextDrawFont(JobCenterTD[0], 4);
	TextDrawSetProportional(JobCenterTD[0], 1);

	JobCenterTD[1] = TextDrawCreate(466.000, 107.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD[1], 13.000, 17.000);
	TextDrawAlignment(JobCenterTD[1], 1);
	TextDrawColor(JobCenterTD[1], -849584897);
	TextDrawSetShadow(JobCenterTD[1], 0);
	TextDrawSetOutline(JobCenterTD[1], 0);
	TextDrawBackgroundColor(JobCenterTD[1], 255);
	TextDrawFont(JobCenterTD[1], 4);
	TextDrawSetProportional(JobCenterTD[1], 1);
	TextDrawSetSelectable(JobCenterTD[1], 1);

	JobCenterTD[2] = TextDrawCreate(424.000, 110.500, "DISNAKER BLOKGEDONG");
	TextDrawLetterSize(JobCenterTD[2], 0.187, 0.999);
	TextDrawAlignment(JobCenterTD[2], 2);
	TextDrawColor(JobCenterTD[2], -1);
	TextDrawSetShadow(JobCenterTD[2], 1);
	TextDrawSetOutline(JobCenterTD[2], 0);
	TextDrawBackgroundColor(JobCenterTD[2], 0);
	TextDrawFont(JobCenterTD[2], 1);
	TextDrawSetProportional(JobCenterTD[2], 1);

	JobCenterTD[3] = TextDrawCreate(472.500, 110.500, "X");
	TextDrawLetterSize(JobCenterTD[3], 0.238, 0.999);
	TextDrawAlignment(JobCenterTD[3], 2);
	TextDrawColor(JobCenterTD[3], -1);
	TextDrawSetShadow(JobCenterTD[3], 1);
	TextDrawSetOutline(JobCenterTD[3], 0);
	TextDrawBackgroundColor(JobCenterTD[3], 0);
	TextDrawFont(JobCenterTD[3], 1);
	TextDrawSetProportional(JobCenterTD[3], 1);

	JobCenterTD[4] = TextDrawCreate(382.000, 127.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD[4], 109.000, 30.000);
	TextDrawAlignment(JobCenterTD[4], 1);
	TextDrawColor(JobCenterTD[4], -849584897);
	TextDrawSetShadow(JobCenterTD[4], 0);
	TextDrawSetOutline(JobCenterTD[4], 0);
	TextDrawBackgroundColor(JobCenterTD[4], 255);
	TextDrawFont(JobCenterTD[4], 4);
	TextDrawSetProportional(JobCenterTD[4], 1);
	TextDrawSetSelectable(JobCenterTD[4], 1);

	JobCenterTD[5] = TextDrawCreate(399.000, 132.000, "Petani");
	TextDrawLetterSize(JobCenterTD[5], 0.187, 0.898);
	TextDrawAlignment(JobCenterTD[5], 1);
	TextDrawColor(JobCenterTD[5], -1);
	TextDrawSetShadow(JobCenterTD[5], 1);
	TextDrawSetOutline(JobCenterTD[5], 0);
	TextDrawBackgroundColor(JobCenterTD[5], 0);
	TextDrawFont(JobCenterTD[5], 1);
	TextDrawSetProportional(JobCenterTD[5], 1);

	JobCenterTD[6] = TextDrawCreate(386.000, 143.000, "Beli bibit dan tanam untuk mendapat uang");
	TextDrawLetterSize(JobCenterTD[6], 0.119, 0.597);
	TextDrawTextSize(JobCenterTD[6], 494.000, 30.000);
	TextDrawAlignment(JobCenterTD[6], 1);
	TextDrawColor(JobCenterTD[6], -1);
	TextDrawSetShadow(JobCenterTD[6], 1);
	TextDrawSetOutline(JobCenterTD[6], 0);
	TextDrawBackgroundColor(JobCenterTD[6], 0);
	TextDrawFont(JobCenterTD[6], 1);
	TextDrawSetProportional(JobCenterTD[6], 1);

	JobCenterTD[7] = TextDrawCreate(386.000, 129.000, "LD_SLOT:grapes");
	TextDrawTextSize(JobCenterTD[7], 9.000, 11.000);
	TextDrawAlignment(JobCenterTD[7], 1);
	TextDrawColor(JobCenterTD[7], -1);
	TextDrawSetShadow(JobCenterTD[7], 0);
	TextDrawSetOutline(JobCenterTD[7], 0);
	TextDrawBackgroundColor(JobCenterTD[7], 255);
	TextDrawFont(JobCenterTD[7], 4);
	TextDrawSetProportional(JobCenterTD[7], 1);

	JobCenterTD[8] = TextDrawCreate(382.000, 160.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD[8], 109.000, 30.000);
	TextDrawAlignment(JobCenterTD[8], 1);
	TextDrawColor(JobCenterTD[8], -849584897);
	TextDrawSetShadow(JobCenterTD[8], 0);
	TextDrawSetOutline(JobCenterTD[8], 0);
	TextDrawBackgroundColor(JobCenterTD[8], 255);
	TextDrawFont(JobCenterTD[8], 4);
	TextDrawSetProportional(JobCenterTD[8], 1);
	TextDrawSetSelectable(JobCenterTD[8], 1);

	JobCenterTD[9] = TextDrawCreate(399.000, 165.000, "Penambang");
	TextDrawLetterSize(JobCenterTD[9], 0.187, 0.898);
	TextDrawAlignment(JobCenterTD[9], 1);
	TextDrawColor(JobCenterTD[9], -1);
	TextDrawSetShadow(JobCenterTD[9], 1);
	TextDrawSetOutline(JobCenterTD[9], 0);
	TextDrawBackgroundColor(JobCenterTD[9], 0);
	TextDrawFont(JobCenterTD[9], 1);
	TextDrawSetProportional(JobCenterTD[9], 1);

	JobCenterTD[10] = TextDrawCreate(386.000, 176.000, "Banyak sumber daya alam di pekerjaan ini");
	TextDrawLetterSize(JobCenterTD[10], 0.119, 0.597);
	TextDrawTextSize(JobCenterTD[10], 532.000, 30.000);
	TextDrawAlignment(JobCenterTD[10], 1);
	TextDrawColor(JobCenterTD[10], -1);
	TextDrawSetShadow(JobCenterTD[10], 1);
	TextDrawSetOutline(JobCenterTD[10], 0);
	TextDrawBackgroundColor(JobCenterTD[10], 0);
	TextDrawFont(JobCenterTD[10], 1);
	TextDrawSetProportional(JobCenterTD[10], 1);

	JobCenterTD[11] = TextDrawCreate(386.000, 164.000, "HUD:radar_bulldozer");
	TextDrawTextSize(JobCenterTD[11], 10.000, 11.000);
	TextDrawAlignment(JobCenterTD[11], 1);
	TextDrawColor(JobCenterTD[11], -1);
	TextDrawSetShadow(JobCenterTD[11], 0);
	TextDrawSetOutline(JobCenterTD[11], 0);
	TextDrawBackgroundColor(JobCenterTD[11], 255);
	TextDrawFont(JobCenterTD[11], 4);
	TextDrawSetProportional(JobCenterTD[11], 1);

	JobCenterTD[12] = TextDrawCreate(382.000, 193.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD[12], 109.000, 30.000);
	TextDrawAlignment(JobCenterTD[12], 1);
	TextDrawColor(JobCenterTD[12], -849584897);
	TextDrawSetShadow(JobCenterTD[12], 0);
	TextDrawSetOutline(JobCenterTD[12], 0);
	TextDrawBackgroundColor(JobCenterTD[12], 255);
	TextDrawFont(JobCenterTD[12], 4);
	TextDrawSetProportional(JobCenterTD[12], 1);
	TextDrawSetSelectable(JobCenterTD[12], 1);

	JobCenterTD[13] = TextDrawCreate(399.000, 198.000, "Tukang Ayam");
	TextDrawLetterSize(JobCenterTD[13], 0.187, 0.898);
	TextDrawAlignment(JobCenterTD[13], 1);
	TextDrawColor(JobCenterTD[13], -1);
	TextDrawSetShadow(JobCenterTD[13], 1);
	TextDrawSetOutline(JobCenterTD[13], 0);
	TextDrawBackgroundColor(JobCenterTD[13], 0);
	TextDrawFont(JobCenterTD[13], 1);
	TextDrawSetProportional(JobCenterTD[13], 1);

	JobCenterTD[14] = TextDrawCreate(386.000, 209.000, "Bekerja di rumah potong dan jual ayam kemasan");
	TextDrawLetterSize(JobCenterTD[14], 0.119, 0.597);
	TextDrawTextSize(JobCenterTD[14], 529.000, 30.000);
	TextDrawAlignment(JobCenterTD[14], 1);
	TextDrawColor(JobCenterTD[14], -1);
	TextDrawSetShadow(JobCenterTD[14], 1);
	TextDrawSetOutline(JobCenterTD[14], 0);
	TextDrawBackgroundColor(JobCenterTD[14], 0);
	TextDrawFont(JobCenterTD[14], 1);
	TextDrawSetProportional(JobCenterTD[14], 1);

	JobCenterTD[15] = TextDrawCreate(387.000, 199.000, "HUD:radar_chicken");
	TextDrawTextSize(JobCenterTD[15], 8.000, 10.000);
	TextDrawAlignment(JobCenterTD[15], 1);
	TextDrawColor(JobCenterTD[15], -12254977);
	TextDrawSetShadow(JobCenterTD[15], 0);
	TextDrawSetOutline(JobCenterTD[15], 0);
	TextDrawBackgroundColor(JobCenterTD[15], 255);
	TextDrawFont(JobCenterTD[15], 4);
	TextDrawSetProportional(JobCenterTD[15], 1);

	JobCenterTD[16] = TextDrawCreate(382.000, 226.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD[16], 109.000, 30.000);
	TextDrawAlignment(JobCenterTD[16], 1);
	TextDrawColor(JobCenterTD[16], -849584897);
	TextDrawSetShadow(JobCenterTD[16], 0);
	TextDrawSetOutline(JobCenterTD[16], 0);
	TextDrawBackgroundColor(JobCenterTD[16], 255);
	TextDrawFont(JobCenterTD[16], 4);
	TextDrawSetProportional(JobCenterTD[16], 1);
	TextDrawSetSelectable(JobCenterTD[16], 1);

	JobCenterTD[17] = TextDrawCreate(399.000, 231.000, "Tukang Minyak");
	TextDrawLetterSize(JobCenterTD[17], 0.187, 0.898);
	TextDrawAlignment(JobCenterTD[17], 1);
	TextDrawColor(JobCenterTD[17], -1);
	TextDrawSetShadow(JobCenterTD[17], 1);
	TextDrawSetOutline(JobCenterTD[17], 0);
	TextDrawBackgroundColor(JobCenterTD[17], 0);
	TextDrawFont(JobCenterTD[17], 1);
	TextDrawSetProportional(JobCenterTD[17], 1);

	JobCenterTD[18] = TextDrawCreate(386.000, 242.000, "Ambil minyak di kilang untuk dapat uang!");
	TextDrawLetterSize(JobCenterTD[18], 0.119, 0.597);
	TextDrawTextSize(JobCenterTD[18], 529.000, 30.000);
	TextDrawAlignment(JobCenterTD[18], 1);
	TextDrawColor(JobCenterTD[18], -1);
	TextDrawSetShadow(JobCenterTD[18], 1);
	TextDrawSetOutline(JobCenterTD[18], 0);
	TextDrawBackgroundColor(JobCenterTD[18], 0);
	TextDrawFont(JobCenterTD[18], 1);
	TextDrawSetProportional(JobCenterTD[18], 1);

	JobCenterTD[19] = TextDrawCreate(387.000, 232.000, "HUD:radar_TorenoRanch");
	TextDrawTextSize(JobCenterTD[19], 8.000, 10.000);
	TextDrawAlignment(JobCenterTD[19], 1);
	TextDrawColor(JobCenterTD[19], -1);
	TextDrawSetShadow(JobCenterTD[19], 0);
	TextDrawSetOutline(JobCenterTD[19], 0);
	TextDrawBackgroundColor(JobCenterTD[19], 255);
	TextDrawFont(JobCenterTD[19], 4);
	TextDrawSetProportional(JobCenterTD[19], 1);

	JobCenterTD[20] = TextDrawCreate(382.000, 259.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD[20], 109.000, 30.000);
	TextDrawAlignment(JobCenterTD[20], 1);
	TextDrawColor(JobCenterTD[20], -849584897);
	TextDrawSetShadow(JobCenterTD[20], 0);
	TextDrawSetOutline(JobCenterTD[20], 0);
	TextDrawBackgroundColor(JobCenterTD[20], 255);
	TextDrawFont(JobCenterTD[20], 4);
	TextDrawSetProportional(JobCenterTD[20], 1);
	TextDrawSetSelectable(JobCenterTD[20], 1);

	JobCenterTD[21] = TextDrawCreate(399.000, 264.000, "Supir Angkot");
	TextDrawLetterSize(JobCenterTD[21], 0.187, 0.898);
	TextDrawAlignment(JobCenterTD[21], 1);
	TextDrawColor(JobCenterTD[21], -1);
	TextDrawSetShadow(JobCenterTD[21], 1);
	TextDrawSetOutline(JobCenterTD[21], 0);
	TextDrawBackgroundColor(JobCenterTD[21], 0);
	TextDrawFont(JobCenterTD[21], 1);
	TextDrawSetProportional(JobCenterTD[21], 1);

	JobCenterTD[22] = TextDrawCreate(386.000, 275.000, "Nyetirin angkot dan dapatkan uang!");
	TextDrawLetterSize(JobCenterTD[22], 0.119, 0.597);
	TextDrawTextSize(JobCenterTD[22], 527.000, 30.000);
	TextDrawAlignment(JobCenterTD[22], 1);
	TextDrawColor(JobCenterTD[22], -1);
	TextDrawSetShadow(JobCenterTD[22], 1);
	TextDrawSetOutline(JobCenterTD[22], 0);
	TextDrawBackgroundColor(JobCenterTD[22], 0);
	TextDrawFont(JobCenterTD[22], 1);
	TextDrawSetProportional(JobCenterTD[22], 1);

	JobCenterTD[23] = TextDrawCreate(387.000, 265.000, "HUD:radar_gangN");
	TextDrawTextSize(JobCenterTD[23], 8.000, 9.000);
	TextDrawAlignment(JobCenterTD[23], 1);
	TextDrawColor(JobCenterTD[23], -1);
	TextDrawSetShadow(JobCenterTD[23], 0);
	TextDrawSetOutline(JobCenterTD[23], 0);
	TextDrawBackgroundColor(JobCenterTD[23], 255);
	TextDrawFont(JobCenterTD[23], 4);
	TextDrawSetProportional(JobCenterTD[23], 1);

	JobCenterTD[24] = TextDrawCreate(382.000, 292.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD[24], 109.000, 30.000);
	TextDrawAlignment(JobCenterTD[24], 1);
	TextDrawColor(JobCenterTD[24], -849584897);
	TextDrawSetShadow(JobCenterTD[24], 0);
	TextDrawSetOutline(JobCenterTD[24], 0);
	TextDrawBackgroundColor(JobCenterTD[24], 255);
	TextDrawFont(JobCenterTD[24], 4);
	TextDrawSetProportional(JobCenterTD[24], 1);
	TextDrawSetSelectable(JobCenterTD[24], 1);

	JobCenterTD[25] = TextDrawCreate(399.000, 297.000, "Nelayan");
	TextDrawLetterSize(JobCenterTD[25], 0.187, 0.898);
	TextDrawAlignment(JobCenterTD[25], 1);
	TextDrawColor(JobCenterTD[25], -1);
	TextDrawSetShadow(JobCenterTD[25], 1);
	TextDrawSetOutline(JobCenterTD[25], 0);
	TextDrawBackgroundColor(JobCenterTD[25], 0);
	TextDrawFont(JobCenterTD[25], 1);
	TextDrawSetProportional(JobCenterTD[25], 1);

	JobCenterTD[26] = TextDrawCreate(386.000, 308.000, "Ambil kapal dan jala ikan di tengah laut!");
	TextDrawLetterSize(JobCenterTD[26], 0.119, 0.597);
	TextDrawTextSize(JobCenterTD[26], 527.000, 30.000);
	TextDrawAlignment(JobCenterTD[26], 1);
	TextDrawColor(JobCenterTD[26], -1);
	TextDrawSetShadow(JobCenterTD[26], 1);
	TextDrawSetOutline(JobCenterTD[26], 0);
	TextDrawBackgroundColor(JobCenterTD[26], 0);
	TextDrawFont(JobCenterTD[26], 1);
	TextDrawSetProportional(JobCenterTD[26], 1);

	JobCenterTD[27] = TextDrawCreate(387.000, 298.000, "HUD:radar_runway");
	TextDrawTextSize(JobCenterTD[27], 8.000, 9.000);
	TextDrawAlignment(JobCenterTD[27], 1);
	TextDrawColor(JobCenterTD[27], -1);
	TextDrawSetShadow(JobCenterTD[27], 0);
	TextDrawSetOutline(JobCenterTD[27], 0);
	TextDrawBackgroundColor(JobCenterTD[27], 255);
	TextDrawFont(JobCenterTD[27], 4);
	TextDrawSetProportional(JobCenterTD[27], 1);

	JobCenterTD[28] = TextDrawCreate(382.000, 325.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD[28], 109.000, 30.000);
	TextDrawAlignment(JobCenterTD[28], 1);
	TextDrawColor(JobCenterTD[28], -849584897);
	TextDrawSetShadow(JobCenterTD[28], 0);
	TextDrawSetOutline(JobCenterTD[28], 0);
	TextDrawBackgroundColor(JobCenterTD[28], 255);
	TextDrawFont(JobCenterTD[28], 4);
	TextDrawSetProportional(JobCenterTD[28], 1);
	TextDrawSetSelectable(JobCenterTD[28], 1);

	JobCenterTD[29] = TextDrawCreate(399.000, 330.000, "Supir Kargo");
	TextDrawLetterSize(JobCenterTD[29], 0.187, 0.898);
	TextDrawAlignment(JobCenterTD[29], 1);
	TextDrawColor(JobCenterTD[29], -1);
	TextDrawSetShadow(JobCenterTD[29], 1);
	TextDrawSetOutline(JobCenterTD[29], 0);
	TextDrawBackgroundColor(JobCenterTD[29], 0);
	TextDrawFont(JobCenterTD[29], 1);
	TextDrawSetProportional(JobCenterTD[29], 1);

	JobCenterTD[30] = TextDrawCreate(386.000, 341.000, "Antar barang dengan truk trailer!");
	TextDrawLetterSize(JobCenterTD[30], 0.119, 0.597);
	TextDrawTextSize(JobCenterTD[30], 527.000, 30.000);
	TextDrawAlignment(JobCenterTD[30], 1);
	TextDrawColor(JobCenterTD[30], -1);
	TextDrawSetShadow(JobCenterTD[30], 1);
	TextDrawSetOutline(JobCenterTD[30], 0);
	TextDrawBackgroundColor(JobCenterTD[30], 0);
	TextDrawFont(JobCenterTD[30], 1);
	TextDrawSetProportional(JobCenterTD[30], 1);

	JobCenterTD[31] = TextDrawCreate(480.000, 107.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD[31], 11.000, 17.000);
	TextDrawAlignment(JobCenterTD[31], 1);
	TextDrawColor(JobCenterTD[31], -849584897);
	TextDrawSetShadow(JobCenterTD[31], 0);
	TextDrawSetOutline(JobCenterTD[31], 0);
	TextDrawBackgroundColor(JobCenterTD[31], 255);
	TextDrawFont(JobCenterTD[31], 4);
	TextDrawSetProportional(JobCenterTD[31], 1);
	TextDrawSetSelectable(JobCenterTD[31], 1);

	JobCenterTD[32] = TextDrawCreate(485.500, 106.500, ">");
	TextDrawLetterSize(JobCenterTD[32], 0.238, 1.899);
	TextDrawAlignment(JobCenterTD[32], 2);
	TextDrawColor(JobCenterTD[32], -1);
	TextDrawSetShadow(JobCenterTD[32], 1);
	TextDrawSetOutline(JobCenterTD[32], 0);
	TextDrawBackgroundColor(JobCenterTD[32], 0);
	TextDrawFont(JobCenterTD[32], 1);
	TextDrawSetProportional(JobCenterTD[32], 1);

	JobCenterTD[33] = TextDrawCreate(380.000, 107.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD[33], 2.000, 248.000);
	TextDrawAlignment(JobCenterTD[33], 1);
	TextDrawColor(JobCenterTD[33], -1);
	TextDrawSetShadow(JobCenterTD[33], 0);
	TextDrawSetOutline(JobCenterTD[33], 0);
	TextDrawBackgroundColor(JobCenterTD[33], 255);
	TextDrawFont(JobCenterTD[33], 4);
	TextDrawSetProportional(JobCenterTD[33], 1);

	JobCenterTD[34] = TextDrawCreate(388.000, 331.000, "HUD:radar_truck");
	TextDrawTextSize(JobCenterTD[34], 7.000, 8.000);
	TextDrawAlignment(JobCenterTD[34], 1);
	TextDrawColor(JobCenterTD[34], -1);
	TextDrawSetShadow(JobCenterTD[34], 0);
	TextDrawSetOutline(JobCenterTD[34], 0);
	TextDrawBackgroundColor(JobCenterTD[34], 255);
	TextDrawFont(JobCenterTD[34], 4);
	TextDrawSetProportional(JobCenterTD[34], 1);

}

CreateJobCenterTD2()
{
	JobCenterTD2[0] = TextDrawCreate(381.000, 107.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD2[0], 84.000, 17.000);
	TextDrawAlignment(JobCenterTD2[0], 1);
	TextDrawColor(JobCenterTD2[0], -849584897);
	TextDrawSetShadow(JobCenterTD2[0], 0);
	TextDrawSetOutline(JobCenterTD2[0], 0);
	TextDrawBackgroundColor(JobCenterTD2[0], 255);
	TextDrawFont(JobCenterTD2[0], 4);
	TextDrawSetProportional(JobCenterTD2[0], 1);

	JobCenterTD2[1] = TextDrawCreate(466.000, 107.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD2[1], 13.000, 17.000);
	TextDrawAlignment(JobCenterTD2[1], 1);
	TextDrawColor(JobCenterTD2[1], -849584897);
	TextDrawSetShadow(JobCenterTD2[1], 0);
	TextDrawSetOutline(JobCenterTD2[1], 0);
	TextDrawBackgroundColor(JobCenterTD2[1], 255);
	TextDrawFont(JobCenterTD2[1], 4);
	TextDrawSetProportional(JobCenterTD2[1], 1);
	TextDrawSetSelectable(JobCenterTD2[1], 1);

	JobCenterTD2[2] = TextDrawCreate(424.000, 110.500, "DISNAKER BLOKGEDONG");
	TextDrawLetterSize(JobCenterTD2[2], 0.187, 0.999);
	TextDrawAlignment(JobCenterTD2[2], 2);
	TextDrawColor(JobCenterTD2[2], -1);
	TextDrawSetShadow(JobCenterTD2[2], 1);
	TextDrawSetOutline(JobCenterTD2[2], 0);
	TextDrawBackgroundColor(JobCenterTD2[2], 0);
	TextDrawFont(JobCenterTD2[2], 1);
	TextDrawSetProportional(JobCenterTD2[2], 1);

	JobCenterTD2[3] = TextDrawCreate(472.500, 110.500, "X");
	TextDrawLetterSize(JobCenterTD2[3], 0.238, 0.999);
	TextDrawAlignment(JobCenterTD2[3], 2);
	TextDrawColor(JobCenterTD2[3], -1);
	TextDrawSetShadow(JobCenterTD2[3], 1);
	TextDrawSetOutline(JobCenterTD2[3], 0);
	TextDrawBackgroundColor(JobCenterTD2[3], 0);
	TextDrawFont(JobCenterTD2[3], 1);
	TextDrawSetProportional(JobCenterTD2[3], 1);

	JobCenterTD2[4] = TextDrawCreate(399.000, 330.000, "Pengangguran");
	TextDrawLetterSize(JobCenterTD2[4], 0.187, 0.898);
	TextDrawAlignment(JobCenterTD2[4], 1);
	TextDrawColor(JobCenterTD2[4], -1);
	TextDrawSetShadow(JobCenterTD2[4], 1);
	TextDrawSetOutline(JobCenterTD2[4], 0);
	TextDrawBackgroundColor(JobCenterTD2[4], 0);
	TextDrawFont(JobCenterTD2[4], 1);
	TextDrawSetProportional(JobCenterTD2[4], 1);

	JobCenterTD2[5] = TextDrawCreate(382.000, 325.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD2[5], 109.000, 30.000);
	TextDrawAlignment(JobCenterTD2[5], 1);
	TextDrawColor(JobCenterTD2[5], -849584897);
	TextDrawSetShadow(JobCenterTD2[5], 0);
	TextDrawSetOutline(JobCenterTD2[5], 0);
	TextDrawBackgroundColor(JobCenterTD2[5], 255);
	TextDrawFont(JobCenterTD2[5], 4);
	TextDrawSetProportional(JobCenterTD2[5], 1);
	TextDrawSetSelectable(JobCenterTD2[5], 1);

	JobCenterTD2[6] = TextDrawCreate(399.000, 297.000, "Penjahit");
	TextDrawLetterSize(JobCenterTD2[6], 0.187, 0.898);
	TextDrawAlignment(JobCenterTD2[6], 1);
	TextDrawColor(JobCenterTD2[6], -1);
	TextDrawSetShadow(JobCenterTD2[6], 1);
	TextDrawSetOutline(JobCenterTD2[6], 0);
	TextDrawBackgroundColor(JobCenterTD2[6], 0);
	TextDrawFont(JobCenterTD2[6], 1);
	TextDrawSetProportional(JobCenterTD2[6], 1);

	JobCenterTD2[7] = TextDrawCreate(382.000, 292.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD2[7], 109.000, 30.000);
	TextDrawAlignment(JobCenterTD2[7], 1);
	TextDrawColor(JobCenterTD2[7], -849584897);
	TextDrawSetShadow(JobCenterTD2[7], 0);
	TextDrawSetOutline(JobCenterTD2[7], 0);
	TextDrawBackgroundColor(JobCenterTD2[7], 255);
	TextDrawFont(JobCenterTD2[7], 4);
	TextDrawSetProportional(JobCenterTD2[7], 1);
	TextDrawSetSelectable(JobCenterTD2[7], 1);

	JobCenterTD2[8] = TextDrawCreate(399.000, 264.000, "Peternak");
	TextDrawLetterSize(JobCenterTD2[8], 0.187, 0.898);
	TextDrawAlignment(JobCenterTD2[8], 1);
	TextDrawColor(JobCenterTD2[8], -1);
	TextDrawSetShadow(JobCenterTD2[8], 1);
	TextDrawSetOutline(JobCenterTD2[8], 0);
	TextDrawBackgroundColor(JobCenterTD2[8], 0);
	TextDrawFont(JobCenterTD2[8], 1);
	TextDrawSetProportional(JobCenterTD2[8], 1);

	JobCenterTD2[9] = TextDrawCreate(382.000, 259.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD2[9], 109.000, 30.000);
	TextDrawAlignment(JobCenterTD2[9], 1);
	TextDrawColor(JobCenterTD2[9], -849584897);
	TextDrawSetShadow(JobCenterTD2[9], 0);
	TextDrawSetOutline(JobCenterTD2[9], 0);
	TextDrawBackgroundColor(JobCenterTD2[9], 255);
	TextDrawFont(JobCenterTD2[9], 4);
	TextDrawSetProportional(JobCenterTD2[9], 1);
	TextDrawSetSelectable(JobCenterTD2[9], 1);

	JobCenterTD2[10] = TextDrawCreate(399.000, 231.000, "Pelaut");
	TextDrawLetterSize(JobCenterTD2[10], 0.187, 0.898);
	TextDrawAlignment(JobCenterTD2[10], 1);
	TextDrawColor(JobCenterTD2[10], -1);
	TextDrawSetShadow(JobCenterTD2[10], 1);
	TextDrawSetOutline(JobCenterTD2[10], 0);
	TextDrawBackgroundColor(JobCenterTD2[10], 0);
	TextDrawFont(JobCenterTD2[10], 1);
	TextDrawSetProportional(JobCenterTD2[10], 1);

	JobCenterTD2[11] = TextDrawCreate(382.000, 226.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD2[11], 109.000, 30.000);
	TextDrawAlignment(JobCenterTD2[11], 1);
	TextDrawColor(JobCenterTD2[11], -849584897);
	TextDrawSetShadow(JobCenterTD2[11], 0);
	TextDrawSetOutline(JobCenterTD2[11], 0);
	TextDrawBackgroundColor(JobCenterTD2[11], 255);
	TextDrawFont(JobCenterTD2[11], 4);
	TextDrawSetProportional(JobCenterTD2[11], 1);
	TextDrawSetSelectable(JobCenterTD2[11], 1);

	JobCenterTD2[12] = TextDrawCreate(399.000, 198.000, "Tukang Kayu");
	TextDrawLetterSize(JobCenterTD2[12], 0.187, 0.898);
	TextDrawAlignment(JobCenterTD2[12], 1);
	TextDrawColor(JobCenterTD2[12], -1);
	TextDrawSetShadow(JobCenterTD2[12], 1);
	TextDrawSetOutline(JobCenterTD2[12], 0);
	TextDrawBackgroundColor(JobCenterTD2[12], 0);
	TextDrawFont(JobCenterTD2[12], 1);
	TextDrawSetProportional(JobCenterTD2[12], 1);

	JobCenterTD2[13] = TextDrawCreate(382.000, 193.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD2[13], 109.000, 30.000);
	TextDrawAlignment(JobCenterTD2[13], 1);
	TextDrawColor(JobCenterTD2[13], -849584897);
	TextDrawSetShadow(JobCenterTD2[13], 0);
	TextDrawSetOutline(JobCenterTD2[13], 0);
	TextDrawBackgroundColor(JobCenterTD2[13], 255);
	TextDrawFont(JobCenterTD2[13], 4);
	TextDrawSetProportional(JobCenterTD2[13], 1);
	TextDrawSetSelectable(JobCenterTD2[13], 1);

	JobCenterTD2[14] = TextDrawCreate(386.000, 164.000, "HUD:radar_MCSTRAP");
	TextDrawTextSize(JobCenterTD2[14], 8.000, 9.000);
	TextDrawAlignment(JobCenterTD2[14], 1);
	TextDrawColor(JobCenterTD2[14], -1);
	TextDrawSetShadow(JobCenterTD2[14], 0);
	TextDrawSetOutline(JobCenterTD2[14], 0);
	TextDrawBackgroundColor(JobCenterTD2[14], 255);
	TextDrawFont(JobCenterTD2[14], 4);
	TextDrawSetProportional(JobCenterTD2[14], 1);

	JobCenterTD2[15] = TextDrawCreate(399.000, 165.000, "Supir Mixer");
	TextDrawLetterSize(JobCenterTD2[15], 0.187, 0.898);
	TextDrawAlignment(JobCenterTD2[15], 1);
	TextDrawColor(JobCenterTD2[15], -1);
	TextDrawSetShadow(JobCenterTD2[15], 1);
	TextDrawSetOutline(JobCenterTD2[15], 0);
	TextDrawBackgroundColor(JobCenterTD2[15], 0);
	TextDrawFont(JobCenterTD2[15], 1);
	TextDrawSetProportional(JobCenterTD2[15], 1);

	JobCenterTD2[16] = TextDrawCreate(382.000, 160.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD2[16], 109.000, 30.000);
	TextDrawAlignment(JobCenterTD2[16], 1);
	TextDrawColor(JobCenterTD2[16], -849584897);
	TextDrawSetShadow(JobCenterTD2[16], 0);
	TextDrawSetOutline(JobCenterTD2[16], 0);
	TextDrawBackgroundColor(JobCenterTD2[16], 255);
	TextDrawFont(JobCenterTD2[16], 4);
	TextDrawSetProportional(JobCenterTD2[16], 1);
	TextDrawSetSelectable(JobCenterTD2[16], 1);

	JobCenterTD2[17] = TextDrawCreate(386.000, 331.000, "HUD:radar_propertyR");
	TextDrawTextSize(JobCenterTD2[17], 8.000, 9.000);
	TextDrawAlignment(JobCenterTD2[17], 1);
	TextDrawColor(JobCenterTD2[17], -1);
	TextDrawSetShadow(JobCenterTD2[17], 0);
	TextDrawSetOutline(JobCenterTD2[17], 0);
	TextDrawBackgroundColor(JobCenterTD2[17], 255);
	TextDrawFont(JobCenterTD2[17], 4);
	TextDrawSetProportional(JobCenterTD2[17], 1);

	JobCenterTD2[18] = TextDrawCreate(399.000, 132.000, "Porter");
	TextDrawLetterSize(JobCenterTD2[18], 0.187, 0.898);
	TextDrawAlignment(JobCenterTD2[18], 1);
	TextDrawColor(JobCenterTD2[18], -1);
	TextDrawSetShadow(JobCenterTD2[18], 1);
	TextDrawSetOutline(JobCenterTD2[18], 0);
	TextDrawBackgroundColor(JobCenterTD2[18], 0);
	TextDrawFont(JobCenterTD2[18], 1);
	TextDrawSetProportional(JobCenterTD2[18], 1);

	JobCenterTD2[19] = TextDrawCreate(382.000, 127.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD2[19], 109.000, 30.000);
	TextDrawAlignment(JobCenterTD2[19], 1);
	TextDrawColor(JobCenterTD2[19], -849584897);
	TextDrawSetShadow(JobCenterTD2[19], 0);
	TextDrawSetOutline(JobCenterTD2[19], 0);
	TextDrawBackgroundColor(JobCenterTD2[19], 255);
	TextDrawFont(JobCenterTD2[19], 4);
	TextDrawSetProportional(JobCenterTD2[19], 1);
	TextDrawSetSelectable(JobCenterTD2[19], 1);

	JobCenterTD2[20] = TextDrawCreate(386.000, 143.000, "Angkut dan pindahkan barang di dermaga untuk dapatkan uang");
	TextDrawLetterSize(JobCenterTD2[20], 0.098, 0.697);
	TextDrawTextSize(JobCenterTD2[20], 614.000, 30.000);
	TextDrawAlignment(JobCenterTD2[20], 1);
	TextDrawColor(JobCenterTD2[20], -1);
	TextDrawSetShadow(JobCenterTD2[20], 1);
	TextDrawSetOutline(JobCenterTD2[20], 0);
	TextDrawBackgroundColor(JobCenterTD2[20], 0);
	TextDrawFont(JobCenterTD2[20], 1);
	TextDrawSetProportional(JobCenterTD2[20], 1);

	JobCenterTD2[21] = TextDrawCreate(386.000, 242.000, "Bawalah kapal mengarungi laut untuk mendapat uang!");
	TextDrawLetterSize(JobCenterTD2[21], 0.108, 0.597);
	TextDrawTextSize(JobCenterTD2[21], 614.000, 30.000);
	TextDrawAlignment(JobCenterTD2[21], 1);
	TextDrawColor(JobCenterTD2[21], -1);
	TextDrawSetShadow(JobCenterTD2[21], 1);
	TextDrawSetOutline(JobCenterTD2[21], 0);
	TextDrawBackgroundColor(JobCenterTD2[21], 0);
	TextDrawFont(JobCenterTD2[21], 1);
	TextDrawSetProportional(JobCenterTD2[21], 1);

	JobCenterTD2[22] = TextDrawCreate(387.000, 344.000, "Inilah anda di dunia nyata!");
	TextDrawLetterSize(JobCenterTD2[22], 0.119, 0.597);
	TextDrawTextSize(JobCenterTD2[22], 614.000, 30.000);
	TextDrawAlignment(JobCenterTD2[22], 1);
	TextDrawColor(JobCenterTD2[22], -1);
	TextDrawSetShadow(JobCenterTD2[22], 1);
	TextDrawSetOutline(JobCenterTD2[22], 0);
	TextDrawBackgroundColor(JobCenterTD2[22], 0);
	TextDrawFont(JobCenterTD2[22], 1);
	TextDrawSetProportional(JobCenterTD2[22], 1);

	JobCenterTD2[23] = TextDrawCreate(386.000, 177.000, "Aduk beton dan jaga kualitas slump sampai tujuan!");
	TextDrawLetterSize(JobCenterTD2[23], 0.119, 0.597);
	TextDrawTextSize(JobCenterTD2[23], 614.000, 30.000);
	TextDrawAlignment(JobCenterTD2[23], 1);
	TextDrawColor(JobCenterTD2[23], -1);
	TextDrawSetShadow(JobCenterTD2[23], 1);
	TextDrawSetOutline(JobCenterTD2[23], 0);
	TextDrawBackgroundColor(JobCenterTD2[23], 0);
	TextDrawFont(JobCenterTD2[23], 1);
	TextDrawSetProportional(JobCenterTD2[23], 1);

	JobCenterTD2[24] = TextDrawCreate(386.000, 308.000, "Buat pakaian lalu jual untuk dapat uang!");
	TextDrawLetterSize(JobCenterTD2[24], 0.119, 0.597);
	TextDrawTextSize(JobCenterTD2[24], 614.000, 30.000);
	TextDrawAlignment(JobCenterTD2[24], 1);
	TextDrawColor(JobCenterTD2[24], -1);
	TextDrawSetShadow(JobCenterTD2[24], 1);
	TextDrawSetOutline(JobCenterTD2[24], 0);
	TextDrawBackgroundColor(JobCenterTD2[24], 0);
	TextDrawFont(JobCenterTD2[24], 1);
	TextDrawSetProportional(JobCenterTD2[24], 1);

	JobCenterTD2[25] = TextDrawCreate(386.000, 209.000, "Ambil kayu dan buatlah papan untuk mendapatkan uang!");
	TextDrawLetterSize(JobCenterTD2[25], 0.108, 0.597);
	TextDrawTextSize(JobCenterTD2[25], 614.000, 30.000);
	TextDrawAlignment(JobCenterTD2[25], 1);
	TextDrawColor(JobCenterTD2[25], -1);
	TextDrawSetShadow(JobCenterTD2[25], 1);
	TextDrawSetOutline(JobCenterTD2[25], 0);
	TextDrawBackgroundColor(JobCenterTD2[25], 0);
	TextDrawFont(JobCenterTD2[25], 1);
	TextDrawSetProportional(JobCenterTD2[25], 1);

	JobCenterTD2[26] = TextDrawCreate(386.000, 275.000, "Peras susu dan jual susu fermentasi!");
	TextDrawLetterSize(JobCenterTD2[26], 0.119, 0.597);
	TextDrawTextSize(JobCenterTD2[26], 614.000, 30.000);
	TextDrawAlignment(JobCenterTD2[26], 1);
	TextDrawColor(JobCenterTD2[26], -1);
	TextDrawSetShadow(JobCenterTD2[26], 1);
	TextDrawSetOutline(JobCenterTD2[26], 0);
	TextDrawBackgroundColor(JobCenterTD2[26], 0);
	TextDrawFont(JobCenterTD2[26], 1);
	TextDrawSetProportional(JobCenterTD2[26], 1);

	JobCenterTD2[27] = TextDrawCreate(386.000, 129.000, "HUD:radar_MADDOG");
	TextDrawTextSize(JobCenterTD2[27], 9.000, 11.000);
	TextDrawAlignment(JobCenterTD2[27], 1);
	TextDrawColor(JobCenterTD2[27], -1);
	TextDrawSetShadow(JobCenterTD2[27], 0);
	TextDrawSetOutline(JobCenterTD2[27], 0);
	TextDrawBackgroundColor(JobCenterTD2[27], 255);
	TextDrawFont(JobCenterTD2[27], 4);
	TextDrawSetProportional(JobCenterTD2[27], 1);

	JobCenterTD2[28] = TextDrawCreate(387.000, 265.000, "HUD:radar_centre");
	TextDrawTextSize(JobCenterTD2[28], 7.000, 7.000);
	TextDrawAlignment(JobCenterTD2[28], 1);
	TextDrawColor(JobCenterTD2[28], -1);
	TextDrawSetShadow(JobCenterTD2[28], 0);
	TextDrawSetOutline(JobCenterTD2[28], 0);
	TextDrawBackgroundColor(JobCenterTD2[28], 255);
	TextDrawFont(JobCenterTD2[28], 4);
	TextDrawSetProportional(JobCenterTD2[28], 1);

	JobCenterTD2[29] = TextDrawCreate(387.000, 165.000, "HUD:radar_MCSTRAP");
	TextDrawTextSize(JobCenterTD2[29], 8.000, 10.000);
	TextDrawAlignment(JobCenterTD2[29], 1);
	TextDrawColor(JobCenterTD2[29], -1);
	TextDrawSetShadow(JobCenterTD2[29], 0);
	TextDrawSetOutline(JobCenterTD2[29], 0);
	TextDrawBackgroundColor(JobCenterTD2[29], 255);
	TextDrawFont(JobCenterTD2[29], 4);
	TextDrawSetProportional(JobCenterTD2[29], 1);

	JobCenterTD2[30] = TextDrawCreate(387.000, 298.000, "HUD:radar_tshirt");
	TextDrawTextSize(JobCenterTD2[30], 8.000, 8.000);
	TextDrawAlignment(JobCenterTD2[30], 1);
	TextDrawColor(JobCenterTD2[30], -1);
	TextDrawSetShadow(JobCenterTD2[30], 0);
	TextDrawSetOutline(JobCenterTD2[30], 0);
	TextDrawBackgroundColor(JobCenterTD2[30], 255);
	TextDrawFont(JobCenterTD2[30], 4);
	TextDrawSetProportional(JobCenterTD2[30], 1);

	JobCenterTD2[31] = TextDrawCreate(388.000, 230.000, "HUD:radar_boatyard");
	TextDrawTextSize(JobCenterTD2[31], 6.000, 9.000);
	TextDrawAlignment(JobCenterTD2[31], 1);
	TextDrawColor(JobCenterTD2[31], -1);
	TextDrawSetShadow(JobCenterTD2[31], 0);
	TextDrawSetOutline(JobCenterTD2[31], 0);
	TextDrawBackgroundColor(JobCenterTD2[31], 255);
	TextDrawFont(JobCenterTD2[31], 4);
	TextDrawSetProportional(JobCenterTD2[31], 1);

	JobCenterTD2[32] = TextDrawCreate(387.000, 198.000, "HUD:radar_light");
	TextDrawTextSize(JobCenterTD2[32], 9.000, 10.000);
	TextDrawAlignment(JobCenterTD2[32], 1);
	TextDrawColor(JobCenterTD2[32], -1);
	TextDrawSetShadow(JobCenterTD2[32], 0);
	TextDrawSetOutline(JobCenterTD2[32], 0);
	TextDrawBackgroundColor(JobCenterTD2[32], 255);
	TextDrawFont(JobCenterTD2[32], 4);
	TextDrawSetProportional(JobCenterTD2[32], 1);

	JobCenterTD2[33] = TextDrawCreate(380.000, 107.000, "LD_SPAC:white");
	TextDrawTextSize(JobCenterTD2[33], 2.000, 282.000);
	TextDrawAlignment(JobCenterTD2[33], 1);
	TextDrawColor(JobCenterTD2[33], -1);
	TextDrawSetShadow(JobCenterTD2[33], 0);
	TextDrawSetOutline(JobCenterTD2[33], 0);
	TextDrawBackgroundColor(JobCenterTD2[33], 255);
	TextDrawFont(JobCenterTD2[33], 4);
	TextDrawSetProportional(JobCenterTD2[33], 1);

	JobCenterTD2[34] = TextDrawCreate(480.000, 107.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD2[34], 11.000, 17.000);
	TextDrawAlignment(JobCenterTD2[34], 1);
	TextDrawColor(JobCenterTD2[34], -849584897);
	TextDrawSetShadow(JobCenterTD2[34], 0);
	TextDrawSetOutline(JobCenterTD2[34], 0);
	TextDrawBackgroundColor(JobCenterTD2[34], 255);
	TextDrawFont(JobCenterTD2[34], 4);
	TextDrawSetProportional(JobCenterTD2[34], 1);
	TextDrawSetSelectable(JobCenterTD2[34], 1);

	JobCenterTD2[35] = TextDrawCreate(485.500, 107.500, "<");
	TextDrawLetterSize(JobCenterTD2[35], 0.238, 1.598);
	TextDrawAlignment(JobCenterTD2[35], 2);
	TextDrawColor(JobCenterTD2[35], -1);
	TextDrawSetShadow(JobCenterTD2[35], 1);
	TextDrawSetOutline(JobCenterTD2[35], 0);
	TextDrawBackgroundColor(JobCenterTD2[35], 0);
	TextDrawFont(JobCenterTD2[35], 1);
	TextDrawSetProportional(JobCenterTD2[35], 1);

	JobCenterTD2[36] = TextDrawCreate(382.000, 358.000, "LD_BUM:blkdot");
	TextDrawTextSize(JobCenterTD2[36], 109.000, 30.000);
	TextDrawAlignment(JobCenterTD2[36], 1);
	TextDrawColor(JobCenterTD2[36], -849584897);
	TextDrawSetShadow(JobCenterTD2[36], 0);
	TextDrawSetOutline(JobCenterTD2[36], 0);
	TextDrawBackgroundColor(JobCenterTD2[36], 255);
	TextDrawFont(JobCenterTD2[36], 4);
	TextDrawSetProportional(JobCenterTD2[36], 1);
	TextDrawSetSelectable(JobCenterTD2[36], 1);

	JobCenterTD2[37] = TextDrawCreate(399.000, 363.000, "Tukang Sawit");
	TextDrawLetterSize(JobCenterTD2[37], 0.187, 0.898);
	TextDrawAlignment(JobCenterTD2[37], 1);
	TextDrawColor(JobCenterTD2[37], -1);
	TextDrawSetShadow(JobCenterTD2[37], 1);
	TextDrawSetOutline(JobCenterTD2[37], 0);
	TextDrawBackgroundColor(JobCenterTD2[37], 0);
	TextDrawFont(JobCenterTD2[37], 1);
	TextDrawSetProportional(JobCenterTD2[37], 1);

	JobCenterTD2[38] = TextDrawCreate(387.000, 374.000, "ambil sawit dan jadikan minyak sawit");
	TextDrawLetterSize(JobCenterTD2[38], 0.119, 0.597);
	TextDrawTextSize(JobCenterTD2[38], 614.000, 30.000);
	TextDrawAlignment(JobCenterTD2[38], 1);
	TextDrawColor(JobCenterTD2[38], -1);
	TextDrawSetShadow(JobCenterTD2[38], 1);
	TextDrawSetOutline(JobCenterTD2[38], 0);
	TextDrawBackgroundColor(JobCenterTD2[38], 0);
	TextDrawFont(JobCenterTD2[38], 1);
	TextDrawSetProportional(JobCenterTD2[38], 1);

	JobCenterTD2[39] = TextDrawCreate(387.000, 363.000, "HUD:radar_light");
	TextDrawTextSize(JobCenterTD2[39], 9.000, 10.000);
	TextDrawAlignment(JobCenterTD2[39], 1);
	TextDrawColor(JobCenterTD2[39], -1);
	TextDrawSetShadow(JobCenterTD2[39], 0);
	TextDrawSetOutline(JobCenterTD2[39], 0);
	TextDrawBackgroundColor(JobCenterTD2[39], 255);
	TextDrawFont(JobCenterTD2[39], 4);
	TextDrawSetProportional(JobCenterTD2[39], 1);

}

ShowJobCenterTD(playerid)
{
	for(new x; x < 35; x++)
	{
		TextDrawShowForPlayer(playerid, JobCenterTD[x]);
	}
	HideHBETD(playerid);
	HideStatsTD(playerid);
	HideServerNameTD(playerid);
	SelectTextDraw(playerid, 0xff91a4cc);
}

HideJobCenterTD(playerid)
{
	for(new x; x < 35; x++)
	{
		TextDrawHideForPlayer(playerid, JobCenterTD[x]);
	}

	ShowHBETD(playerid);
	ShowStatsTD(playerid);
	ShowServerNameTD(playerid);
	CancelSelectTextDraw(playerid);
}

ShowJobCenterTD2(playerid)
{
	for(new x; x < 40; x++)
	{
		TextDrawShowForPlayer(playerid, JobCenterTD2[x]);
	}
	HideHBETD(playerid);
	HideStatsTD(playerid);
	HideServerNameTD(playerid);
	SelectTextDraw(playerid, 0xff91a4cc);
}

HideJobCenterTD2(playerid)
{
	for(new x; x < 40; x++)
	{
		TextDrawHideForPlayer(playerid, JobCenterTD2[x]);
	}

	ShowHBETD(playerid);
	ShowStatsTD(playerid);
	ShowServerNameTD(playerid);
	CancelSelectTextDraw(playerid);
}