new Text: MarketPage1[76],
    Text: MarketPage2[77];

CreateMarket1()
{
	MarketPage1[0] = TextDrawCreate(174.000, 178.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[0], 65.000, 43.000);
	TextDrawAlignment(MarketPage1[0], 1);
	TextDrawColor(MarketPage1[0], -377187329);
	TextDrawSetShadow(MarketPage1[0], 0);
	TextDrawSetOutline(MarketPage1[0], 0);
	TextDrawBackgroundColor(MarketPage1[0], 255);
	TextDrawFont(MarketPage1[0], 4);
	TextDrawSetProportional(MarketPage1[0], 1);

	MarketPage1[1] = TextDrawCreate(176.000, 180.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[1], 61.000, 37.000);
	TextDrawAlignment(MarketPage1[1], 1);
	TextDrawColor(MarketPage1[1], -377187329);
	TextDrawSetShadow(MarketPage1[1], 0);
	TextDrawSetOutline(MarketPage1[1], 0);
	TextDrawBackgroundColor(MarketPage1[1], 255);
	TextDrawFont(MarketPage1[1], 4);
	TextDrawSetProportional(MarketPage1[1], 1);

	MarketPage1[2] = TextDrawCreate(169.000, 156.000, "LD_BEAT:chit");
	TextDrawTextSize(MarketPage1[2], 21.000, 20.000);
	TextDrawAlignment(MarketPage1[2], 1);
	TextDrawColor(MarketPage1[2], -377187329);
	TextDrawSetShadow(MarketPage1[2], 0);
	TextDrawSetOutline(MarketPage1[2], 0);
	TextDrawBackgroundColor(MarketPage1[2], 255);
	TextDrawFont(MarketPage1[2], 4);
	TextDrawSetProportional(MarketPage1[2], 1);

	MarketPage1[3] = TextDrawCreate(172.000, 141.000, "LD_BEAT:chit");
	TextDrawTextSize(MarketPage1[3], 15.000, 18.000);
	TextDrawAlignment(MarketPage1[3], 1);
	TextDrawColor(MarketPage1[3], -377187329);
	TextDrawSetShadow(MarketPage1[3], 0);
	TextDrawSetOutline(MarketPage1[3], 0);
	TextDrawBackgroundColor(MarketPage1[3], 255);
	TextDrawFont(MarketPage1[3], 4);
	TextDrawSetProportional(MarketPage1[3], 1);

	MarketPage1[4] = TextDrawCreate(185.000, 230.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[4], 45.000, 24.000);
	TextDrawAlignment(MarketPage1[4], 1);
	TextDrawColor(MarketPage1[4], -377187329);
	TextDrawSetShadow(MarketPage1[4], 0);
	TextDrawSetOutline(MarketPage1[4], 0);
	TextDrawBackgroundColor(MarketPage1[4], 255);
	TextDrawFont(MarketPage1[4], 4);
	TextDrawSetProportional(MarketPage1[4], 1);

	MarketPage1[5] = TextDrawCreate(187.000, 234.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[5], 41.000, 16.000);
	TextDrawAlignment(MarketPage1[5], 1);
	TextDrawColor(MarketPage1[5], -849584897);
	TextDrawSetShadow(MarketPage1[5], 0);
	TextDrawSetOutline(MarketPage1[5], 0);
	TextDrawBackgroundColor(MarketPage1[5], 255);
	TextDrawFont(MarketPage1[5], 4);
	TextDrawSetProportional(MarketPage1[5], 1);
	TextDrawSetSelectable(MarketPage1[5], 1);

	MarketPage1[6] = TextDrawCreate(247.000, 269.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[6], 46.000, 59.000);
	TextDrawAlignment(MarketPage1[6], 1);
	TextDrawColor(MarketPage1[6], 131684);
	TextDrawSetShadow(MarketPage1[6], 0);
	TextDrawSetOutline(MarketPage1[6], 0);
	TextDrawBackgroundColor(MarketPage1[6], 255);
	TextDrawFont(MarketPage1[6], 4);
	TextDrawSetProportional(MarketPage1[6], 1);

	MarketPage1[7] = TextDrawCreate(299.000, 269.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[7], 46.000, 59.000);
	TextDrawAlignment(MarketPage1[7], 1);
	TextDrawColor(MarketPage1[7], 131684);
	TextDrawSetShadow(MarketPage1[7], 0);
	TextDrawSetOutline(MarketPage1[7], 0);
	TextDrawBackgroundColor(MarketPage1[7], 255);
	TextDrawFont(MarketPage1[7], 4);
	TextDrawSetProportional(MarketPage1[7], 1);

	MarketPage1[8] = TextDrawCreate(247.000, 178.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[8], 46.000, 59.000);
	TextDrawAlignment(MarketPage1[8], 1);
	TextDrawColor(MarketPage1[8], 131684);
	TextDrawSetShadow(MarketPage1[8], 0);
	TextDrawSetOutline(MarketPage1[8], 0);
	TextDrawBackgroundColor(MarketPage1[8], 255);
	TextDrawFont(MarketPage1[8], 4);
	TextDrawSetProportional(MarketPage1[8], 1);

	MarketPage1[9] = TextDrawCreate(299.000, 178.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[9], 46.000, 59.000);
	TextDrawAlignment(MarketPage1[9], 1);
	TextDrawColor(MarketPage1[9], 131684);
	TextDrawSetShadow(MarketPage1[9], 0);
	TextDrawSetOutline(MarketPage1[9], 0);
	TextDrawBackgroundColor(MarketPage1[9], 255);
	TextDrawFont(MarketPage1[9], 4);
	TextDrawSetProportional(MarketPage1[9], 1);

	MarketPage1[10] = TextDrawCreate(351.000, 178.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[10], 46.000, 59.000);
	TextDrawAlignment(MarketPage1[10], 1);
	TextDrawColor(MarketPage1[10], 131684);
	TextDrawSetShadow(MarketPage1[10], 0);
	TextDrawSetOutline(MarketPage1[10], 0);
	TextDrawBackgroundColor(MarketPage1[10], 255);
	TextDrawFont(MarketPage1[10], 4);
	TextDrawSetProportional(MarketPage1[10], 1);

	MarketPage1[11] = TextDrawCreate(403.000, 178.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[11], 46.000, 59.000);
	TextDrawAlignment(MarketPage1[11], 1);
	TextDrawColor(MarketPage1[11], 131684);
	TextDrawSetShadow(MarketPage1[11], 0);
	TextDrawSetOutline(MarketPage1[11], 0);
	TextDrawBackgroundColor(MarketPage1[11], 255);
	TextDrawFont(MarketPage1[11], 4);
	TextDrawSetProportional(MarketPage1[11], 1);

	MarketPage1[12] = TextDrawCreate(351.000, 268.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[12], 46.000, 59.000);
	TextDrawAlignment(MarketPage1[12], 1);
	TextDrawColor(MarketPage1[12], 131684);
	TextDrawSetShadow(MarketPage1[12], 0);
	TextDrawSetOutline(MarketPage1[12], 0);
	TextDrawBackgroundColor(MarketPage1[12], 255);
	TextDrawFont(MarketPage1[12], 4);
	TextDrawSetProportional(MarketPage1[12], 1);

	MarketPage1[13] = TextDrawCreate(403.000, 268.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[13], 46.000, 59.000);
	TextDrawAlignment(MarketPage1[13], 1);
	TextDrawColor(MarketPage1[13], 131684);
	TextDrawSetShadow(MarketPage1[13], 0);
	TextDrawSetOutline(MarketPage1[13], 0);
	TextDrawBackgroundColor(MarketPage1[13], 255);
	TextDrawFont(MarketPage1[13], 4);
	TextDrawSetProportional(MarketPage1[13], 1);

	MarketPage1[14] = TextDrawCreate(247.000, 240.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[14], 46.000, 20.000);
	TextDrawAlignment(MarketPage1[14], 1);
	TextDrawColor(MarketPage1[14], -377187329);
	TextDrawSetShadow(MarketPage1[14], 0);
	TextDrawSetOutline(MarketPage1[14], 0);
	TextDrawBackgroundColor(MarketPage1[14], 255);
	TextDrawFont(MarketPage1[14], 4);
	TextDrawSetProportional(MarketPage1[14], 1);
	TextDrawSetSelectable(MarketPage1[14], 1);

	MarketPage1[15] = TextDrawCreate(299.000, 240.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[15], 46.000, 20.000);
	TextDrawAlignment(MarketPage1[15], 1);
	TextDrawColor(MarketPage1[15], -377187329);
	TextDrawSetShadow(MarketPage1[15], 0);
	TextDrawSetOutline(MarketPage1[15], 0);
	TextDrawBackgroundColor(MarketPage1[15], 255);
	TextDrawFont(MarketPage1[15], 4);
	TextDrawSetProportional(MarketPage1[15], 1);
	TextDrawSetSelectable(MarketPage1[15], 1);

	MarketPage1[16] = TextDrawCreate(351.000, 241.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[16], 46.000, 20.000);
	TextDrawAlignment(MarketPage1[16], 1);
	TextDrawColor(MarketPage1[16], -377187329);
	TextDrawSetShadow(MarketPage1[16], 0);
	TextDrawSetOutline(MarketPage1[16], 0);
	TextDrawBackgroundColor(MarketPage1[16], 255);
	TextDrawFont(MarketPage1[16], 4);
	TextDrawSetProportional(MarketPage1[16], 1);
	TextDrawSetSelectable(MarketPage1[16], 1);

	MarketPage1[17] = TextDrawCreate(403.000, 241.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[17], 46.000, 20.000);
	TextDrawAlignment(MarketPage1[17], 1);
	TextDrawColor(MarketPage1[17], -377187329);
	TextDrawSetShadow(MarketPage1[17], 0);
	TextDrawSetOutline(MarketPage1[17], 0);
	TextDrawBackgroundColor(MarketPage1[17], 255);
	TextDrawFont(MarketPage1[17], 4);
	TextDrawSetProportional(MarketPage1[17], 1);
	TextDrawSetSelectable(MarketPage1[17], 1);

	MarketPage1[18] = TextDrawCreate(247.000, 331.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[18], 46.000, 20.000);
	TextDrawAlignment(MarketPage1[18], 1);
	TextDrawColor(MarketPage1[18], -377187329);
	TextDrawSetShadow(MarketPage1[18], 0);
	TextDrawSetOutline(MarketPage1[18], 0);
	TextDrawBackgroundColor(MarketPage1[18], 255);
	TextDrawFont(MarketPage1[18], 4);
	TextDrawSetProportional(MarketPage1[18], 1);
	TextDrawSetSelectable(MarketPage1[18], 1);

	MarketPage1[19] = TextDrawCreate(299.000, 331.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[19], 46.000, 20.000);
	TextDrawAlignment(MarketPage1[19], 1);
	TextDrawColor(MarketPage1[19], -377187329);
	TextDrawSetShadow(MarketPage1[19], 0);
	TextDrawSetOutline(MarketPage1[19], 0);
	TextDrawBackgroundColor(MarketPage1[19], 255);
	TextDrawFont(MarketPage1[19], 4);
	TextDrawSetProportional(MarketPage1[19], 1);
	TextDrawSetSelectable(MarketPage1[19], 1);

	MarketPage1[20] = TextDrawCreate(351.000, 331.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[20], 46.000, 20.000);
	TextDrawAlignment(MarketPage1[20], 1);
	TextDrawColor(MarketPage1[20], -377187329);
	TextDrawSetShadow(MarketPage1[20], 0);
	TextDrawSetOutline(MarketPage1[20], 0);
	TextDrawBackgroundColor(MarketPage1[20], 255);
	TextDrawFont(MarketPage1[20], 4);
	TextDrawSetProportional(MarketPage1[20], 1);
	TextDrawSetSelectable(MarketPage1[20], 1);

	MarketPage1[21] = TextDrawCreate(403.000, 331.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[21], 46.000, 20.000);
	TextDrawAlignment(MarketPage1[21], 1);
	TextDrawColor(MarketPage1[21], -377187329);
	TextDrawSetShadow(MarketPage1[21], 0);
	TextDrawSetOutline(MarketPage1[21], 0);
	TextDrawBackgroundColor(MarketPage1[21], 255);
	TextDrawFont(MarketPage1[21], 4);
	TextDrawSetProportional(MarketPage1[21], 1);
	TextDrawSetSelectable(MarketPage1[21], 1);

	MarketPage1[22] = TextDrawCreate(261.000, 165.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[22], 173.000, -4.000);
	TextDrawAlignment(MarketPage1[22], 1);
	TextDrawColor(MarketPage1[22], -1);
	TextDrawSetShadow(MarketPage1[22], 0);
	TextDrawSetOutline(MarketPage1[22], 0);
	TextDrawBackgroundColor(MarketPage1[22], 255);
	TextDrawFont(MarketPage1[22], 4);
	TextDrawSetProportional(MarketPage1[22], 1);

	MarketPage1[23] = TextDrawCreate(435.000, 153.000, "LD_BEAT:right");
	TextDrawTextSize(MarketPage1[23], 14.000, 20.000);
	TextDrawAlignment(MarketPage1[23], 1);
	TextDrawColor(MarketPage1[23], -1);
	TextDrawSetShadow(MarketPage1[23], 0);
	TextDrawSetOutline(MarketPage1[23], 0);
	TextDrawBackgroundColor(MarketPage1[23], 255);
	TextDrawFont(MarketPage1[23], 4);
	TextDrawSetProportional(MarketPage1[23], 1);
	TextDrawSetSelectable(MarketPage1[23], 1);

	MarketPage1[24] = TextDrawCreate(246.000, 154.000, "LD_BEAT:left");
	TextDrawTextSize(MarketPage1[24], 14.000, 20.000);
	TextDrawAlignment(MarketPage1[24], 1);
	TextDrawColor(MarketPage1[24], -1);
	TextDrawSetShadow(MarketPage1[24], 0);
	TextDrawSetOutline(MarketPage1[24], 0);
	TextDrawBackgroundColor(MarketPage1[24], 255);
	TextDrawFont(MarketPage1[24], 4);
	TextDrawSetProportional(MarketPage1[24], 1);
	TextDrawSetSelectable(MarketPage1[24], 1);

	MarketPage1[25] = TextDrawCreate(188.000, 143.000, "MARKET 24/7");
	TextDrawLetterSize(MarketPage1[25], 0.238, 1.600);
	TextDrawAlignment(MarketPage1[25], 1);
	TextDrawColor(MarketPage1[25], -602653441);
	TextDrawSetShadow(MarketPage1[25], 0);
	TextDrawSetOutline(MarketPage1[25], 0);
	TextDrawBackgroundColor(MarketPage1[25], 150);
	TextDrawFont(MarketPage1[25], 1);
	TextDrawSetProportional(MarketPage1[25], 1);

	MarketPage1[26] = TextDrawCreate(189.000, 159.000, "Vyn_Ytp");
	TextDrawLetterSize(MarketPage1[26], 0.188, 1.600);
	TextDrawAlignment(MarketPage1[26], 1);
	TextDrawColor(MarketPage1[26], -106);
	TextDrawSetShadow(MarketPage1[26], 0);
	TextDrawSetOutline(MarketPage1[26], 0);
	TextDrawBackgroundColor(MarketPage1[26], 150);
	TextDrawFont(MarketPage1[26], 1);
	TextDrawSetProportional(MarketPage1[26], 1);

	MarketPage1[27] = TextDrawCreate(182.000, 181.000, "Selamat datang");
	TextDrawLetterSize(MarketPage1[27], 0.188, 1.600);
	TextDrawAlignment(MarketPage1[27], 1);
	TextDrawColor(MarketPage1[27], -106);
	TextDrawSetShadow(MarketPage1[27], 0);
	TextDrawSetOutline(MarketPage1[27], 0);
	TextDrawBackgroundColor(MarketPage1[27], 150);
	TextDrawFont(MarketPage1[27], 1);
	TextDrawSetProportional(MarketPage1[27], 1);

	MarketPage1[28] = TextDrawCreate(178.000, 194.000, "selamat berbelanja");
	TextDrawLetterSize(MarketPage1[28], 0.188, 1.600);
	TextDrawAlignment(MarketPage1[28], 1);
	TextDrawColor(MarketPage1[28], -106);
	TextDrawSetShadow(MarketPage1[28], 0);
	TextDrawSetOutline(MarketPage1[28], 0);
	TextDrawBackgroundColor(MarketPage1[28], 150);
	TextDrawFont(MarketPage1[28], 1);
	TextDrawSetProportional(MarketPage1[28], 1);

	MarketPage1[29] = TextDrawCreate(200.000, 233.000, "Tutup");
	TextDrawLetterSize(MarketPage1[29], 0.187, 1.600);
	TextDrawAlignment(MarketPage1[29], 1);
	TextDrawColor(MarketPage1[29], -106);
	TextDrawSetShadow(MarketPage1[29], 0);
	TextDrawSetOutline(MarketPage1[29], 0);
	TextDrawBackgroundColor(MarketPage1[29], 150);
	TextDrawFont(MarketPage1[29], 1);
	TextDrawSetProportional(MarketPage1[29], 1);

	MarketPage1[30] = TextDrawCreate(369.000, 243.000, "Beli");
	TextDrawLetterSize(MarketPage1[30], 0.187, 1.600);
	TextDrawAlignment(MarketPage1[30], 1);
	TextDrawColor(MarketPage1[30], -106);
	TextDrawSetShadow(MarketPage1[30], 0);
	TextDrawSetOutline(MarketPage1[30], 0);
	TextDrawBackgroundColor(MarketPage1[30], 150);
	TextDrawFont(MarketPage1[30], 1);
	TextDrawSetProportional(MarketPage1[30], 1);

	MarketPage1[31] = TextDrawCreate(420.000, 243.000, "Beli");
	TextDrawLetterSize(MarketPage1[31], 0.187, 1.600);
	TextDrawAlignment(MarketPage1[31], 1);
	TextDrawColor(MarketPage1[31], -106);
	TextDrawSetShadow(MarketPage1[31], 0);
	TextDrawSetOutline(MarketPage1[31], 0);
	TextDrawBackgroundColor(MarketPage1[31], 150);
	TextDrawFont(MarketPage1[31], 1);
	TextDrawSetProportional(MarketPage1[31], 1);

	MarketPage1[32] = TextDrawCreate(265.000, 242.000, "Beli");
	TextDrawLetterSize(MarketPage1[32], 0.187, 1.600);
	TextDrawAlignment(MarketPage1[32], 1);
	TextDrawColor(MarketPage1[32], -106);
	TextDrawSetShadow(MarketPage1[32], 0);
	TextDrawSetOutline(MarketPage1[32], 0);
	TextDrawBackgroundColor(MarketPage1[32], 150);
	TextDrawFont(MarketPage1[32], 1);
	TextDrawSetProportional(MarketPage1[32], 1);

	MarketPage1[33] = TextDrawCreate(316.000, 242.000, "Beli");
	TextDrawLetterSize(MarketPage1[33], 0.187, 1.600);
	TextDrawAlignment(MarketPage1[33], 1);
	TextDrawColor(MarketPage1[33], -106);
	TextDrawSetShadow(MarketPage1[33], 0);
	TextDrawSetOutline(MarketPage1[33], 0);
	TextDrawBackgroundColor(MarketPage1[33], 150);
	TextDrawFont(MarketPage1[33], 1);
	TextDrawSetProportional(MarketPage1[33], 1);

	MarketPage1[34] = TextDrawCreate(266.000, 332.000, "Beli");
	TextDrawLetterSize(MarketPage1[34], 0.187, 1.600);
	TextDrawAlignment(MarketPage1[34], 1);
	TextDrawColor(MarketPage1[34], -106);
	TextDrawSetShadow(MarketPage1[34], 0);
	TextDrawSetOutline(MarketPage1[34], 0);
	TextDrawBackgroundColor(MarketPage1[34], 150);
	TextDrawFont(MarketPage1[34], 1);
	TextDrawSetProportional(MarketPage1[34], 1);

	MarketPage1[35] = TextDrawCreate(317.000, 332.000, "Beli");
	TextDrawLetterSize(MarketPage1[35], 0.187, 1.600);
	TextDrawAlignment(MarketPage1[35], 1);
	TextDrawColor(MarketPage1[35], -106);
	TextDrawSetShadow(MarketPage1[35], 0);
	TextDrawSetOutline(MarketPage1[35], 0);
	TextDrawBackgroundColor(MarketPage1[35], 150);
	TextDrawFont(MarketPage1[35], 1);
	TextDrawSetProportional(MarketPage1[35], 1);

	MarketPage1[36] = TextDrawCreate(369.000, 333.000, "Beli");
	TextDrawLetterSize(MarketPage1[36], 0.187, 1.600);
	TextDrawAlignment(MarketPage1[36], 1);
	TextDrawColor(MarketPage1[36], -106);
	TextDrawSetShadow(MarketPage1[36], 0);
	TextDrawSetOutline(MarketPage1[36], 0);
	TextDrawBackgroundColor(MarketPage1[36], 150);
	TextDrawFont(MarketPage1[36], 1);
	TextDrawSetProportional(MarketPage1[36], 1);

	MarketPage1[37] = TextDrawCreate(420.000, 333.000, "Beli");
	TextDrawLetterSize(MarketPage1[37], 0.187, 1.600);
	TextDrawAlignment(MarketPage1[37], 1);
	TextDrawColor(MarketPage1[37], -106);
	TextDrawSetShadow(MarketPage1[37], 0);
	TextDrawSetOutline(MarketPage1[37], 0);
	TextDrawBackgroundColor(MarketPage1[37], 150);
	TextDrawFont(MarketPage1[37], 1);
	TextDrawSetProportional(MarketPage1[37], 1);

	MarketPage1[38] = TextDrawCreate(224.000, 162.000, "_");
	TextDrawTextSize(MarketPage1[38], 90.000, 90.000);
	TextDrawAlignment(MarketPage1[38], 1);
	TextDrawColor(MarketPage1[38], -1);
	TextDrawSetShadow(MarketPage1[38], 0);
	TextDrawSetOutline(MarketPage1[38], 0);
	TextDrawBackgroundColor(MarketPage1[38], 131584);
	TextDrawFont(MarketPage1[38], 5);
	TextDrawSetProportional(MarketPage1[38], 0);
	TextDrawSetPreviewModel(MarketPage1[38], 2769);
	TextDrawSetPreviewRot(MarketPage1[38], 95.000, 2.000, -110.000, 1.799);
	TextDrawSetPreviewVehCol(MarketPage1[38], 0, 0);

	MarketPage1[39] = TextDrawCreate(275.000, 163.000, "_");
	TextDrawTextSize(MarketPage1[39], 90.000, 90.000);
	TextDrawAlignment(MarketPage1[39], 1);
	TextDrawColor(MarketPage1[39], -1);
	TextDrawSetShadow(MarketPage1[39], 0);
	TextDrawSetOutline(MarketPage1[39], 0);
	TextDrawBackgroundColor(MarketPage1[39], 0);
	TextDrawFont(MarketPage1[39], 5);
	TextDrawSetProportional(MarketPage1[39], 0);
	TextDrawSetPreviewModel(MarketPage1[39], 19570);
	TextDrawSetPreviewRot(MarketPage1[39], 0.000, 0.000, 0.000, 1.700);
	TextDrawSetPreviewVehCol(MarketPage1[39], 0, 0);

	MarketPage1[40] = TextDrawCreate(328.000, 164.000, "_");
	TextDrawTextSize(MarketPage1[40], 90.000, 90.000);
	TextDrawAlignment(MarketPage1[40], 1);
	TextDrawColor(MarketPage1[40], -1);
	TextDrawSetShadow(MarketPage1[40], 0);
	TextDrawSetOutline(MarketPage1[40], 0);
	TextDrawBackgroundColor(MarketPage1[40], 0);
	TextDrawFont(MarketPage1[40], 5);
	TextDrawSetProportional(MarketPage1[40], 0);
	TextDrawSetPreviewModel(MarketPage1[40], 19878);
	TextDrawSetPreviewRot(MarketPage1[40], -88.000, 0.000, 90.000, 1.700);
	TextDrawSetPreviewVehCol(MarketPage1[40], 0, 0);

	MarketPage1[41] = TextDrawCreate(380.000, 162.000, "_");
	TextDrawTextSize(MarketPage1[41], 90.000, 90.000);
	TextDrawAlignment(MarketPage1[41], 1);
	TextDrawColor(MarketPage1[41], -1);
	TextDrawSetShadow(MarketPage1[41], 0);
	TextDrawSetOutline(MarketPage1[41], 0);
	TextDrawBackgroundColor(MarketPage1[41], 0);
	TextDrawFont(MarketPage1[41], 5);
	TextDrawSetProportional(MarketPage1[41], 0);
	TextDrawSetPreviewModel(MarketPage1[41], 19896);
	TextDrawSetPreviewRot(MarketPage1[41], -88.000, 0.000, 180.000, 1.299);
	TextDrawSetPreviewVehCol(MarketPage1[41], 0, 0);

	MarketPage1[42] = TextDrawCreate(220.000, 267.000, "_");
	TextDrawTextSize(MarketPage1[42], 90.000, 90.000);
	TextDrawAlignment(MarketPage1[42], 1);
	TextDrawColor(MarketPage1[42], -1);
	TextDrawSetShadow(MarketPage1[42], 0);
	TextDrawSetOutline(MarketPage1[42], 0);
	TextDrawBackgroundColor(MarketPage1[42], 0);
	TextDrawFont(MarketPage1[42], 5);
	TextDrawSetProportional(MarketPage1[42], 0);
	TextDrawSetPreviewModel(MarketPage1[42], 336);
	TextDrawSetPreviewRot(MarketPage1[42], -5.000, 0.000, 170.000, 2.598);
	TextDrawSetPreviewVehCol(MarketPage1[42], 0, 0);

	MarketPage1[43] = TextDrawCreate(272.000, 259.000, "_");
	TextDrawTextSize(MarketPage1[43], 90.000, 90.000);
	TextDrawAlignment(MarketPage1[43], 1);
	TextDrawColor(MarketPage1[43], -1);
	TextDrawSetShadow(MarketPage1[43], 0);
	TextDrawSetOutline(MarketPage1[43], 0);
	TextDrawBackgroundColor(MarketPage1[43], 0);
	TextDrawFont(MarketPage1[43], 5);
	TextDrawSetProportional(MarketPage1[43], 0);
	TextDrawSetPreviewModel(MarketPage1[43], 335);
	TextDrawSetPreviewRot(MarketPage1[43], -5.000, 0.000, 170.000, 2.598);
	TextDrawSetPreviewVehCol(MarketPage1[43], 0, 0);

	MarketPage1[44] = TextDrawCreate(326.000, 270.000, "_");
	TextDrawTextSize(MarketPage1[44], 90.000, 90.000);
	TextDrawAlignment(MarketPage1[44], 1);
	TextDrawColor(MarketPage1[44], -1);
	TextDrawSetShadow(MarketPage1[44], 0);
	TextDrawSetOutline(MarketPage1[44], 0);
	TextDrawBackgroundColor(MarketPage1[44], 0);
	TextDrawFont(MarketPage1[44], 5);
	TextDrawSetProportional(MarketPage1[44], 0);
	TextDrawSetPreviewModel(MarketPage1[44], 333);
	TextDrawSetPreviewRot(MarketPage1[44], -5.000, 0.000, 214.000, 3.197);
	TextDrawSetPreviewVehCol(MarketPage1[44], 0, 0);

	MarketPage1[45] = TextDrawCreate(378.000, 268.000, "_");
	TextDrawTextSize(MarketPage1[45], 90.000, 90.000);
	TextDrawAlignment(MarketPage1[45], 1);
	TextDrawColor(MarketPage1[45], -1);
	TextDrawSetShadow(MarketPage1[45], 0);
	TextDrawSetOutline(MarketPage1[45], 0);
	TextDrawBackgroundColor(MarketPage1[45], 0);
	TextDrawFont(MarketPage1[45], 5);
	TextDrawSetProportional(MarketPage1[45], 0);
	TextDrawSetPreviewModel(MarketPage1[45], 338);
	TextDrawSetPreviewRot(MarketPage1[45], -5.000, 0.000, 214.000, 4.197);
	TextDrawSetPreviewVehCol(MarketPage1[45], 0, 0);

	MarketPage1[46] = TextDrawCreate(248.000, 178.000, "$650");
	TextDrawLetterSize(MarketPage1[46], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[46], 1);
	TextDrawColor(MarketPage1[46], 852308735);
	TextDrawSetShadow(MarketPage1[46], 0);
	TextDrawSetOutline(MarketPage1[46], 0);
	TextDrawBackgroundColor(MarketPage1[46], 150);
	TextDrawFont(MarketPage1[46], 1);
	TextDrawSetProportional(MarketPage1[46], 1);

	MarketPage1[47] = TextDrawCreate(300.000, 178.000, "$650");
	TextDrawLetterSize(MarketPage1[47], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[47], 1);
	TextDrawColor(MarketPage1[47], 852308735);
	TextDrawSetShadow(MarketPage1[47], 0);
	TextDrawSetOutline(MarketPage1[47], 0);
	TextDrawBackgroundColor(MarketPage1[47], 150);
	TextDrawFont(MarketPage1[47], 1);
	TextDrawSetProportional(MarketPage1[47], 1);

	MarketPage1[48] = TextDrawCreate(352.000, 178.000, "$870");
	TextDrawLetterSize(MarketPage1[48], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[48], 1);
	TextDrawColor(MarketPage1[48], 852308735);
	TextDrawSetShadow(MarketPage1[48], 0);
	TextDrawSetOutline(MarketPage1[48], 0);
	TextDrawBackgroundColor(MarketPage1[48], 150);
	TextDrawFont(MarketPage1[48], 1);
	TextDrawSetProportional(MarketPage1[48], 1);

	MarketPage1[49] = TextDrawCreate(404.000, 178.000, "$310");
	TextDrawLetterSize(MarketPage1[49], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[49], 1);
	TextDrawColor(MarketPage1[49], 852308735);
	TextDrawSetShadow(MarketPage1[49], 0);
	TextDrawSetOutline(MarketPage1[49], 0);
	TextDrawBackgroundColor(MarketPage1[49], 150);
	TextDrawFont(MarketPage1[49], 1);
	TextDrawSetProportional(MarketPage1[49], 1);

	MarketPage1[50] = TextDrawCreate(248.000, 228.000, "Nasi uduk");
	TextDrawLetterSize(MarketPage1[50], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[50], 1);
	TextDrawColor(MarketPage1[50], -1);
	TextDrawSetShadow(MarketPage1[50], 0);
	TextDrawSetOutline(MarketPage1[50], 0);
	TextDrawBackgroundColor(MarketPage1[50], 150);
	TextDrawFont(MarketPage1[50], 1);
	TextDrawSetProportional(MarketPage1[50], 1);

	MarketPage1[51] = TextDrawCreate(300.000, 228.000, "Air mineral");
	TextDrawLetterSize(MarketPage1[51], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[51], 1);
	TextDrawColor(MarketPage1[51], -1);
	TextDrawSetShadow(MarketPage1[51], 0);
	TextDrawSetOutline(MarketPage1[51], 0);
	TextDrawBackgroundColor(MarketPage1[51], 150);
	TextDrawFont(MarketPage1[51], 1);
	TextDrawSetProportional(MarketPage1[51], 1);

	MarketPage1[52] = TextDrawCreate(352.000, 228.000, "Skateboard");
	TextDrawLetterSize(MarketPage1[52], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[52], 1);
	TextDrawColor(MarketPage1[52], -1);
	TextDrawSetShadow(MarketPage1[52], 0);
	TextDrawSetOutline(MarketPage1[52], 0);
	TextDrawBackgroundColor(MarketPage1[52], 150);
	TextDrawFont(MarketPage1[52], 1);
	TextDrawSetProportional(MarketPage1[52], 1);

	MarketPage1[53] = TextDrawCreate(404.000, 228.000, "Udud");
	TextDrawLetterSize(MarketPage1[53], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[53], 1);
	TextDrawColor(MarketPage1[53], -1);
	TextDrawSetShadow(MarketPage1[53], 0);
	TextDrawSetOutline(MarketPage1[53], 0);
	TextDrawBackgroundColor(MarketPage1[53], 150);
	TextDrawFont(MarketPage1[53], 1);
	TextDrawSetProportional(MarketPage1[53], 1);

	MarketPage1[54] = TextDrawCreate(248.000, 268.000, "$950");
	TextDrawLetterSize(MarketPage1[54], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[54], 1);
	TextDrawColor(MarketPage1[54], 852308735);
	TextDrawSetShadow(MarketPage1[54], 0);
	TextDrawSetOutline(MarketPage1[54], 0);
	TextDrawBackgroundColor(MarketPage1[54], 150);
	TextDrawFont(MarketPage1[54], 1);
	TextDrawSetProportional(MarketPage1[54], 1);

	MarketPage1[55] = TextDrawCreate(300.000, 268.000, "$950");
	TextDrawLetterSize(MarketPage1[55], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[55], 1);
	TextDrawColor(MarketPage1[55], 852308735);
	TextDrawSetShadow(MarketPage1[55], 0);
	TextDrawSetOutline(MarketPage1[55], 0);
	TextDrawBackgroundColor(MarketPage1[55], 150);
	TextDrawFont(MarketPage1[55], 1);
	TextDrawSetProportional(MarketPage1[55], 1);

	MarketPage1[56] = TextDrawCreate(352.000, 268.000, "$950");
	TextDrawLetterSize(MarketPage1[56], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[56], 1);
	TextDrawColor(MarketPage1[56], 852308735);
	TextDrawSetShadow(MarketPage1[56], 0);
	TextDrawSetOutline(MarketPage1[56], 0);
	TextDrawBackgroundColor(MarketPage1[56], 150);
	TextDrawFont(MarketPage1[56], 1);
	TextDrawSetProportional(MarketPage1[56], 1);

	MarketPage1[57] = TextDrawCreate(404.000, 268.000, "$950");
	TextDrawLetterSize(MarketPage1[57], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[57], 1);
	TextDrawColor(MarketPage1[57], 852308735);
	TextDrawSetShadow(MarketPage1[57], 0);
	TextDrawSetOutline(MarketPage1[57], 0);
	TextDrawBackgroundColor(MarketPage1[57], 150);
	TextDrawFont(MarketPage1[57], 1);
	TextDrawSetProportional(MarketPage1[57], 1);

	MarketPage1[58] = TextDrawCreate(248.000, 318.000, "Baseball");
	TextDrawLetterSize(MarketPage1[58], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[58], 1);
	TextDrawColor(MarketPage1[58], -1);
	TextDrawSetShadow(MarketPage1[58], 0);
	TextDrawSetOutline(MarketPage1[58], 0);
	TextDrawBackgroundColor(MarketPage1[58], 150);
	TextDrawFont(MarketPage1[58], 1);
	TextDrawSetProportional(MarketPage1[58], 1);

	MarketPage1[59] = TextDrawCreate(300.000, 318.000, "Pisau");
	TextDrawLetterSize(MarketPage1[59], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[59], 1);
	TextDrawColor(MarketPage1[59], -1);
	TextDrawSetShadow(MarketPage1[59], 0);
	TextDrawSetOutline(MarketPage1[59], 0);
	TextDrawBackgroundColor(MarketPage1[59], 150);
	TextDrawFont(MarketPage1[59], 1);
	TextDrawSetProportional(MarketPage1[59], 1);

	MarketPage1[60] = TextDrawCreate(352.000, 318.000, "Golf Stick");
	TextDrawLetterSize(MarketPage1[60], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[60], 1);
	TextDrawColor(MarketPage1[60], -1);
	TextDrawSetShadow(MarketPage1[60], 0);
	TextDrawSetOutline(MarketPage1[60], 0);
	TextDrawBackgroundColor(MarketPage1[60], 150);
	TextDrawFont(MarketPage1[60], 1);
	TextDrawSetProportional(MarketPage1[60], 1);

	MarketPage1[61] = TextDrawCreate(404.000, 318.000, "Pool Cue");
	TextDrawLetterSize(MarketPage1[61], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[61], 1);
	TextDrawColor(MarketPage1[61], -1);
	TextDrawSetShadow(MarketPage1[61], 0);
	TextDrawSetOutline(MarketPage1[61], 0);
	TextDrawBackgroundColor(MarketPage1[61], 150);
	TextDrawFont(MarketPage1[61], 1);
	TextDrawSetProportional(MarketPage1[61], 1);

	MarketPage1[62] = TextDrawCreate(287.000, 178.000, "x1");
	TextDrawLetterSize(MarketPage1[62], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[62], 1);
	TextDrawColor(MarketPage1[62], -1);
	TextDrawSetShadow(MarketPage1[62], 0);
	TextDrawSetOutline(MarketPage1[62], 0);
	TextDrawBackgroundColor(MarketPage1[62], 150);
	TextDrawFont(MarketPage1[62], 1);
	TextDrawSetProportional(MarketPage1[62], 1);

	MarketPage1[63] = TextDrawCreate(339.000, 178.000, "x1");
	TextDrawLetterSize(MarketPage1[63], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[63], 1);
	TextDrawColor(MarketPage1[63], -1);
	TextDrawSetShadow(MarketPage1[63], 0);
	TextDrawSetOutline(MarketPage1[63], 0);
	TextDrawBackgroundColor(MarketPage1[63], 150);
	TextDrawFont(MarketPage1[63], 1);
	TextDrawSetProportional(MarketPage1[63], 1);

	MarketPage1[64] = TextDrawCreate(391.000, 178.000, "x1");
	TextDrawLetterSize(MarketPage1[64], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[64], 1);
	TextDrawColor(MarketPage1[64], -1);
	TextDrawSetShadow(MarketPage1[64], 0);
	TextDrawSetOutline(MarketPage1[64], 0);
	TextDrawBackgroundColor(MarketPage1[64], 150);
	TextDrawFont(MarketPage1[64], 1);
	TextDrawSetProportional(MarketPage1[64], 1);

	MarketPage1[65] = TextDrawCreate(443.000, 178.000, "x1");
	TextDrawLetterSize(MarketPage1[65], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[65], 1);
	TextDrawColor(MarketPage1[65], -1);
	TextDrawSetShadow(MarketPage1[65], 0);
	TextDrawSetOutline(MarketPage1[65], 0);
	TextDrawBackgroundColor(MarketPage1[65], 150);
	TextDrawFont(MarketPage1[65], 1);
	TextDrawSetProportional(MarketPage1[65], 1);

	MarketPage1[66] = TextDrawCreate(287.000, 269.000, "x1");
	TextDrawLetterSize(MarketPage1[66], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[66], 1);
	TextDrawColor(MarketPage1[66], -1);
	TextDrawSetShadow(MarketPage1[66], 0);
	TextDrawSetOutline(MarketPage1[66], 0);
	TextDrawBackgroundColor(MarketPage1[66], 150);
	TextDrawFont(MarketPage1[66], 1);
	TextDrawSetProportional(MarketPage1[66], 1);

	MarketPage1[67] = TextDrawCreate(339.000, 269.000, "x1");
	TextDrawLetterSize(MarketPage1[67], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[67], 1);
	TextDrawColor(MarketPage1[67], -1);
	TextDrawSetShadow(MarketPage1[67], 0);
	TextDrawSetOutline(MarketPage1[67], 0);
	TextDrawBackgroundColor(MarketPage1[67], 150);
	TextDrawFont(MarketPage1[67], 1);
	TextDrawSetProportional(MarketPage1[67], 1);

	MarketPage1[68] = TextDrawCreate(391.000, 269.000, "x1");
	TextDrawLetterSize(MarketPage1[68], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[68], 1);
	TextDrawColor(MarketPage1[68], -1);
	TextDrawSetShadow(MarketPage1[68], 0);
	TextDrawSetOutline(MarketPage1[68], 0);
	TextDrawBackgroundColor(MarketPage1[68], 150);
	TextDrawFont(MarketPage1[68], 1);
	TextDrawSetProportional(MarketPage1[68], 1);

	MarketPage1[69] = TextDrawCreate(443.000, 269.000, "x1");
	TextDrawLetterSize(MarketPage1[69], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[69], 1);
	TextDrawColor(MarketPage1[69], -1);
	TextDrawSetShadow(MarketPage1[69], 0);
	TextDrawSetOutline(MarketPage1[69], 0);
	TextDrawBackgroundColor(MarketPage1[69], 150);
	TextDrawFont(MarketPage1[69], 1);
	TextDrawSetProportional(MarketPage1[69], 1);

	MarketPage1[70] = TextDrawCreate(195.000, 269.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[70], 46.000, 59.000);
	TextDrawAlignment(MarketPage1[70], 1);
	TextDrawColor(MarketPage1[70], 131684);
	TextDrawSetShadow(MarketPage1[70], 0);
	TextDrawSetOutline(MarketPage1[70], 0);
	TextDrawBackgroundColor(MarketPage1[70], 255);
	TextDrawFont(MarketPage1[70], 4);
	TextDrawSetProportional(MarketPage1[70], 1);

	MarketPage1[71] = TextDrawCreate(195.000, 331.000, "LD_SPAC:white");
	TextDrawTextSize(MarketPage1[71], 46.000, 20.000);
	TextDrawAlignment(MarketPage1[71], 1);
	TextDrawColor(MarketPage1[71], -377187329);
	TextDrawSetShadow(MarketPage1[71], 0);
	TextDrawSetOutline(MarketPage1[71], 0);
	TextDrawBackgroundColor(MarketPage1[71], 255);
	TextDrawFont(MarketPage1[71], 4);
	TextDrawSetProportional(MarketPage1[71], 1);
	TextDrawSetSelectable(MarketPage1[71], 1);

	MarketPage1[72] = TextDrawCreate(214.000, 332.000, "Beli");
	TextDrawLetterSize(MarketPage1[72], 0.187, 1.600);
	TextDrawAlignment(MarketPage1[72], 1);
	TextDrawColor(MarketPage1[72], -106);
	TextDrawSetShadow(MarketPage1[72], 0);
	TextDrawSetOutline(MarketPage1[72], 0);
	TextDrawBackgroundColor(MarketPage1[72], 150);
	TextDrawFont(MarketPage1[72], 1);
	TextDrawSetProportional(MarketPage1[72], 1);

	MarketPage1[73] = TextDrawCreate(235.000, 269.000, "x1");
	TextDrawLetterSize(MarketPage1[73], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[73], 1);
	TextDrawColor(MarketPage1[73], -1);
	TextDrawSetShadow(MarketPage1[73], 0);
	TextDrawSetOutline(MarketPage1[73], 0);
	TextDrawBackgroundColor(MarketPage1[73], 150);
	TextDrawFont(MarketPage1[73], 1);
	TextDrawSetProportional(MarketPage1[73], 1);

	MarketPage1[74] = TextDrawCreate(195.000, 269.000, "$650");
	TextDrawLetterSize(MarketPage1[74], 0.170, 0.999);
	TextDrawAlignment(MarketPage1[74], 1);
	TextDrawColor(MarketPage1[74], 852308735);
	TextDrawSetShadow(MarketPage1[74], 0);
	TextDrawSetOutline(MarketPage1[74], 0);
	TextDrawBackgroundColor(MarketPage1[74], 150);
	TextDrawFont(MarketPage1[74], 1);
	TextDrawSetProportional(MarketPage1[74], 1);

	MarketPage1[75] = TextDrawCreate(173.000, 253.000, "_");
	TextDrawTextSize(MarketPage1[75], 90.000, 90.000);
	TextDrawAlignment(MarketPage1[75], 1);
	TextDrawColor(MarketPage1[75], -1);
	TextDrawSetShadow(MarketPage1[75], 0);
	TextDrawSetOutline(MarketPage1[75], 0);
	TextDrawBackgroundColor(MarketPage1[75], 66048);
	TextDrawFont(MarketPage1[75], 5);
	TextDrawSetProportional(MarketPage1[75], 0);
	TextDrawSetPreviewModel(MarketPage1[75], 19632);
	TextDrawSetPreviewRot(MarketPage1[75], 0.000, 0.000, 0.000, 1.899);
	TextDrawSetPreviewVehCol(MarketPage1[75], 0, 0);

}

CreateMarket2()
{
        MarketPage2[0] = TextDrawCreate(174.000, 178.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[0], 65.000, 43.000);
        TextDrawAlignment(MarketPage2[0], 1);
        TextDrawColor(MarketPage2[0], -377187329);
        TextDrawSetShadow(MarketPage2[0], 0);
        TextDrawSetOutline(MarketPage2[0], 0);
        TextDrawBackgroundColor(MarketPage2[0], 255);
        TextDrawFont(MarketPage2[0], 4);
        TextDrawSetProportional(MarketPage2[0], 1);

        MarketPage2[1] = TextDrawCreate(176.000, 180.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[1], 61.000, 37.000);
        TextDrawAlignment(MarketPage2[1], 1);
        TextDrawColor(MarketPage2[1], -377187329);
        TextDrawSetShadow(MarketPage2[1], 0);
        TextDrawSetOutline(MarketPage2[1], 0);
        TextDrawBackgroundColor(MarketPage2[1], 255);
        TextDrawFont(MarketPage2[1], 4);
        TextDrawSetProportional(MarketPage2[1], 1);

        MarketPage2[2] = TextDrawCreate(169.000, 156.000, "LD_BEAT:chit");
        TextDrawTextSize(MarketPage2[2], 21.000, 20.000);
        TextDrawAlignment(MarketPage2[2], 1);
        TextDrawColor(MarketPage2[2], -377187329);
        TextDrawSetShadow(MarketPage2[2], 0);
        TextDrawSetOutline(MarketPage2[2], 0);
        TextDrawBackgroundColor(MarketPage2[2], 255);
        TextDrawFont(MarketPage2[2], 4);
        TextDrawSetProportional(MarketPage2[2], 1);

        MarketPage2[3] = TextDrawCreate(172.000, 141.000, "LD_BEAT:chit");
        TextDrawTextSize(MarketPage2[3], 15.000, 18.000);
        TextDrawAlignment(MarketPage2[3], 1);
        TextDrawColor(MarketPage2[3], -377187329);
        TextDrawSetShadow(MarketPage2[3], 0);
        TextDrawSetOutline(MarketPage2[3], 0);
        TextDrawBackgroundColor(MarketPage2[3], 255);
        TextDrawFont(MarketPage2[3], 4);
        TextDrawSetProportional(MarketPage2[3], 1);

        MarketPage2[4] = TextDrawCreate(185.000, 230.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[4], 45.000, 24.000);
        TextDrawAlignment(MarketPage2[4], 1);
        TextDrawColor(MarketPage2[4], -377187329);
        TextDrawSetShadow(MarketPage2[4], 0);
        TextDrawSetOutline(MarketPage2[4], 0);
        TextDrawBackgroundColor(MarketPage2[4], 255);
        TextDrawFont(MarketPage2[4], 4);
        TextDrawSetProportional(MarketPage2[4], 1);

        MarketPage2[5] = TextDrawCreate(187.000, 234.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[5], 41.000, 16.000);
        TextDrawAlignment(MarketPage2[5], 1);
        TextDrawColor(MarketPage2[5], -849584897);
        TextDrawSetShadow(MarketPage2[5], 0);
        TextDrawSetOutline(MarketPage2[5], 0);
        TextDrawBackgroundColor(MarketPage2[5], 255);
        TextDrawFont(MarketPage2[5], 4);
        TextDrawSetProportional(MarketPage2[5], 1);
        TextDrawSetSelectable(MarketPage2[5], 1);

        MarketPage2[6] = TextDrawCreate(247.000, 269.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[6], 46.000, 59.000);
        TextDrawAlignment(MarketPage2[6], 1);
        TextDrawColor(MarketPage2[6], 131684);
        TextDrawSetShadow(MarketPage2[6], 0);
        TextDrawSetOutline(MarketPage2[6], 0);
        TextDrawBackgroundColor(MarketPage2[6], 255);
        TextDrawFont(MarketPage2[6], 4);
        TextDrawSetProportional(MarketPage2[6], 1);

        MarketPage2[7] = TextDrawCreate(299.000, 269.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[7], 46.000, 59.000);
        TextDrawAlignment(MarketPage2[7], 1);
        TextDrawColor(MarketPage2[7], 131684);
        TextDrawSetShadow(MarketPage2[7], 0);
        TextDrawSetOutline(MarketPage2[7], 0);
        TextDrawBackgroundColor(MarketPage2[7], 255);
        TextDrawFont(MarketPage2[7], 4);
        TextDrawSetProportional(MarketPage2[7], 1);

        MarketPage2[8] = TextDrawCreate(247.000, 178.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[8], 46.000, 59.000);
        TextDrawAlignment(MarketPage2[8], 1);
        TextDrawColor(MarketPage2[8], 131684);
        TextDrawSetShadow(MarketPage2[8], 0);
        TextDrawSetOutline(MarketPage2[8], 0);
        TextDrawBackgroundColor(MarketPage2[8], 255);
        TextDrawFont(MarketPage2[8], 4);
        TextDrawSetProportional(MarketPage2[8], 1);

        MarketPage2[9] = TextDrawCreate(299.000, 178.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[9], 46.000, 59.000);
        TextDrawAlignment(MarketPage2[9], 1);
        TextDrawColor(MarketPage2[9], 131684);
        TextDrawSetShadow(MarketPage2[9], 0);
        TextDrawSetOutline(MarketPage2[9], 0);
        TextDrawBackgroundColor(MarketPage2[9], 255);
        TextDrawFont(MarketPage2[9], 4);
        TextDrawSetProportional(MarketPage2[9], 1);

        MarketPage2[10] = TextDrawCreate(351.000, 178.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[10], 46.000, 59.000);
        TextDrawAlignment(MarketPage2[10], 1);
        TextDrawColor(MarketPage2[10], 131684);
        TextDrawSetShadow(MarketPage2[10], 0);
        TextDrawSetOutline(MarketPage2[10], 0);
        TextDrawBackgroundColor(MarketPage2[10], 255);
        TextDrawFont(MarketPage2[10], 4);
        TextDrawSetProportional(MarketPage2[10], 1);

        MarketPage2[11] = TextDrawCreate(403.000, 178.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[11], 46.000, 59.000);
        TextDrawAlignment(MarketPage2[11], 1);
        TextDrawColor(MarketPage2[11], 131684);
        TextDrawSetShadow(MarketPage2[11], 0);
        TextDrawSetOutline(MarketPage2[11], 0);
        TextDrawBackgroundColor(MarketPage2[11], 255);
        TextDrawFont(MarketPage2[11], 4);
        TextDrawSetProportional(MarketPage2[11], 1);

        MarketPage2[12] = TextDrawCreate(351.000, 268.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[12], 46.000, 59.000);
        TextDrawAlignment(MarketPage2[12], 1);
        TextDrawColor(MarketPage2[12], 131684);
        TextDrawSetShadow(MarketPage2[12], 0);
        TextDrawSetOutline(MarketPage2[12], 0);
        TextDrawBackgroundColor(MarketPage2[12], 255);
        TextDrawFont(MarketPage2[12], 4);
        TextDrawSetProportional(MarketPage2[12], 1);

        MarketPage2[13] = TextDrawCreate(403.000, 268.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[13], 46.000, 59.000);
        TextDrawAlignment(MarketPage2[13], 1);
        TextDrawColor(MarketPage2[13], 131684);
        TextDrawSetShadow(MarketPage2[13], 0);
        TextDrawSetOutline(MarketPage2[13], 0);
        TextDrawBackgroundColor(MarketPage2[13], 255);
        TextDrawFont(MarketPage2[13], 4);
        TextDrawSetProportional(MarketPage2[13], 1);

        MarketPage2[14] = TextDrawCreate(247.000, 240.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[14], 46.000, 20.000);
        TextDrawAlignment(MarketPage2[14], 1);
        TextDrawColor(MarketPage2[14], -377187329);
        TextDrawSetShadow(MarketPage2[14], 0);
        TextDrawSetOutline(MarketPage2[14], 0);
        TextDrawBackgroundColor(MarketPage2[14], 255);
        TextDrawFont(MarketPage2[14], 4);
        TextDrawSetProportional(MarketPage2[14], 1);
        TextDrawSetSelectable(MarketPage2[14], 1);

        MarketPage2[15] = TextDrawCreate(299.000, 240.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[15], 46.000, 20.000);
        TextDrawAlignment(MarketPage2[15], 1);
        TextDrawColor(MarketPage2[15], -377187329);
        TextDrawSetShadow(MarketPage2[15], 0);
        TextDrawSetOutline(MarketPage2[15], 0);
        TextDrawBackgroundColor(MarketPage2[15], 255);
        TextDrawFont(MarketPage2[15], 4);
        TextDrawSetProportional(MarketPage2[15], 1);
        TextDrawSetSelectable(MarketPage2[15], 1);

        MarketPage2[16] = TextDrawCreate(351.000, 241.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[16], 46.000, 20.000);
        TextDrawAlignment(MarketPage2[16], 1);
        TextDrawColor(MarketPage2[16], -377187329);
        TextDrawSetShadow(MarketPage2[16], 0);
        TextDrawSetOutline(MarketPage2[16], 0);
        TextDrawBackgroundColor(MarketPage2[16], 255);
        TextDrawFont(MarketPage2[16], 4);
        TextDrawSetProportional(MarketPage2[16], 1);
        TextDrawSetSelectable(MarketPage2[16], 1);

        MarketPage2[17] = TextDrawCreate(403.000, 241.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[17], 46.000, 20.000);
        TextDrawAlignment(MarketPage2[17], 1);
        TextDrawColor(MarketPage2[17], -377187329);
        TextDrawSetShadow(MarketPage2[17], 0);
        TextDrawSetOutline(MarketPage2[17], 0);
        TextDrawBackgroundColor(MarketPage2[17], 255);
        TextDrawFont(MarketPage2[17], 4);
        TextDrawSetProportional(MarketPage2[17], 1);
        TextDrawSetSelectable(MarketPage2[17], 1);

        MarketPage2[18] = TextDrawCreate(247.000, 331.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[18], 46.000, 20.000);
        TextDrawAlignment(MarketPage2[18], 1);
        TextDrawColor(MarketPage2[18], -377187329);
        TextDrawSetShadow(MarketPage2[18], 0);
        TextDrawSetOutline(MarketPage2[18], 0);
        TextDrawBackgroundColor(MarketPage2[18], 255);
        TextDrawFont(MarketPage2[18], 4);
        TextDrawSetProportional(MarketPage2[18], 1);
        TextDrawSetSelectable(MarketPage2[18], 1);

        MarketPage2[19] = TextDrawCreate(299.000, 331.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[19], 46.000, 20.000);
        TextDrawAlignment(MarketPage2[19], 1);
        TextDrawColor(MarketPage2[19], -377187329);
        TextDrawSetShadow(MarketPage2[19], 0);
        TextDrawSetOutline(MarketPage2[19], 0);
        TextDrawBackgroundColor(MarketPage2[19], 255);
        TextDrawFont(MarketPage2[19], 4);
        TextDrawSetProportional(MarketPage2[19], 1);
        TextDrawSetSelectable(MarketPage2[19], 1);

        MarketPage2[20] = TextDrawCreate(351.000, 331.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[20], 46.000, 20.000);
        TextDrawAlignment(MarketPage2[20], 1);
        TextDrawColor(MarketPage2[20], -377187329);
        TextDrawSetShadow(MarketPage2[20], 0);
        TextDrawSetOutline(MarketPage2[20], 0);
        TextDrawBackgroundColor(MarketPage2[20], 255);
        TextDrawFont(MarketPage2[20], 4);
        TextDrawSetProportional(MarketPage2[20], 1);
        TextDrawSetSelectable(MarketPage2[20], 1);

        MarketPage2[21] = TextDrawCreate(403.000, 331.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[21], 46.000, 20.000);
        TextDrawAlignment(MarketPage2[21], 1);
        TextDrawColor(MarketPage2[21], -377187329);
        TextDrawSetShadow(MarketPage2[21], 0);
        TextDrawSetOutline(MarketPage2[21], 0);
        TextDrawBackgroundColor(MarketPage2[21], 255);
        TextDrawFont(MarketPage2[21], 4);
        TextDrawSetProportional(MarketPage2[21], 1);
        TextDrawSetSelectable(MarketPage2[21], 1);

        MarketPage2[22] = TextDrawCreate(261.000, 165.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[22], 173.000, -4.000);
        TextDrawAlignment(MarketPage2[22], 1);
        TextDrawColor(MarketPage2[22], -1);
        TextDrawSetShadow(MarketPage2[22], 0);
        TextDrawSetOutline(MarketPage2[22], 0);
        TextDrawBackgroundColor(MarketPage2[22], 255);
        TextDrawFont(MarketPage2[22], 4);
        TextDrawSetProportional(MarketPage2[22], 1);

        MarketPage2[23] = TextDrawCreate(435.000, 153.000, "LD_BEAT:right");
        TextDrawTextSize(MarketPage2[23], 14.000, 20.000);
        TextDrawAlignment(MarketPage2[23], 1);
        TextDrawColor(MarketPage2[23], -1);
        TextDrawSetShadow(MarketPage2[23], 0);
        TextDrawSetOutline(MarketPage2[23], 0);
        TextDrawBackgroundColor(MarketPage2[23], 255);
        TextDrawFont(MarketPage2[23], 4);
        TextDrawSetProportional(MarketPage2[23], 1);
        TextDrawSetSelectable(MarketPage2[23], 1);

        MarketPage2[24] = TextDrawCreate(246.000, 154.000, "LD_BEAT:left");
        TextDrawTextSize(MarketPage2[24], 14.000, 20.000);
        TextDrawAlignment(MarketPage2[24], 1);
        TextDrawColor(MarketPage2[24], -1);
        TextDrawSetShadow(MarketPage2[24], 0);
        TextDrawSetOutline(MarketPage2[24], 0);
        TextDrawBackgroundColor(MarketPage2[24], 255);
        TextDrawFont(MarketPage2[24], 4);
        TextDrawSetProportional(MarketPage2[24], 1);
        TextDrawSetSelectable(MarketPage2[24], 1);

        MarketPage2[25] = TextDrawCreate(188.000, 143.000, "MARKET 24/7");
        TextDrawLetterSize(MarketPage2[25], 0.239, 1.600);
        TextDrawAlignment(MarketPage2[25], 1);
        TextDrawColor(MarketPage2[25], -602653441);
        TextDrawSetShadow(MarketPage2[25], 0);
        TextDrawSetOutline(MarketPage2[25], 0);
        TextDrawBackgroundColor(MarketPage2[25], 150);
        TextDrawFont(MarketPage2[25], 1);
        TextDrawSetProportional(MarketPage2[25], 1);

        MarketPage2[26] = TextDrawCreate(189.000, 159.000, "Vyn_Ytp");
        TextDrawLetterSize(MarketPage2[26], 0.189, 1.600);
        TextDrawAlignment(MarketPage2[26], 1);
        TextDrawColor(MarketPage2[26], -106);
        TextDrawSetShadow(MarketPage2[26], 0);
        TextDrawSetOutline(MarketPage2[26], 0);
        TextDrawBackgroundColor(MarketPage2[26], 150);
        TextDrawFont(MarketPage2[26], 1);
        TextDrawSetProportional(MarketPage2[26], 1);

        MarketPage2[27] = TextDrawCreate(182.000, 181.000, "Selamat datang");
        TextDrawLetterSize(MarketPage2[27], 0.189, 1.600);
        TextDrawAlignment(MarketPage2[27], 1);
        TextDrawColor(MarketPage2[27], -106);
        TextDrawSetShadow(MarketPage2[27], 0);
        TextDrawSetOutline(MarketPage2[27], 0);
        TextDrawBackgroundColor(MarketPage2[27], 150);
        TextDrawFont(MarketPage2[27], 1);
        TextDrawSetProportional(MarketPage2[27], 1);

        MarketPage2[28] = TextDrawCreate(178.000, 194.000, "selamat berbelanja");
        TextDrawLetterSize(MarketPage2[28], 0.189, 1.600);
        TextDrawAlignment(MarketPage2[28], 1);
        TextDrawColor(MarketPage2[28], -106);
        TextDrawSetShadow(MarketPage2[28], 0);
        TextDrawSetOutline(MarketPage2[28], 0);
        TextDrawBackgroundColor(MarketPage2[28], 150);
        TextDrawFont(MarketPage2[28], 1);
        TextDrawSetProportional(MarketPage2[28], 1);

        MarketPage2[29] = TextDrawCreate(200.000, 233.000, "Tutup");
        TextDrawLetterSize(MarketPage2[29], 0.188, 1.600);
        TextDrawAlignment(MarketPage2[29], 1);
        TextDrawColor(MarketPage2[29], -106);
        TextDrawSetShadow(MarketPage2[29], 0);
        TextDrawSetOutline(MarketPage2[29], 0);
        TextDrawBackgroundColor(MarketPage2[29], 150);
        TextDrawFont(MarketPage2[29], 1);
        TextDrawSetProportional(MarketPage2[29], 1);

        MarketPage2[30] = TextDrawCreate(369.000, 243.000, "Beli");
        TextDrawLetterSize(MarketPage2[30], 0.188, 1.600);
        TextDrawAlignment(MarketPage2[30], 1);
        TextDrawColor(MarketPage2[30], -106);
        TextDrawSetShadow(MarketPage2[30], 0);
        TextDrawSetOutline(MarketPage2[30], 0);
        TextDrawBackgroundColor(MarketPage2[30], 150);
        TextDrawFont(MarketPage2[30], 1);
        TextDrawSetProportional(MarketPage2[30], 1);

        MarketPage2[31] = TextDrawCreate(420.000, 243.000, "Beli");
        TextDrawLetterSize(MarketPage2[31], 0.188, 1.600);
        TextDrawAlignment(MarketPage2[31], 1);
        TextDrawColor(MarketPage2[31], -106);
        TextDrawSetShadow(MarketPage2[31], 0);
        TextDrawSetOutline(MarketPage2[31], 0);
        TextDrawBackgroundColor(MarketPage2[31], 150);
        TextDrawFont(MarketPage2[31], 1);
        TextDrawSetProportional(MarketPage2[31], 1);

        MarketPage2[32] = TextDrawCreate(265.000, 242.000, "Beli");
        TextDrawLetterSize(MarketPage2[32], 0.188, 1.600);
        TextDrawAlignment(MarketPage2[32], 1);
        TextDrawColor(MarketPage2[32], -106);
        TextDrawSetShadow(MarketPage2[32], 0);
        TextDrawSetOutline(MarketPage2[32], 0);
        TextDrawBackgroundColor(MarketPage2[32], 150);
        TextDrawFont(MarketPage2[32], 1);
        TextDrawSetProportional(MarketPage2[32], 1);

        MarketPage2[33] = TextDrawCreate(316.000, 242.000, "Beli");
        TextDrawLetterSize(MarketPage2[33], 0.188, 1.600);
        TextDrawAlignment(MarketPage2[33], 1);
        TextDrawColor(MarketPage2[33], -106);
        TextDrawSetShadow(MarketPage2[33], 0);
        TextDrawSetOutline(MarketPage2[33], 0);
        TextDrawBackgroundColor(MarketPage2[33], 150);
        TextDrawFont(MarketPage2[33], 1);
        TextDrawSetProportional(MarketPage2[33], 1);

        MarketPage2[34] = TextDrawCreate(266.000, 332.000, "Beli");
        TextDrawLetterSize(MarketPage2[34], 0.188, 1.600);
        TextDrawAlignment(MarketPage2[34], 1);
        TextDrawColor(MarketPage2[34], -106);
        TextDrawSetShadow(MarketPage2[34], 0);
        TextDrawSetOutline(MarketPage2[34], 0);
        TextDrawBackgroundColor(MarketPage2[34], 150);
        TextDrawFont(MarketPage2[34], 1);
        TextDrawSetProportional(MarketPage2[34], 1);

        MarketPage2[35] = TextDrawCreate(317.000, 332.000, "Beli");
        TextDrawLetterSize(MarketPage2[35], 0.188, 1.600);
        TextDrawAlignment(MarketPage2[35], 1);
        TextDrawColor(MarketPage2[35], -106);
        TextDrawSetShadow(MarketPage2[35], 0);
        TextDrawSetOutline(MarketPage2[35], 0);
        TextDrawBackgroundColor(MarketPage2[35], 150);
        TextDrawFont(MarketPage2[35], 1);
        TextDrawSetProportional(MarketPage2[35], 1);

        MarketPage2[36] = TextDrawCreate(369.000, 333.000, "Beli");
        TextDrawLetterSize(MarketPage2[36], 0.188, 1.600);
        TextDrawAlignment(MarketPage2[36], 1);
        TextDrawColor(MarketPage2[36], -106);
        TextDrawSetShadow(MarketPage2[36], 0);
        TextDrawSetOutline(MarketPage2[36], 0);
        TextDrawBackgroundColor(MarketPage2[36], 150);
        TextDrawFont(MarketPage2[36], 1);
        TextDrawSetProportional(MarketPage2[36], 1);

        MarketPage2[37] = TextDrawCreate(420.000, 333.000, "Beli");
        TextDrawLetterSize(MarketPage2[37], 0.188, 1.600);
        TextDrawAlignment(MarketPage2[37], 1);
        TextDrawColor(MarketPage2[37], -106);
        TextDrawSetShadow(MarketPage2[37], 0);
        TextDrawSetOutline(MarketPage2[37], 0);
        TextDrawBackgroundColor(MarketPage2[37], 150);
        TextDrawFont(MarketPage2[37], 1);
        TextDrawSetProportional(MarketPage2[37], 1);

        MarketPage2[38] = TextDrawCreate(234.000, 173.000, "_");
        TextDrawTextSize(MarketPage2[38], 90.000, 90.000);
        TextDrawAlignment(MarketPage2[38], 1);
        TextDrawColor(MarketPage2[38], -1);
        TextDrawSetShadow(MarketPage2[38], 0);
        TextDrawSetOutline(MarketPage2[38], 0);
        TextDrawBackgroundColor(MarketPage2[38], 131584);
        TextDrawFont(MarketPage2[38], 5);
        TextDrawSetProportional(MarketPage2[38], 0);
        TextDrawSetPreviewModel(MarketPage2[38], 357);
        TextDrawSetPreviewRot(MarketPage2[38], 0.000, -27.000, 16.000, 3.299);
        TextDrawSetPreviewVehCol(MarketPage2[38], 0, 0);

        MarketPage2[39] = TextDrawCreate(276.000, 164.000, "_");
        TextDrawTextSize(MarketPage2[39], 90.000, 90.000);
        TextDrawAlignment(MarketPage2[39], 1);
        TextDrawColor(MarketPage2[39], -1);
        TextDrawSetShadow(MarketPage2[39], 0);
        TextDrawSetOutline(MarketPage2[39], 0);
        TextDrawBackgroundColor(MarketPage2[39], 0);
        TextDrawFont(MarketPage2[39], 5);
        TextDrawSetProportional(MarketPage2[39], 0);
        TextDrawSetPreviewModel(MarketPage2[39], 2358);
        TextDrawSetPreviewRot(MarketPage2[39], 177.000, 181.000, 0.000, 1.700);
        TextDrawSetPreviewVehCol(MarketPage2[39], 0, 0);

        MarketPage2[40] = TextDrawCreate(328.000, 164.000, "_");
        TextDrawTextSize(MarketPage2[40], 90.000, 90.000);
        TextDrawAlignment(MarketPage2[40], 1);
        TextDrawColor(MarketPage2[40], -1);
        TextDrawSetShadow(MarketPage2[40], 0);
        TextDrawSetOutline(MarketPage2[40], 0);
        TextDrawBackgroundColor(MarketPage2[40], 0);
        TextDrawFont(MarketPage2[40], 5);
        TextDrawSetProportional(MarketPage2[40], 0);
        TextDrawSetPreviewModel(MarketPage2[40], 19627);
        TextDrawSetPreviewRot(MarketPage2[40], -88.000, 0.000, 90.000, 1.700);
        TextDrawSetPreviewVehCol(MarketPage2[40], 0, 0);

        MarketPage2[41] = TextDrawCreate(386.000, 157.000, "_");
        TextDrawTextSize(MarketPage2[41], 90.000, 90.000);
        TextDrawAlignment(MarketPage2[41], 1);
        TextDrawColor(MarketPage2[41], -1);
        TextDrawSetShadow(MarketPage2[41], 0);
        TextDrawSetOutline(MarketPage2[41], 0);
        TextDrawBackgroundColor(MarketPage2[41], 0);
        TextDrawFont(MarketPage2[41], 5);
        TextDrawSetProportional(MarketPage2[41], 0);
        TextDrawSetPreviewModel(MarketPage2[41], 365);
        TextDrawSetPreviewRot(MarketPage2[41], 0.000, -5.000, 0.000, 1.299);
        TextDrawSetPreviewVehCol(MarketPage2[41], 0, 0);

        MarketPage2[42] = TextDrawCreate(224.000, 252.000, "_");
        TextDrawTextSize(MarketPage2[42], 90.000, 90.000);
        TextDrawAlignment(MarketPage2[42], 1);
        TextDrawColor(MarketPage2[42], -1);
        TextDrawSetShadow(MarketPage2[42], 0);
        TextDrawSetOutline(MarketPage2[42], 0);
        TextDrawBackgroundColor(MarketPage2[42], 0);
        TextDrawFont(MarketPage2[42], 5);
        TextDrawSetProportional(MarketPage2[42], 0);
        TextDrawSetPreviewModel(MarketPage2[42], 18641);
        TextDrawSetPreviewRot(MarketPage2[42], -5.000, 0.000, 170.000, 2.598);
        TextDrawSetPreviewVehCol(MarketPage2[42], 0, 0);

        MarketPage2[43] = TextDrawCreate(275.000, 254.000, "_");
        TextDrawTextSize(MarketPage2[43], 90.000, 90.000);
        TextDrawAlignment(MarketPage2[43], 1);
        TextDrawColor(MarketPage2[43], -1);
        TextDrawSetShadow(MarketPage2[43], 0);
        TextDrawSetOutline(MarketPage2[43], 0);
        TextDrawBackgroundColor(MarketPage2[43], 0);
        TextDrawFont(MarketPage2[43], 5);
        TextDrawSetProportional(MarketPage2[43], 0);
        TextDrawSetPreviewModel(MarketPage2[43], 2228);
        TextDrawSetPreviewRot(MarketPage2[43], -5.000, 0.000, 170.000, 2.598);
        TextDrawSetPreviewVehCol(MarketPage2[43], 0, 0);

        MarketPage2[44] = TextDrawCreate(326.000, 253.000, "_");
        TextDrawTextSize(MarketPage2[44], 90.000, 90.000);
        TextDrawAlignment(MarketPage2[44], 1);
        TextDrawColor(MarketPage2[44], -1);
        TextDrawSetShadow(MarketPage2[44], 0);
        TextDrawSetOutline(MarketPage2[44], 0);
        TextDrawBackgroundColor(MarketPage2[44], 0);
        TextDrawFont(MarketPage2[44], 5);
        TextDrawSetProportional(MarketPage2[44], 0);
        TextDrawSetPreviewModel(MarketPage2[44], 18632);
        TextDrawSetPreviewRot(MarketPage2[44], -5.000, 0.000, 313.000, 1.899);
        TextDrawSetPreviewVehCol(MarketPage2[44], 0, 0);

        MarketPage2[45] = TextDrawCreate(379.000, 252.000, "_");
        TextDrawTextSize(MarketPage2[45], 90.000, 90.000);
        TextDrawAlignment(MarketPage2[45], 1);
        TextDrawColor(MarketPage2[45], -1);
        TextDrawSetShadow(MarketPage2[45], 0);
        TextDrawSetOutline(MarketPage2[45], 0);
        TextDrawBackgroundColor(MarketPage2[45], 0);
        TextDrawFont(MarketPage2[45], 5);
        TextDrawSetProportional(MarketPage2[45], 0);
        TextDrawSetPreviewModel(MarketPage2[45], 19573);
        TextDrawSetPreviewRot(MarketPage2[45], 0.000, 0.000, 0.000, 2.299);
        TextDrawSetPreviewVehCol(MarketPage2[45], 0, 0);

        MarketPage2[46] = TextDrawCreate(248.000, 178.000, "$1200");
        TextDrawLetterSize(MarketPage2[46], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[46], 1);
        TextDrawColor(MarketPage2[46], 852308735);
        TextDrawSetShadow(MarketPage2[46], 0);
        TextDrawSetOutline(MarketPage2[46], 0);
        TextDrawBackgroundColor(MarketPage2[46], 150);
        TextDrawFont(MarketPage2[46], 1);
        TextDrawSetProportional(MarketPage2[46], 1);

        MarketPage2[47] = TextDrawCreate(300.000, 178.000, "$700");
        TextDrawLetterSize(MarketPage2[47], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[47], 1);
        TextDrawColor(MarketPage2[47], 852308735);
        TextDrawSetShadow(MarketPage2[47], 0);
        TextDrawSetOutline(MarketPage2[47], 0);
        TextDrawBackgroundColor(MarketPage2[47], 150);
        TextDrawFont(MarketPage2[47], 1);
        TextDrawSetProportional(MarketPage2[47], 1);

        MarketPage2[48] = TextDrawCreate(352.000, 178.000, "$620");
        TextDrawLetterSize(MarketPage2[48], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[48], 1);
        TextDrawColor(MarketPage2[48], 852308735);
        TextDrawSetShadow(MarketPage2[48], 0);
        TextDrawSetOutline(MarketPage2[48], 0);
        TextDrawBackgroundColor(MarketPage2[48], 150);
        TextDrawFont(MarketPage2[48], 1);
        TextDrawSetProportional(MarketPage2[48], 1);

        MarketPage2[49] = TextDrawCreate(404.000, 178.000, "$780");
        TextDrawLetterSize(MarketPage2[49], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[49], 1);
        TextDrawColor(MarketPage2[49], 852308735);
        TextDrawSetShadow(MarketPage2[49], 0);
        TextDrawSetOutline(MarketPage2[49], 0);
        TextDrawBackgroundColor(MarketPage2[49], 150);
        TextDrawFont(MarketPage2[49], 1);
        TextDrawSetProportional(MarketPage2[49], 1);

        MarketPage2[50] = TextDrawCreate(248.000, 228.000, "Hunting Rifle");
        TextDrawLetterSize(MarketPage2[50], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[50], 1);
        TextDrawColor(MarketPage2[50], -1);
        TextDrawSetShadow(MarketPage2[50], 0);
        TextDrawSetOutline(MarketPage2[50], 0);
        TextDrawBackgroundColor(MarketPage2[50], 150);
        TextDrawFont(MarketPage2[50], 1);
        TextDrawSetProportional(MarketPage2[50], 1);

        MarketPage2[51] = TextDrawCreate(300.000, 228.000, "Hunting Ammo");
        TextDrawLetterSize(MarketPage2[51], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[51], 1);
        TextDrawColor(MarketPage2[51], -1);
        TextDrawSetShadow(MarketPage2[51], 0);
        TextDrawSetOutline(MarketPage2[51], 0);
        TextDrawBackgroundColor(MarketPage2[51], 150);
        TextDrawFont(MarketPage2[51], 1);
        TextDrawSetProportional(MarketPage2[51], 1);

        MarketPage2[52] = TextDrawCreate(352.000, 228.000, "Obeng");
        TextDrawLetterSize(MarketPage2[52], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[52], 1);
        TextDrawColor(MarketPage2[52], -1);
        TextDrawSetShadow(MarketPage2[52], 0);
        TextDrawSetOutline(MarketPage2[52], 0);
        TextDrawBackgroundColor(MarketPage2[52], 150);
        TextDrawFont(MarketPage2[52], 1);
        TextDrawSetProportional(MarketPage2[52], 1);

        MarketPage2[53] = TextDrawCreate(404.000, 228.000, "Pilox");
        TextDrawLetterSize(MarketPage2[53], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[53], 1);
        TextDrawColor(MarketPage2[53], -1);
        TextDrawSetShadow(MarketPage2[53], 0);
        TextDrawSetOutline(MarketPage2[53], 0);
        TextDrawBackgroundColor(MarketPage2[53], 150);
        TextDrawFont(MarketPage2[53], 1);
        TextDrawSetProportional(MarketPage2[53], 1);

        MarketPage2[54] = TextDrawCreate(248.000, 268.000, "$520");
        TextDrawLetterSize(MarketPage2[54], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[54], 1);
        TextDrawColor(MarketPage2[54], 852308735);
        TextDrawSetShadow(MarketPage2[54], 0);
        TextDrawSetOutline(MarketPage2[54], 0);
        TextDrawBackgroundColor(MarketPage2[54], 150);
        TextDrawFont(MarketPage2[54], 1);
        TextDrawSetProportional(MarketPage2[54], 1);

        MarketPage2[55] = TextDrawCreate(300.000, 268.000, "$500");
        TextDrawLetterSize(MarketPage2[55], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[55], 1);
        TextDrawColor(MarketPage2[55], 852308735);
        TextDrawSetShadow(MarketPage2[55], 0);
        TextDrawSetOutline(MarketPage2[55], 0);
        TextDrawBackgroundColor(MarketPage2[55], 150);
        TextDrawFont(MarketPage2[55], 1);
        TextDrawSetProportional(MarketPage2[55], 1);

        MarketPage2[56] = TextDrawCreate(352.000, 268.000, "$980");
        TextDrawLetterSize(MarketPage2[56], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[56], 1);
        TextDrawColor(MarketPage2[56], 852308735);
        TextDrawSetShadow(MarketPage2[56], 0);
        TextDrawSetOutline(MarketPage2[56], 0);
        TextDrawBackgroundColor(MarketPage2[56], 150);
        TextDrawFont(MarketPage2[56], 1);
        TextDrawSetProportional(MarketPage2[56], 1);

        MarketPage2[57] = TextDrawCreate(404.000, 268.000, "$100");
        TextDrawLetterSize(MarketPage2[57], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[57], 1);
        TextDrawColor(MarketPage2[57], 852308735);
        TextDrawSetShadow(MarketPage2[57], 0);
        TextDrawSetOutline(MarketPage2[57], 0);
        TextDrawBackgroundColor(MarketPage2[57], 150);
        TextDrawFont(MarketPage2[57], 1);
        TextDrawSetProportional(MarketPage2[57], 1);

        MarketPage2[58] = TextDrawCreate(248.000, 318.000, "Senter");
        TextDrawLetterSize(MarketPage2[58], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[58], 1);
        TextDrawColor(MarketPage2[58], -1);
        TextDrawSetShadow(MarketPage2[58], 0);
        TextDrawSetOutline(MarketPage2[58], 0);
        TextDrawBackgroundColor(MarketPage2[58], 150);
        TextDrawFont(MarketPage2[58], 1);
        TextDrawSetProportional(MarketPage2[58], 1);

        MarketPage2[59] = TextDrawCreate(300.000, 318.000, "Cangkul");
        TextDrawLetterSize(MarketPage2[59], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[59], 1);
        TextDrawColor(MarketPage2[59], -1);
        TextDrawSetShadow(MarketPage2[59], 0);
        TextDrawSetOutline(MarketPage2[59], 0);
        TextDrawBackgroundColor(MarketPage2[59], 150);
        TextDrawFont(MarketPage2[59], 1);
        TextDrawSetProportional(MarketPage2[59], 1);

        MarketPage2[60] = TextDrawCreate(352.000, 318.000, "Pancingan");
        TextDrawLetterSize(MarketPage2[60], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[60], 1);
        TextDrawColor(MarketPage2[60], -1);
        TextDrawSetShadow(MarketPage2[60], 0);
        TextDrawSetOutline(MarketPage2[60], 0);
        TextDrawBackgroundColor(MarketPage2[60], 150);
        TextDrawFont(MarketPage2[60], 1);
        TextDrawSetProportional(MarketPage2[60], 1);

        MarketPage2[61] = TextDrawCreate(404.000, 318.000, "Umpan");
        TextDrawLetterSize(MarketPage2[61], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[61], 1);
        TextDrawColor(MarketPage2[61], -1);
        TextDrawSetShadow(MarketPage2[61], 0);
        TextDrawSetOutline(MarketPage2[61], 0);
        TextDrawBackgroundColor(MarketPage2[61], 150);
        TextDrawFont(MarketPage2[61], 1);
        TextDrawSetProportional(MarketPage2[61], 1);

        MarketPage2[62] = TextDrawCreate(287.000, 178.000, "x1");
        TextDrawLetterSize(MarketPage2[62], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[62], 1);
        TextDrawColor(MarketPage2[62], -1);
        TextDrawSetShadow(MarketPage2[62], 0);
        TextDrawSetOutline(MarketPage2[62], 0);
        TextDrawBackgroundColor(MarketPage2[62], 150);
        TextDrawFont(MarketPage2[62], 1);
        TextDrawSetProportional(MarketPage2[62], 1);

        MarketPage2[63] = TextDrawCreate(339.000, 178.000, "x1");
        TextDrawLetterSize(MarketPage2[63], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[63], 1);
        TextDrawColor(MarketPage2[63], -1);
        TextDrawSetShadow(MarketPage2[63], 0);
        TextDrawSetOutline(MarketPage2[63], 0);
        TextDrawBackgroundColor(MarketPage2[63], 150);
        TextDrawFont(MarketPage2[63], 1);
        TextDrawSetProportional(MarketPage2[63], 1);

        MarketPage2[64] = TextDrawCreate(391.000, 178.000, "x1");
        TextDrawLetterSize(MarketPage2[64], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[64], 1);
        TextDrawColor(MarketPage2[64], -1);
        TextDrawSetShadow(MarketPage2[64], 0);
        TextDrawSetOutline(MarketPage2[64], 0);
        TextDrawBackgroundColor(MarketPage2[64], 150);
        TextDrawFont(MarketPage2[64], 1);
        TextDrawSetProportional(MarketPage2[64], 1);

        MarketPage2[65] = TextDrawCreate(443.000, 178.000, "x1");
        TextDrawLetterSize(MarketPage2[65], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[65], 1);
        TextDrawColor(MarketPage2[65], -1);
        TextDrawSetShadow(MarketPage2[65], 0);
        TextDrawSetOutline(MarketPage2[65], 0);
        TextDrawBackgroundColor(MarketPage2[65], 150);
        TextDrawFont(MarketPage2[65], 1);
        TextDrawSetProportional(MarketPage2[65], 1);

        MarketPage2[66] = TextDrawCreate(287.000, 269.000, "x1");
        TextDrawLetterSize(MarketPage2[66], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[66], 1);
        TextDrawColor(MarketPage2[66], -1);
        TextDrawSetShadow(MarketPage2[66], 0);
        TextDrawSetOutline(MarketPage2[66], 0);
        TextDrawBackgroundColor(MarketPage2[66], 150);
        TextDrawFont(MarketPage2[66], 1);
        TextDrawSetProportional(MarketPage2[66], 1);

        MarketPage2[67] = TextDrawCreate(339.000, 269.000, "x1");
        TextDrawLetterSize(MarketPage2[67], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[67], 1);
        TextDrawColor(MarketPage2[67], -1);
        TextDrawSetShadow(MarketPage2[67], 0);
        TextDrawSetOutline(MarketPage2[67], 0);
        TextDrawBackgroundColor(MarketPage2[67], 150);
        TextDrawFont(MarketPage2[67], 1);
        TextDrawSetProportional(MarketPage2[67], 1);

        MarketPage2[68] = TextDrawCreate(391.000, 269.000, "x1");
        TextDrawLetterSize(MarketPage2[68], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[68], 1);
        TextDrawColor(MarketPage2[68], -1);
        TextDrawSetShadow(MarketPage2[68], 0);
        TextDrawSetOutline(MarketPage2[68], 0);
        TextDrawBackgroundColor(MarketPage2[68], 150);
        TextDrawFont(MarketPage2[68], 1);
        TextDrawSetProportional(MarketPage2[68], 1);

        MarketPage2[69] = TextDrawCreate(443.000, 269.000, "x1");
        TextDrawLetterSize(MarketPage2[69], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[69], 1);
        TextDrawColor(MarketPage2[69], -1);
        TextDrawSetShadow(MarketPage2[69], 0);
        TextDrawSetOutline(MarketPage2[69], 0);
        TextDrawBackgroundColor(MarketPage2[69], 150);
        TextDrawFont(MarketPage2[69], 1);
        TextDrawSetProportional(MarketPage2[69], 1);

        MarketPage2[70] = TextDrawCreate(193.000, 269.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[70], 46.000, 59.000);
        TextDrawAlignment(MarketPage2[70], 1);
        TextDrawColor(MarketPage2[70], 131684);
        TextDrawSetShadow(MarketPage2[70], 0);
        TextDrawSetOutline(MarketPage2[70], 0);
        TextDrawBackgroundColor(MarketPage2[70], 255);
        TextDrawFont(MarketPage2[70], 4);
        TextDrawSetProportional(MarketPage2[70], 1);

        MarketPage2[71] = TextDrawCreate(193.000, 331.000, "LD_SPAC:white");
        TextDrawTextSize(MarketPage2[71], 46.000, 20.000);
        TextDrawAlignment(MarketPage2[71], 1);
        TextDrawColor(MarketPage2[71], -377187329);
        TextDrawSetShadow(MarketPage2[71], 0);
        TextDrawSetOutline(MarketPage2[71], 0);
        TextDrawBackgroundColor(MarketPage2[71], 255);
        TextDrawFont(MarketPage2[71], 4);
        TextDrawSetProportional(MarketPage2[71], 1);
        TextDrawSetSelectable(MarketPage2[71], 1);

        MarketPage2[72] = TextDrawCreate(194.000, 318.000, "Ember");
        TextDrawLetterSize(MarketPage2[72], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[72], 1);
        TextDrawColor(MarketPage2[72], -1);
        TextDrawSetShadow(MarketPage2[72], 0);
        TextDrawSetOutline(MarketPage2[72], 0);
        TextDrawBackgroundColor(MarketPage2[72], 150);
        TextDrawFont(MarketPage2[72], 1);
        TextDrawSetProportional(MarketPage2[72], 1);

        MarketPage2[73] = TextDrawCreate(211.000, 332.000, "Beli");
        TextDrawLetterSize(MarketPage2[73], 0.188, 1.600);
        TextDrawAlignment(MarketPage2[73], 1);
        TextDrawColor(MarketPage2[73], -106);
        TextDrawSetShadow(MarketPage2[73], 0);
        TextDrawSetOutline(MarketPage2[73], 0);
        TextDrawBackgroundColor(MarketPage2[73], 150);
        TextDrawFont(MarketPage2[73], 1);
        TextDrawSetProportional(MarketPage2[73], 1);

        MarketPage2[74] = TextDrawCreate(194.000, 268.000, "$520");
        TextDrawLetterSize(MarketPage2[74], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[74], 1);
        TextDrawColor(MarketPage2[74], 852308735);
        TextDrawSetShadow(MarketPage2[74], 0);
        TextDrawSetOutline(MarketPage2[74], 0);
        TextDrawBackgroundColor(MarketPage2[74], 150);
        TextDrawFont(MarketPage2[74], 1);
        TextDrawSetProportional(MarketPage2[74], 1);

        MarketPage2[75] = TextDrawCreate(170.000, 253.000, "_");
        TextDrawTextSize(MarketPage2[75], 90.000, 90.000);
        TextDrawAlignment(MarketPage2[75], 1);
        TextDrawColor(MarketPage2[75], -1);
        TextDrawSetShadow(MarketPage2[75], 0);
        TextDrawSetOutline(MarketPage2[75], 0);
        TextDrawBackgroundColor(MarketPage2[75], 66048);
        TextDrawFont(MarketPage2[75], 5);
        TextDrawSetProportional(MarketPage2[75], 0);
        TextDrawSetPreviewModel(MarketPage2[75], 19468);
        TextDrawSetPreviewRot(MarketPage2[75], 0.000, 0.000, 0.000, 2.000);
        TextDrawSetPreviewVehCol(MarketPage2[75], 0, 0);

        MarketPage2[76] = TextDrawCreate(233.000, 269.000, "x1");
        TextDrawLetterSize(MarketPage2[76], 0.170, 0.999);
        TextDrawAlignment(MarketPage2[76], 1);
        TextDrawColor(MarketPage2[76], -1);
        TextDrawSetShadow(MarketPage2[76], 0);
        TextDrawSetOutline(MarketPage2[76], 0);
        TextDrawBackgroundColor(MarketPage2[76], 150);
        TextDrawFont(MarketPage2[76], 1);
        TextDrawSetProportional(MarketPage2[76], 1);

}

ShowMarket1(playerid)
{
    	for(new x; x < 76; x++)
    {
    	TextDrawShowForPlayer(playerid, MarketPage1[x]);
	}
        //SelectTextDraw(playerid, 0xff91a4cc);
}

HideMarket1(playerid)
{
    	for(new x; x < 76; x++)
    {
    	TextDrawHideForPlayer(playerid, MarketPage1[x]);
	}
        CancelSelectTextDraw(playerid);
}

ShowMarket2(playerid)
{
    	for(new x; x < 77; x++)
    {
    	TextDrawShowForPlayer(playerid, MarketPage2[x]);
	}
        SelectTextDraw(playerid, 0xff91a4cc);
}

HideMarket2(playerid)
{
    	for(new x; x < 77; x++)
    {
    	TextDrawHideForPlayer(playerid, MarketPage2[x]);
	}
        CancelSelectTextDraw(playerid);
}