new Text:RadialTD[34],
    Text:RadialTD2[24],
	Text:RadialFashionTD[28],
	Text:RadialVehTD[24],
	Text:RadialCardTD[26];

CreateRadialTD()
{
	RadialTD[0] = TextDrawCreate(313.000, 183.000, "Preview_Model");
	TextDrawLetterSize(RadialTD[0], 0.600, 2.000);
	TextDrawTextSize(RadialTD[0], 38.000, 45.500);
	TextDrawAlignment(RadialTD[0], 1);
	TextDrawColor(RadialTD[0], 54);
	TextDrawSetShadow(RadialTD[0], 0);
	TextDrawSetOutline(RadialTD[0], 0);
	TextDrawBackgroundColor(RadialTD[0], 0);
	TextDrawFont(RadialTD[0], 5);
	TextDrawSetProportional(RadialTD[0], 1);
	TextDrawSetPreviewModel(RadialTD[0], 19819);
	TextDrawSetPreviewRot(RadialTD[0], -78.000, 0.000, 59.000, 1.000);
	TextDrawSetPreviewVehCol(RadialTD[0], 1, 1);
	TextDrawSetSelectable(RadialTD[0], 1);

	RadialTD[1] = TextDrawCreate(303.000, 226.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD[1], 25.000, 29.000);
	TextDrawAlignment(RadialTD[1], 1);
	TextDrawColor(RadialTD[1], 45);
	TextDrawSetShadow(RadialTD[1], 0);
	TextDrawSetOutline(RadialTD[1], 0);
	TextDrawBackgroundColor(RadialTD[1], 255);
	TextDrawFont(RadialTD[1], 4);
	TextDrawSetProportional(RadialTD[1], 1);
	TextDrawSetSelectable(RadialTD[1], 1);

	RadialTD[2] = TextDrawCreate(278.000, 183.000, "Preview_Model");
	TextDrawLetterSize(RadialTD[2], 0.600, 2.000);
	TextDrawTextSize(RadialTD[2], 38.000, 45.500);
	TextDrawAlignment(RadialTD[2], 1);
	TextDrawColor(RadialTD[2], 54);
	TextDrawSetShadow(RadialTD[2], 0);
	TextDrawSetOutline(RadialTD[2], 0);
	TextDrawBackgroundColor(RadialTD[2], 0);
	TextDrawFont(RadialTD[2], 5);
	TextDrawSetProportional(RadialTD[2], 1);
	TextDrawSetPreviewModel(RadialTD[2], 19819);
	TextDrawSetPreviewRot(RadialTD[2], -78.000, 0.000, 59.000, 1.000);
	TextDrawSetPreviewVehCol(RadialTD[2], 1, 1);
	TextDrawSetSelectable(RadialTD[2], 1);

	RadialTD[3] = TextDrawCreate(264.000, 215.000, "Preview_Model");
	TextDrawLetterSize(RadialTD[3], 0.600, 2.000);
	TextDrawTextSize(RadialTD[3], 38.000, 45.500);
	TextDrawAlignment(RadialTD[3], 1);
	TextDrawColor(RadialTD[3], 54);
	TextDrawSetShadow(RadialTD[3], 0);
	TextDrawSetOutline(RadialTD[3], 0);
	TextDrawBackgroundColor(RadialTD[3], 0);
	TextDrawFont(RadialTD[3], 5);
	TextDrawSetProportional(RadialTD[3], 1);
	TextDrawSetPreviewModel(RadialTD[3], 19819);
	TextDrawSetPreviewRot(RadialTD[3], -78.000, 0.000, 59.000, 1.000);
	TextDrawSetPreviewVehCol(RadialTD[3], 1, 1);
	TextDrawSetSelectable(RadialTD[3], 1);

	RadialTD[4] = TextDrawCreate(326.000, 215.000, "Preview_Model");
	TextDrawLetterSize(RadialTD[4], 0.600, 2.000);
	TextDrawTextSize(RadialTD[4], 38.000, 45.500);
	TextDrawAlignment(RadialTD[4], 1);
	TextDrawColor(RadialTD[4], 54);
	TextDrawSetShadow(RadialTD[4], 0);
	TextDrawSetOutline(RadialTD[4], 0);
	TextDrawBackgroundColor(RadialTD[4], 0);
	TextDrawFont(RadialTD[4], 5);
	TextDrawSetProportional(RadialTD[4], 1);
	TextDrawSetPreviewModel(RadialTD[4], 19819);
	TextDrawSetPreviewRot(RadialTD[4], -78.000, 0.000, 59.000, 1.000);
	TextDrawSetPreviewVehCol(RadialTD[4], 1, 1);
	TextDrawSetSelectable(RadialTD[4], 1);

	RadialTD[5] = TextDrawCreate(278.000, 249.000, "Preview_Model");
	TextDrawLetterSize(RadialTD[5], 0.600, 2.000);
	TextDrawTextSize(RadialTD[5], 38.000, 45.500);
	TextDrawAlignment(RadialTD[5], 1);
	TextDrawColor(RadialTD[5], 54);
	TextDrawSetShadow(RadialTD[5], 0);
	TextDrawSetOutline(RadialTD[5], 0);
	TextDrawBackgroundColor(RadialTD[5], 0);
	TextDrawFont(RadialTD[5], 5);
	TextDrawSetProportional(RadialTD[5], 1);
	TextDrawSetPreviewModel(RadialTD[5], 19819);
	TextDrawSetPreviewRot(RadialTD[5], -78.000, 0.000, 59.000, 1.000);
	TextDrawSetPreviewVehCol(RadialTD[5], 1, 1);
	TextDrawSetSelectable(RadialTD[5], 1);

	RadialTD[6] = TextDrawCreate(313.000, 249.000, "Preview_Model");
	TextDrawLetterSize(RadialTD[6], 0.600, 2.000);
	TextDrawTextSize(RadialTD[6], 38.000, 45.500);
	TextDrawAlignment(RadialTD[6], 1);
	TextDrawColor(RadialTD[6], 54);
	TextDrawSetShadow(RadialTD[6], 0);
	TextDrawSetOutline(RadialTD[6], 0);
	TextDrawBackgroundColor(RadialTD[6], 0);
	TextDrawFont(RadialTD[6], 5);
	TextDrawSetProportional(RadialTD[6], 1);
	TextDrawSetPreviewModel(RadialTD[6], 19819);
	TextDrawSetPreviewRot(RadialTD[6], -78.000, 0.000, 59.000, 1.000);
	TextDrawSetPreviewVehCol(RadialTD[6], 1, 1);
	TextDrawSetSelectable(RadialTD[6], 1);

	RadialTD[7] = TextDrawCreate(312.000, 233.000, "X");
	TextDrawLetterSize(RadialTD[7], 0.300, 1.500);
	TextDrawAlignment(RadialTD[7], 1);
	TextDrawColor(RadialTD[7], -1);
	TextDrawSetShadow(RadialTD[7], 0);
	TextDrawSetOutline(RadialTD[7], 0);
	TextDrawBackgroundColor(RadialTD[7], 150);
	TextDrawFont(RadialTD[7], 1);
	TextDrawSetProportional(RadialTD[7], 1);

	RadialTD[8] = TextDrawCreate(344.000, 238.000, "/");
	TextDrawLetterSize(RadialTD[8], 0.519, 0.599);
	TextDrawAlignment(RadialTD[8], 1);
	TextDrawColor(RadialTD[8], -1);
	TextDrawSetShadow(RadialTD[8], 0);
	TextDrawSetOutline(RadialTD[8], 0);
	TextDrawBackgroundColor(RadialTD[8], 150);
	TextDrawFont(RadialTD[8], 1);
	TextDrawSetProportional(RadialTD[8], 1);

	RadialTD[9] = TextDrawCreate(340.000, 239.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD[9], 9.000, 3.000);
	TextDrawAlignment(RadialTD[9], 1);
	TextDrawColor(RadialTD[9], -1);
	TextDrawSetShadow(RadialTD[9], 0);
	TextDrawSetOutline(RadialTD[9], 0);
	TextDrawBackgroundColor(RadialTD[9], 255);
	TextDrawFont(RadialTD[9], 4);
	TextDrawSetProportional(RadialTD[9], 1);

	RadialTD[10] = TextDrawCreate(344.000, 241.000, "/");
	TextDrawLetterSize(RadialTD[10], 0.579, -0.400);
	TextDrawAlignment(RadialTD[10], 1);
	TextDrawColor(RadialTD[10], -1);
	TextDrawSetShadow(RadialTD[10], 0);
	TextDrawSetOutline(RadialTD[10], 0);
	TextDrawBackgroundColor(RadialTD[10], 150);
	TextDrawFont(RadialTD[10], 1);
	TextDrawSetProportional(RadialTD[10], 1);

	RadialTD[11] = TextDrawCreate(293.000, 216.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD[11], 8.000, -15.000);
	TextDrawAlignment(RadialTD[11], 1);
	TextDrawColor(RadialTD[11], -1);
	TextDrawSetShadow(RadialTD[11], 0);
	TextDrawSetOutline(RadialTD[11], 0);
	TextDrawBackgroundColor(RadialTD[11], 255);
	TextDrawFont(RadialTD[11], 4);
	TextDrawSetProportional(RadialTD[11], 1);

	RadialTD[12] = TextDrawCreate(294.000, 215.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD[12], 6.000, -13.000);
	TextDrawAlignment(RadialTD[12], 1);
	TextDrawColor(RadialTD[12], 1768516095);
	TextDrawSetShadow(RadialTD[12], 0);
	TextDrawSetOutline(RadialTD[12], 0);
	TextDrawBackgroundColor(RadialTD[12], 255);
	TextDrawFont(RadialTD[12], 4);
	TextDrawSetProportional(RadialTD[12], 1);

	RadialTD[13] = TextDrawCreate(296.000, 212.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD[13], 2.000, 3.000);
	TextDrawAlignment(RadialTD[13], 1);
	TextDrawColor(RadialTD[13], -1);
	TextDrawSetShadow(RadialTD[13], 0);
	TextDrawSetOutline(RadialTD[13], 0);
	TextDrawBackgroundColor(RadialTD[13], 255);
	TextDrawFont(RadialTD[13], 4);
	TextDrawSetProportional(RadialTD[13], 1);

	RadialTD[14] = TextDrawCreate(326.000, 214.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD[14], 12.000, -9.000);
	TextDrawAlignment(RadialTD[14], 1);
	TextDrawColor(RadialTD[14], -1);
	TextDrawSetShadow(RadialTD[14], 0);
	TextDrawSetOutline(RadialTD[14], 0);
	TextDrawBackgroundColor(RadialTD[14], 255);
	TextDrawFont(RadialTD[14], 4);
	TextDrawSetProportional(RadialTD[14], 1);

	RadialTD[15] = TextDrawCreate(322.000, 210.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD[15], 20.000, 8.000);
	TextDrawAlignment(RadialTD[15], 1);
	TextDrawColor(RadialTD[15], -1);
	TextDrawSetShadow(RadialTD[15], 0);
	TextDrawSetOutline(RadialTD[15], 0);
	TextDrawBackgroundColor(RadialTD[15], 255);
	TextDrawFont(RadialTD[15], 4);
	TextDrawSetProportional(RadialTD[15], 1);

	RadialTD[16] = TextDrawCreate(324.000, 199.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD[16], 16.000, 12.000);
	TextDrawAlignment(RadialTD[16], 1);
	TextDrawColor(RadialTD[16], -1);
	TextDrawSetShadow(RadialTD[16], 0);
	TextDrawSetOutline(RadialTD[16], 0);
	TextDrawBackgroundColor(RadialTD[16], 255);
	TextDrawFont(RadialTD[16], 4);
	TextDrawSetProportional(RadialTD[16], 1);

	RadialTD[17] = TextDrawCreate(326.000, 207.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD[17], 12.000, -1.000);
	TextDrawAlignment(RadialTD[17], 1);
	TextDrawColor(RadialTD[17], -2139062017);
	TextDrawSetShadow(RadialTD[17], 0);
	TextDrawSetOutline(RadialTD[17], 0);
	TextDrawBackgroundColor(RadialTD[17], 255);
	TextDrawFont(RadialTD[17], 4);
	TextDrawSetProportional(RadialTD[17], 1);

	RadialTD[18] = TextDrawCreate(330.000, 207.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD[18], 4.000, 2.000);
	TextDrawAlignment(RadialTD[18], 1);
	TextDrawColor(RadialTD[18], -2139062017);
	TextDrawSetShadow(RadialTD[18], 0);
	TextDrawSetOutline(RadialTD[18], 0);
	TextDrawBackgroundColor(RadialTD[18], 255);
	TextDrawFont(RadialTD[18], 4);
	TextDrawSetProportional(RadialTD[18], 1);

	RadialTD[19] = TextDrawCreate(326.000, 214.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD[19], 12.000, 1.000);
	TextDrawAlignment(RadialTD[19], 1);
	TextDrawColor(RadialTD[19], -2139062017);
	TextDrawSetShadow(RadialTD[19], 0);
	TextDrawSetOutline(RadialTD[19], 0);
	TextDrawBackgroundColor(RadialTD[19], 255);
	TextDrawFont(RadialTD[19], 4);
	TextDrawSetProportional(RadialTD[19], 1);

	RadialTD[20] = TextDrawCreate(277.000, 247.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD[20], 8.000, -13.000);
	TextDrawAlignment(RadialTD[20], 1);
	TextDrawColor(RadialTD[20], -2139062017);
	TextDrawSetShadow(RadialTD[20], 0);
	TextDrawSetOutline(RadialTD[20], 0);
	TextDrawBackgroundColor(RadialTD[20], 255);
	TextDrawFont(RadialTD[20], 4);
	TextDrawSetProportional(RadialTD[20], 1);

	RadialTD[21] = TextDrawCreate(280.000, 249.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD[21], 8.000, -13.000);
	TextDrawAlignment(RadialTD[21], 1);
	TextDrawColor(RadialTD[21], -1);
	TextDrawSetShadow(RadialTD[21], 0);
	TextDrawSetOutline(RadialTD[21], 0);
	TextDrawBackgroundColor(RadialTD[21], 255);
	TextDrawFont(RadialTD[21], 4);
	TextDrawSetProportional(RadialTD[21], 1);

	RadialTD[22] = TextDrawCreate(282.000, 236.000, "$");
	TextDrawLetterSize(RadialTD[22], 0.200, 0.799);
	TextDrawAlignment(RadialTD[22], 1);
	TextDrawColor(RadialTD[22], -2139062017);
	TextDrawSetShadow(RadialTD[22], 0);
	TextDrawSetOutline(RadialTD[22], 0);
	TextDrawBackgroundColor(RadialTD[22], 150);
	TextDrawFont(RadialTD[22], 1);
	TextDrawSetProportional(RadialTD[22], 1);

	RadialTD[23] = TextDrawCreate(289.000, 268.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD[23], 10.000, 11.000);
	TextDrawAlignment(RadialTD[23], 1);
	TextDrawColor(RadialTD[23], -1);
	TextDrawSetShadow(RadialTD[23], 0);
	TextDrawSetOutline(RadialTD[23], 0);
	TextDrawBackgroundColor(RadialTD[23], 255);
	TextDrawFont(RadialTD[23], 4);
	TextDrawSetProportional(RadialTD[23], 1);

	RadialTD[24] = TextDrawCreate(296.000, 268.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD[24], 10.000, 11.000);
	TextDrawAlignment(RadialTD[24], 1);
	TextDrawColor(RadialTD[24], -1);
	TextDrawSetShadow(RadialTD[24], 0);
	TextDrawSetOutline(RadialTD[24], 0);
	TextDrawBackgroundColor(RadialTD[24], 255);
	TextDrawFont(RadialTD[24], 4);
	TextDrawSetProportional(RadialTD[24], 1);

	RadialTD[25] = TextDrawCreate(297.000, 269.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD[25], 8.000, 9.000);
	TextDrawAlignment(RadialTD[25], 1);
	TextDrawColor(RadialTD[25], -2139062017);
	TextDrawSetShadow(RadialTD[25], 0);
	TextDrawSetOutline(RadialTD[25], 0);
	TextDrawBackgroundColor(RadialTD[25], 255);
	TextDrawFont(RadialTD[25], 4);
	TextDrawSetProportional(RadialTD[25], 1);

	RadialTD[26] = TextDrawCreate(290.000, 269.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD[26], 8.000, 9.000);
	TextDrawAlignment(RadialTD[26], 1);
	TextDrawColor(RadialTD[26], -2139062017);
	TextDrawSetShadow(RadialTD[26], 0);
	TextDrawSetOutline(RadialTD[26], 0);
	TextDrawBackgroundColor(RadialTD[26], 255);
	TextDrawFont(RadialTD[26], 4);
	TextDrawSetProportional(RadialTD[26], 1);

	RadialTD[27] = TextDrawCreate(302.000, 274.000, "/");
	TextDrawLetterSize(RadialTD[27], 0.170, 0.799);
	TextDrawAlignment(RadialTD[27], 1);
	TextDrawColor(RadialTD[27], -1);
	TextDrawSetShadow(RadialTD[27], 0);
	TextDrawSetOutline(RadialTD[27], 0);
	TextDrawBackgroundColor(RadialTD[27], 150);
	TextDrawFont(RadialTD[27], 1);
	TextDrawSetProportional(RadialTD[27], 1);

	RadialTD[28] = TextDrawCreate(291.000, 283.000, "/");
	TextDrawLetterSize(RadialTD[28], 0.180, -0.700);
	TextDrawAlignment(RadialTD[28], 1);
	TextDrawColor(RadialTD[28], -1);
	TextDrawSetShadow(RadialTD[28], 0);
	TextDrawSetOutline(RadialTD[28], 0);
	TextDrawBackgroundColor(RadialTD[28], 150);
	TextDrawFont(RadialTD[28], 1);
	TextDrawSetProportional(RadialTD[28], 1);

	RadialTD[29] = TextDrawCreate(297.000, 273.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD[29], 1.000, 2.000);
	TextDrawAlignment(RadialTD[29], 1);
	TextDrawColor(RadialTD[29], -1);
	TextDrawSetShadow(RadialTD[29], 0);
	TextDrawSetOutline(RadialTD[29], 0);
	TextDrawBackgroundColor(RadialTD[29], 255);
	TextDrawFont(RadialTD[29], 4);
	TextDrawSetProportional(RadialTD[29], 1);

	RadialTD[30] = TextDrawCreate(322.000, 265.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD[30], 20.000, 20.000);
	TextDrawAlignment(RadialTD[30], 1);
	TextDrawColor(RadialTD[30], -1);
	TextDrawSetShadow(RadialTD[30], 0);
	TextDrawSetOutline(RadialTD[30], 0);
	TextDrawBackgroundColor(RadialTD[30], 255);
	TextDrawFont(RadialTD[30], 4);
	TextDrawSetProportional(RadialTD[30], 1);

	RadialTD[31] = TextDrawCreate(327.000, 271.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD[31], 5.000, 6.000);
	TextDrawAlignment(RadialTD[31], 1);
	TextDrawColor(RadialTD[31], -2139062017);
	TextDrawSetShadow(RadialTD[31], 0);
	TextDrawSetOutline(RadialTD[31], 0);
	TextDrawBackgroundColor(RadialTD[31], 255);
	TextDrawFont(RadialTD[31], 4);
	TextDrawSetProportional(RadialTD[31], 1);

	RadialTD[32] = TextDrawCreate(332.000, 271.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD[32], 5.000, 6.000);
	TextDrawAlignment(RadialTD[32], 1);
	TextDrawColor(RadialTD[32], -2139062017);
	TextDrawSetShadow(RadialTD[32], 0);
	TextDrawSetOutline(RadialTD[32], 0);
	TextDrawBackgroundColor(RadialTD[32], 255);
	TextDrawFont(RadialTD[32], 4);
	TextDrawSetProportional(RadialTD[32], 1);

	RadialTD[33] = TextDrawCreate(326.000, 275.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD[33], 12.000, 8.000);
	TextDrawAlignment(RadialTD[33], 1);
	TextDrawColor(RadialTD[33], -2139062017);
	TextDrawSetShadow(RadialTD[33], 0);
	TextDrawSetOutline(RadialTD[33], 0);
	TextDrawBackgroundColor(RadialTD[33], 255);
	TextDrawFont(RadialTD[33], 4);
	TextDrawSetProportional(RadialTD[33], 1);

}

CreateRadialTD2()
{
	RadialTD2[0] = TextDrawCreate(326.000, 215.000, "Preview_Model");
	TextDrawLetterSize(RadialTD2[0], 0.600, 2.000);
	TextDrawTextSize(RadialTD2[0], 38.000, 45.500);
	TextDrawAlignment(RadialTD2[0], 1);
	TextDrawColor(RadialTD2[0], 54);
	TextDrawSetShadow(RadialTD2[0], 0);
	TextDrawSetOutline(RadialTD2[0], 0);
	TextDrawBackgroundColor(RadialTD2[0], 0);
	TextDrawFont(RadialTD2[0], 5);
	TextDrawSetProportional(RadialTD2[0], 1);
	TextDrawSetPreviewModel(RadialTD2[0], 19819);
	TextDrawSetPreviewRot(RadialTD2[0], -78.000, 0.000, 59.000, 1.000);
	TextDrawSetPreviewVehCol(RadialTD2[0], 1, 1);
	TextDrawSetSelectable(RadialTD2[0], 1);

	RadialTD2[1] = TextDrawCreate(345.000, 239.000, "/");
	TextDrawLetterSize(RadialTD2[1], -0.589, 0.599);
	TextDrawAlignment(RadialTD2[1], 1);
	TextDrawColor(RadialTD2[1], -1);
	TextDrawSetShadow(RadialTD2[1], 0);
	TextDrawSetOutline(RadialTD2[1], 0);
	TextDrawBackgroundColor(RadialTD2[1], 150);
	TextDrawFont(RadialTD2[1], 1);
	TextDrawSetProportional(RadialTD2[1], 1);

	RadialTD2[2] = TextDrawCreate(340.000, 239.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD2[2], 9.000, 3.000);
	TextDrawAlignment(RadialTD2[2], 1);
	TextDrawColor(RadialTD2[2], -1);
	TextDrawSetShadow(RadialTD2[2], 0);
	TextDrawSetOutline(RadialTD2[2], 0);
	TextDrawBackgroundColor(RadialTD2[2], 255);
	TextDrawFont(RadialTD2[2], 4);
	TextDrawSetProportional(RadialTD2[2], 1);

	RadialTD2[3] = TextDrawCreate(337.000, 235.000, "/");
	TextDrawLetterSize(RadialTD2[3], 0.579, 0.599);
	TextDrawAlignment(RadialTD2[3], 1);
	TextDrawColor(RadialTD2[3], -1);
	TextDrawSetShadow(RadialTD2[3], 0);
	TextDrawSetOutline(RadialTD2[3], 0);
	TextDrawBackgroundColor(RadialTD2[3], 150);
	TextDrawFont(RadialTD2[3], 1);
	TextDrawSetProportional(RadialTD2[3], 1);

	RadialTD2[4] = TextDrawCreate(357.000, 215.000, "Preview_Model");
	TextDrawLetterSize(RadialTD2[4], 0.600, 2.000);
	TextDrawTextSize(RadialTD2[4], 38.000, 45.500);
	TextDrawAlignment(RadialTD2[4], 1);
	TextDrawColor(RadialTD2[4], 54);
	TextDrawSetShadow(RadialTD2[4], 0);
	TextDrawSetOutline(RadialTD2[4], 0);
	TextDrawBackgroundColor(RadialTD2[4], 0);
	TextDrawFont(RadialTD2[4], 5);
	TextDrawSetProportional(RadialTD2[4], 1);
	TextDrawSetPreviewModel(RadialTD2[4], 19819);
	TextDrawSetPreviewRot(RadialTD2[4], -78.000, 0.000, 59.000, 1.000);
	TextDrawSetPreviewVehCol(RadialTD2[4], 1, 1);
	TextDrawSetSelectable(RadialTD2[4], 1);

	RadialTD2[5] = TextDrawCreate(387.000, 215.000, "Preview_Model");
	TextDrawLetterSize(RadialTD2[5], 0.600, 2.000);
	TextDrawTextSize(RadialTD2[5], 38.000, 45.500);
	TextDrawAlignment(RadialTD2[5], 1);
	TextDrawColor(RadialTD2[5], 54);
	TextDrawSetShadow(RadialTD2[5], 0);
	TextDrawSetOutline(RadialTD2[5], 0);
	TextDrawBackgroundColor(RadialTD2[5], 0);
	TextDrawFont(RadialTD2[5], 5);
	TextDrawSetProportional(RadialTD2[5], 1);
	TextDrawSetPreviewModel(RadialTD2[5], 19819);
	TextDrawSetPreviewRot(RadialTD2[5], -78.000, 0.000, 59.000, 1.000);
	TextDrawSetPreviewVehCol(RadialTD2[5], 1, 1);
	TextDrawSetSelectable(RadialTD2[5], 1);

	RadialTD2[6] = TextDrawCreate(372.000, 184.000, "Preview_Model");
	TextDrawLetterSize(RadialTD2[6], 0.600, 2.000);
	TextDrawTextSize(RadialTD2[6], 38.000, 45.500);
	TextDrawAlignment(RadialTD2[6], 1);
	TextDrawColor(RadialTD2[6], 54);
	TextDrawSetShadow(RadialTD2[6], 0);
	TextDrawSetOutline(RadialTD2[6], 0);
	TextDrawBackgroundColor(RadialTD2[6], 0);
	TextDrawFont(RadialTD2[6], 5);
	TextDrawSetProportional(RadialTD2[6], 1);
	TextDrawSetPreviewModel(RadialTD2[6], 19819);
	TextDrawSetPreviewRot(RadialTD2[6], -78.000, 0.000, 59.000, 1.000);
	TextDrawSetPreviewVehCol(RadialTD2[6], 1, 1);
	TextDrawSetSelectable(RadialTD2[6], 1);

	RadialTD2[7] = TextDrawCreate(370.000, 247.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD2[7], 8.000, -13.000);
	TextDrawAlignment(RadialTD2[7], 1);
	TextDrawColor(RadialTD2[7], -2139062017);
	TextDrawSetShadow(RadialTD2[7], 0);
	TextDrawSetOutline(RadialTD2[7], 0);
	TextDrawBackgroundColor(RadialTD2[7], 255);
	TextDrawFont(RadialTD2[7], 4);
	TextDrawSetProportional(RadialTD2[7], 1);

	RadialTD2[8] = TextDrawCreate(372.000, 249.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD2[8], 8.000, -13.000);
	TextDrawAlignment(RadialTD2[8], 1);
	TextDrawColor(RadialTD2[8], -1);
	TextDrawSetShadow(RadialTD2[8], 0);
	TextDrawSetOutline(RadialTD2[8], 0);
	TextDrawBackgroundColor(RadialTD2[8], 255);
	TextDrawFont(RadialTD2[8], 4);
	TextDrawSetProportional(RadialTD2[8], 1);

	RadialTD2[9] = TextDrawCreate(373.000, 240.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD2[9], 4.000, -2.000);
	TextDrawAlignment(RadialTD2[9], 1);
	TextDrawColor(RadialTD2[9], -2139062017);
	TextDrawSetShadow(RadialTD2[9], 0);
	TextDrawSetOutline(RadialTD2[9], 0);
	TextDrawBackgroundColor(RadialTD2[9], 255);
	TextDrawFont(RadialTD2[9], 4);
	TextDrawSetProportional(RadialTD2[9], 1);

	RadialTD2[10] = TextDrawCreate(375.000, 244.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD2[10], 5.000, -1.000);
	TextDrawAlignment(RadialTD2[10], 1);
	TextDrawColor(RadialTD2[10], -2139062017);
	TextDrawSetShadow(RadialTD2[10], 0);
	TextDrawSetOutline(RadialTD2[10], 0);
	TextDrawBackgroundColor(RadialTD2[10], 255);
	TextDrawFont(RadialTD2[10], 4);
	TextDrawSetProportional(RadialTD2[10], 1);

	RadialTD2[11] = TextDrawCreate(374.000, 246.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD2[11], 6.000, -1.000);
	TextDrawAlignment(RadialTD2[11], 1);
	TextDrawColor(RadialTD2[11], -2139062017);
	TextDrawSetShadow(RadialTD2[11], 0);
	TextDrawSetOutline(RadialTD2[11], 0);
	TextDrawBackgroundColor(RadialTD2[11], 255);
	TextDrawFont(RadialTD2[11], 4);
	TextDrawSetProportional(RadialTD2[11], 1);

	RadialTD2[12] = TextDrawCreate(400.000, 246.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD2[12], 11.000, -9.000);
	TextDrawAlignment(RadialTD2[12], 1);
	TextDrawColor(RadialTD2[12], -1);
	TextDrawSetShadow(RadialTD2[12], 0);
	TextDrawSetOutline(RadialTD2[12], 0);
	TextDrawBackgroundColor(RadialTD2[12], 255);
	TextDrawFont(RadialTD2[12], 4);
	TextDrawSetProportional(RadialTD2[12], 1);

	RadialTD2[13] = TextDrawCreate(401.000, 240.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD2[13], 4.000, -2.000);
	TextDrawAlignment(RadialTD2[13], 1);
	TextDrawColor(RadialTD2[13], -2139062017);
	TextDrawSetShadow(RadialTD2[13], 0);
	TextDrawSetOutline(RadialTD2[13], 0);
	TextDrawBackgroundColor(RadialTD2[13], 255);
	TextDrawFont(RadialTD2[13], 4);
	TextDrawSetProportional(RadialTD2[13], 1);

	RadialTD2[14] = TextDrawCreate(404.000, 243.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD2[14], 6.000, -1.000);
	TextDrawAlignment(RadialTD2[14], 1);
	TextDrawColor(RadialTD2[14], -2139062017);
	TextDrawSetShadow(RadialTD2[14], 0);
	TextDrawSetOutline(RadialTD2[14], 0);
	TextDrawBackgroundColor(RadialTD2[14], 255);
	TextDrawFont(RadialTD2[14], 4);
	TextDrawSetProportional(RadialTD2[14], 1);

	RadialTD2[15] = TextDrawCreate(386.000, 215.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD2[15], 11.000, -6.000);
	TextDrawAlignment(RadialTD2[15], 1);
	TextDrawColor(RadialTD2[15], -1);
	TextDrawSetShadow(RadialTD2[15], 0);
	TextDrawSetOutline(RadialTD2[15], 0);
	TextDrawBackgroundColor(RadialTD2[15], 255);
	TextDrawFont(RadialTD2[15], 4);
	TextDrawSetProportional(RadialTD2[15], 1);

	RadialTD2[16] = TextDrawCreate(383.000, 203.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD2[16], 17.000, 12.000);
	TextDrawAlignment(RadialTD2[16], 1);
	TextDrawColor(RadialTD2[16], -1);
	TextDrawSetShadow(RadialTD2[16], 0);
	TextDrawSetOutline(RadialTD2[16], 0);
	TextDrawBackgroundColor(RadialTD2[16], 255);
	TextDrawFont(RadialTD2[16], 4);
	TextDrawSetProportional(RadialTD2[16], 1);

	RadialTD2[17] = TextDrawCreate(391.000, 213.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD2[17], -5.000, 5.000);
	TextDrawAlignment(RadialTD2[17], 1);
	TextDrawColor(RadialTD2[17], -1);
	TextDrawSetShadow(RadialTD2[17], 0);
	TextDrawSetOutline(RadialTD2[17], 0);
	TextDrawBackgroundColor(RadialTD2[17], 255);
	TextDrawFont(RadialTD2[17], 4);
	TextDrawSetProportional(RadialTD2[17], 1);

	RadialTD2[18] = TextDrawCreate(397.000, 213.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD2[18], -5.000, 5.000);
	TextDrawAlignment(RadialTD2[18], 1);
	TextDrawColor(RadialTD2[18], -1);
	TextDrawSetShadow(RadialTD2[18], 0);
	TextDrawSetOutline(RadialTD2[18], 0);
	TextDrawBackgroundColor(RadialTD2[18], 255);
	TextDrawFont(RadialTD2[18], 4);
	TextDrawSetProportional(RadialTD2[18], 1);

	RadialTD2[19] = TextDrawCreate(391.000, 213.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD2[19], -4.000, 5.000);
	TextDrawAlignment(RadialTD2[19], 1);
	TextDrawColor(RadialTD2[19], -2139062017);
	TextDrawSetShadow(RadialTD2[19], 0);
	TextDrawSetOutline(RadialTD2[19], 0);
	TextDrawBackgroundColor(RadialTD2[19], 255);
	TextDrawFont(RadialTD2[19], 4);
	TextDrawSetProportional(RadialTD2[19], 1);

	RadialTD2[20] = TextDrawCreate(397.000, 213.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialTD2[20], -4.000, 5.000);
	TextDrawAlignment(RadialTD2[20], 1);
	TextDrawColor(RadialTD2[20], -2139062017);
	TextDrawSetShadow(RadialTD2[20], 0);
	TextDrawSetOutline(RadialTD2[20], 0);
	TextDrawBackgroundColor(RadialTD2[20], 255);
	TextDrawFont(RadialTD2[20], 4);
	TextDrawSetProportional(RadialTD2[20], 1);

	RadialTD2[21] = TextDrawCreate(395.000, 212.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD2[21], 2.000, -3.000);
	TextDrawAlignment(RadialTD2[21], 1);
	TextDrawColor(RadialTD2[21], -2139062017);
	TextDrawSetShadow(RadialTD2[21], 0);
	TextDrawSetOutline(RadialTD2[21], 0);
	TextDrawBackgroundColor(RadialTD2[21], 255);
	TextDrawFont(RadialTD2[21], 4);
	TextDrawSetProportional(RadialTD2[21], 1);

	RadialTD2[22] = TextDrawCreate(388.000, 210.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD2[22], 6.000, -3.000);
	TextDrawAlignment(RadialTD2[22], 1);
	TextDrawColor(RadialTD2[22], -2139062017);
	TextDrawSetShadow(RadialTD2[22], 0);
	TextDrawSetOutline(RadialTD2[22], 0);
	TextDrawBackgroundColor(RadialTD2[22], 255);
	TextDrawFont(RadialTD2[22], 4);
	TextDrawSetProportional(RadialTD2[22], 1);

	RadialTD2[23] = TextDrawCreate(391.000, 210.000, "LD_SPAC:white");
	TextDrawTextSize(RadialTD2[23], 1.000, -3.000);
	TextDrawAlignment(RadialTD2[23], 1);
	TextDrawColor(RadialTD2[23], -1);
	TextDrawSetShadow(RadialTD2[23], 0);
	TextDrawSetOutline(RadialTD2[23], 0);
	TextDrawBackgroundColor(RadialTD2[23], 255);
	TextDrawFont(RadialTD2[23], 4);
	TextDrawSetProportional(RadialTD2[23], 1);

}

CreateRadialFashionTD()
{
	RadialFashionTD[23] = TextDrawCreate(96.000, 194.000, "LD_BUM:blkdot"); //helmet
	TextDrawTextSize(RadialFashionTD[23], 34.000, 35.000);
	TextDrawAlignment(RadialFashionTD[23], 1);
	TextDrawColor(RadialFashionTD[23], 0x00000066);
	TextDrawSetShadow(RadialFashionTD[23], 0);
	TextDrawSetOutline(RadialFashionTD[23], 0);
	TextDrawBackgroundColor(RadialFashionTD[23], 255);
	TextDrawFont(RadialFashionTD[23], 4);
	TextDrawSetProportional(RadialFashionTD[23], 1);
	TextDrawSetSelectable(RadialFashionTD[23], 1);

	RadialFashionTD[24] = TextDrawCreate(141.000, 194.000, "LD_BUM:blkdot"); //kacamata
	TextDrawTextSize(RadialFashionTD[24], 34.000, 35.000);
	TextDrawAlignment(RadialFashionTD[24], 1);
	TextDrawColor(RadialFashionTD[24], 0x00000066);
	TextDrawSetShadow(RadialFashionTD[24], 0);
	TextDrawSetOutline(RadialFashionTD[24], 0);
	TextDrawBackgroundColor(RadialFashionTD[24], 255);
	TextDrawFont(RadialFashionTD[24], 4);
	TextDrawSetProportional(RadialFashionTD[24], 1);
	TextDrawSetSelectable(RadialFashionTD[24], 1);

	RadialFashionTD[25] = TextDrawCreate(186.000, 194.000, "LD_BUM:blkdot"); //aksesoris
	TextDrawTextSize(RadialFashionTD[25], 34.000, 35.000);
	TextDrawAlignment(RadialFashionTD[25], 1);
	TextDrawColor(RadialFashionTD[25], 0x00000066);
	TextDrawSetShadow(RadialFashionTD[25], 0);
	TextDrawSetOutline(RadialFashionTD[25], 0);
	TextDrawBackgroundColor(RadialFashionTD[25], 255);
	TextDrawFont(RadialFashionTD[25], 4);
	TextDrawSetProportional(RadialFashionTD[25], 1);
	TextDrawSetSelectable(RadialFashionTD[25], 1);

	RadialFashionTD[26] = TextDrawCreate(232.000, 194.000, "LD_BUM:blkdot"); //koper
	TextDrawTextSize(RadialFashionTD[26], 34.000, 35.000);
	TextDrawAlignment(RadialFashionTD[26], 1);
	TextDrawColor(RadialFashionTD[26], 0x00000066);
	TextDrawSetShadow(RadialFashionTD[26], 0);
	TextDrawSetOutline(RadialFashionTD[26], 0);
	TextDrawBackgroundColor(RadialFashionTD[26], 255);
	TextDrawFont(RadialFashionTD[26], 4);
	TextDrawSetProportional(RadialFashionTD[26], 1);
	TextDrawSetSelectable(RadialFashionTD[26], 1);

	RadialFashionTD[27] = TextDrawCreate(166.000, 238.000, "LD_BEAT:chit"); //CloseB
	TextDrawTextSize(RadialFashionTD[27], 30.000, 30.000);
	TextDrawAlignment(RadialFashionTD[27], 1);
	TextDrawColor(RadialFashionTD[27], 0x00000066);
	TextDrawSetShadow(RadialFashionTD[27], 0);
	TextDrawSetOutline(RadialFashionTD[27], 0);
	TextDrawBackgroundColor(RadialFashionTD[27], 255);
	TextDrawFont(RadialFashionTD[27], 4);
	TextDrawSetProportional(RadialFashionTD[27], 1);
	TextDrawSetSelectable(RadialFashionTD[27], 1);

	RadialFashionTD[0] = TextDrawCreate(177.000, 245.000, "X");
	TextDrawLetterSize(RadialFashionTD[0], 0.349, 1.590);
	TextDrawAlignment(RadialFashionTD[0], 1);
	TextDrawColor(RadialFashionTD[0], 0xffffffcc);
	TextDrawSetShadow(RadialFashionTD[0], 0);
	TextDrawSetOutline(RadialFashionTD[0], 0);
	TextDrawBackgroundColor(RadialFashionTD[0], 150);
	TextDrawFont(RadialFashionTD[0], 1);
	TextDrawSetProportional(RadialFashionTD[0], 1);
	
	RadialFashionTD[1] = TextDrawCreate(101.000, 196.000, "ld_beat:chit");
	TextDrawLetterSize(RadialFashionTD[1], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[1], 28.500, 29.000);
	TextDrawAlignment(RadialFashionTD[1], 1);
	TextDrawColor(RadialFashionTD[1], 0xffffffcc);
	TextDrawUseBox(RadialFashionTD[1], 1);
	TextDrawBoxColor(RadialFashionTD[1], 50);
	TextDrawSetShadow(RadialFashionTD[1], 0);
	TextDrawSetOutline(RadialFashionTD[1], 0);
	TextDrawBackgroundColor(RadialFashionTD[1], 255);
	TextDrawFont(RadialFashionTD[1], 4);

	RadialFashionTD[2] = TextDrawCreate(105.000, 206.000, "ld_dual:white");
	TextDrawLetterSize(RadialFashionTD[2], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[2], 8.000, 12.000);
	TextDrawAlignment(RadialFashionTD[2], 1);
	TextDrawColor(RadialFashionTD[2], 0xffffffcc);
	TextDrawUseBox(RadialFashionTD[2], 1);
	TextDrawBoxColor(RadialFashionTD[2], 50);
	TextDrawSetShadow(RadialFashionTD[2], 0);
	TextDrawSetOutline(RadialFashionTD[2], 0);
	TextDrawBackgroundColor(RadialFashionTD[2], 255);
	TextDrawFont(RadialFashionTD[2], 4);
	TextDrawSetProportional(RadialFashionTD[2], 1);

	RadialFashionTD[3] = TextDrawCreate(99.000, 203.000, "ld_beat:chit");
	TextDrawLetterSize(RadialFashionTD[3], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[3], 21.500, 7.000);
	TextDrawAlignment(RadialFashionTD[3], 1);
	TextDrawColor(RadialFashionTD[3], 0xffffffcc);
	TextDrawUseBox(RadialFashionTD[3], 1);
	TextDrawBoxColor(RadialFashionTD[3], 50);
	TextDrawSetShadow(RadialFashionTD[3], 0);
	TextDrawSetOutline(RadialFashionTD[3], 0);
	TextDrawBackgroundColor(RadialFashionTD[3], 255);
	TextDrawFont(RadialFashionTD[3], 4);
	TextDrawSetProportional(RadialFashionTD[3], 0);

	RadialFashionTD[4] = TextDrawCreate(106.000, 205.000, "/");
	TextDrawLetterSize(RadialFashionTD[4], 0.629, 1.500);
	TextDrawTextSize(RadialFashionTD[4], 400.000, 17.000);
	TextDrawAlignment(RadialFashionTD[4], 1);
	TextDrawColor(RadialFashionTD[4], -1061109505);
	TextDrawSetShadow(RadialFashionTD[4], 0);
	TextDrawSetOutline(RadialFashionTD[4], 0);
	TextDrawBackgroundColor(RadialFashionTD[4], 255);
	TextDrawFont(RadialFashionTD[4], 0);
	TextDrawSetProportional(RadialFashionTD[4], 1);

	RadialFashionTD[5] = TextDrawCreate(105.000, 208.000, "ld_dual:white");
	TextDrawLetterSize(RadialFashionTD[5], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[5], 5.500, 11.000);
	TextDrawAlignment(RadialFashionTD[5], 1);
	TextDrawColor(RadialFashionTD[5], 1296911871);
	TextDrawUseBox(RadialFashionTD[5], 1);
	TextDrawBoxColor(RadialFashionTD[5], 50);
	TextDrawSetShadow(RadialFashionTD[5], 0);
	TextDrawSetOutline(RadialFashionTD[5], 0);
	TextDrawBackgroundColor(RadialFashionTD[5], 255);
	TextDrawFont(RadialFashionTD[5], 4);
	TextDrawSetProportional(RadialFashionTD[5], 1);

	RadialFashionTD[6] = TextDrawCreate(105.000, 207.000, "ld_dual:white");
	TextDrawLetterSize(RadialFashionTD[6], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[6], 9.000, 2.500);
	TextDrawAlignment(RadialFashionTD[6], 1);
	TextDrawColor(RadialFashionTD[6], 0xffffffcc);
	TextDrawUseBox(RadialFashionTD[6], 1);
	TextDrawBoxColor(RadialFashionTD[6], 50);
	TextDrawSetShadow(RadialFashionTD[6], 0);
	TextDrawSetOutline(RadialFashionTD[6], 0);
	TextDrawBackgroundColor(RadialFashionTD[6], 255);
	TextDrawFont(RadialFashionTD[6], 4);
	TextDrawSetProportional(RadialFashionTD[6], 1);

	RadialFashionTD[7] = TextDrawCreate(143.000, 204.000, "ld_beat:chit");
	TextDrawLetterSize(RadialFashionTD[7], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[7], 16.500, 15.500);
	TextDrawAlignment(RadialFashionTD[7], 1);
	TextDrawColor(RadialFashionTD[7], 0xffffffcc);
	TextDrawUseBox(RadialFashionTD[7], 1);
	TextDrawBoxColor(RadialFashionTD[7], 50);
	TextDrawSetShadow(RadialFashionTD[7], 0);
	TextDrawSetOutline(RadialFashionTD[7], 0);
	TextDrawBackgroundColor(RadialFashionTD[7], 255);
	TextDrawFont(RadialFashionTD[7], 4);
	TextDrawSetProportional(RadialFashionTD[7], 0);

	RadialFashionTD[8] = TextDrawCreate(156.000, 204.000, "ld_beat:chit");
	TextDrawLetterSize(RadialFashionTD[8], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[8], 16.500, 15.500);
	TextDrawAlignment(RadialFashionTD[8], 1);
	TextDrawColor(RadialFashionTD[8], 0xffffffcc);
	TextDrawUseBox(RadialFashionTD[8], 1);
	TextDrawBoxColor(RadialFashionTD[8], 50);
	TextDrawSetShadow(RadialFashionTD[8], 0);
	TextDrawSetOutline(RadialFashionTD[8], 0);
	TextDrawBackgroundColor(RadialFashionTD[8], 255);
	TextDrawFont(RadialFashionTD[8], 4);
	TextDrawSetProportional(RadialFashionTD[8], 0);

	RadialFashionTD[9] = TextDrawCreate(153.000, 207.000, "ld_dual:white");
	TextDrawLetterSize(RadialFashionTD[9], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[9], 10.000, 1.500);
	TextDrawAlignment(RadialFashionTD[9], 1);
	TextDrawColor(RadialFashionTD[9], 0xffffffcc);
	TextDrawUseBox(RadialFashionTD[9], 1);
	TextDrawBoxColor(RadialFashionTD[9], 50);
	TextDrawSetShadow(RadialFashionTD[9], 0);
	TextDrawSetOutline(RadialFashionTD[9], 0);
	TextDrawBackgroundColor(RadialFashionTD[9], 255);
	TextDrawFont(RadialFashionTD[9], 4);
	TextDrawSetProportional(RadialFashionTD[9], 1);

	RadialFashionTD[10] = TextDrawCreate(155.000, 209.000, "ld_dual:white");
	TextDrawLetterSize(RadialFashionTD[10], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[10], 7.500, 1.500);
	TextDrawAlignment(RadialFashionTD[10], 1);
	TextDrawColor(RadialFashionTD[10], 0xffffffcc);
	TextDrawUseBox(RadialFashionTD[10], 1);
	TextDrawBoxColor(RadialFashionTD[10], 50);
	TextDrawSetShadow(RadialFashionTD[10], 0);
	TextDrawSetOutline(RadialFashionTD[10], 0);
	TextDrawBackgroundColor(RadialFashionTD[10], 255);
	TextDrawFont(RadialFashionTD[10], 4);
	TextDrawSetProportional(RadialFashionTD[10], 1);

	RadialFashionTD[11] = TextDrawCreate(145.000, 205.000, "ld_beat:chit");
	TextDrawLetterSize(RadialFashionTD[11], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[11], 13.000, 13.500);
	TextDrawAlignment(RadialFashionTD[11], 1);
	TextDrawColor(RadialFashionTD[11], -1094795521);
	TextDrawUseBox(RadialFashionTD[11], 1);
	TextDrawBoxColor(RadialFashionTD[11], 50);
	TextDrawSetShadow(RadialFashionTD[11], 0);
	TextDrawSetOutline(RadialFashionTD[11], 0);
	TextDrawBackgroundColor(RadialFashionTD[11], 255);
	TextDrawFont(RadialFashionTD[11], 4);
	TextDrawSetProportional(RadialFashionTD[12], 0);

	RadialFashionTD[12] = TextDrawCreate(158.000, 205.000, "ld_beat:chit");
	TextDrawLetterSize(RadialFashionTD[12], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[12], 13.000, 13.500);
	TextDrawAlignment(RadialFashionTD[12], 1);
	TextDrawColor(RadialFashionTD[12], -1094795521);
	TextDrawUseBox(RadialFashionTD[12], 1);
	TextDrawBoxColor(RadialFashionTD[12], 50);
	TextDrawSetShadow(RadialFashionTD[12], 0);
	TextDrawSetOutline(RadialFashionTD[12], 0);
	TextDrawBackgroundColor(RadialFashionTD[12], 255);
	TextDrawFont(RadialFashionTD[12], 4);
	TextDrawSetProportional(RadialFashionTD[12], 0);

	RadialFashionTD[13] = TextDrawCreate(201.000, 198.000, "ld_dual:white");
	TextDrawLetterSize(RadialFashionTD[13], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[13], 4.000, 28.000);
	TextDrawAlignment(RadialFashionTD[13], 1);
	TextDrawColor(RadialFashionTD[13], -1);
	TextDrawUseBox(RadialFashionTD[13], 1);
	TextDrawBoxColor(RadialFashionTD[13], 50);
	TextDrawSetShadow(RadialFashionTD[13], 0);
	TextDrawSetOutline(RadialFashionTD[13], 0);
	TextDrawBackgroundColor(RadialFashionTD[13], 255);
	TextDrawFont(RadialFashionTD[13], 4);
	TextDrawSetProportional(RadialFashionTD[13], 1);

	RadialFashionTD[14] = TextDrawCreate(198.000, 207.000, "ld_dual:white");
	TextDrawLetterSize(RadialFashionTD[14], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[14], 10.500, 11.500);
	TextDrawAlignment(RadialFashionTD[14], 1);
	TextDrawColor(RadialFashionTD[14], 1296911871);
	TextDrawUseBox(RadialFashionTD[14], 1);
	TextDrawBoxColor(RadialFashionTD[14], 50);
	TextDrawSetShadow(RadialFashionTD[14], 0);
	TextDrawSetOutline(RadialFashionTD[14], 0);
	TextDrawBackgroundColor(RadialFashionTD[14], 255);
	TextDrawFont(RadialFashionTD[14], 4);
	TextDrawSetProportional(RadialFashionTD[14], 1);

	RadialFashionTD[15] = TextDrawCreate(199.000, 209.000, "ld_dual:white");
	TextDrawLetterSize(RadialFashionTD[15], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[15], 8.500, 8.000);
	TextDrawAlignment(RadialFashionTD[15], 1);
	TextDrawColor(RadialFashionTD[15], -741092353);
	TextDrawUseBox(RadialFashionTD[15], 1);
	TextDrawBoxColor(RadialFashionTD[15], 50);
	TextDrawSetShadow(RadialFashionTD[15], 0);
	TextDrawSetOutline(RadialFashionTD[15], 0);
	TextDrawBackgroundColor(RadialFashionTD[15], 255);
	TextDrawFont(RadialFashionTD[15], 4);
	TextDrawSetProportional(RadialFashionTD[15], 1);

	RadialFashionTD[16] = TextDrawCreate(203.000, 210.000, "ld_dual:white");
	TextDrawLetterSize(RadialFashionTD[16], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[16], 1.000, 3.000);
	TextDrawAlignment(RadialFashionTD[16], 1);
	TextDrawColor(RadialFashionTD[16], 255);
	TextDrawUseBox(RadialFashionTD[16], 1);
	TextDrawBoxColor(RadialFashionTD[16], 50);
	TextDrawSetShadow(RadialFashionTD[16], 0);
	TextDrawSetOutline(RadialFashionTD[16], 0);
	TextDrawBackgroundColor(RadialFashionTD[16], 255);
	TextDrawFont(RadialFashionTD[16], 4);
	TextDrawSetProportional(RadialFashionTD[16], 1);

	RadialFashionTD[17] = TextDrawCreate(200.000, 213.000, "ld_dual:white");
	TextDrawLetterSize(RadialFashionTD[17], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[17], 4.000, 1.500);
	TextDrawAlignment(RadialFashionTD[17], 1);
	TextDrawColor(RadialFashionTD[17], 255);
	TextDrawUseBox(RadialFashionTD[17], 1);
	TextDrawBoxColor(RadialFashionTD[17], 50);
	TextDrawSetShadow(RadialFashionTD[17], 0);
	TextDrawSetOutline(RadialFashionTD[17], 0);
	TextDrawBackgroundColor(RadialFashionTD[17], 255);
	TextDrawFont(RadialFashionTD[17], 4);
	TextDrawSetProportional(RadialFashionTD[17], 1);

	RadialFashionTD[18] = TextDrawCreate(240.000, 205.000, "ld_dual:white");
	TextDrawLetterSize(RadialFashionTD[18], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[18], 19.000, 16.000);
	TextDrawAlignment(RadialFashionTD[18], 1);
	TextDrawColor(RadialFashionTD[18], 0xffffffcc);
	TextDrawUseBox(RadialFashionTD[18], 1);
	TextDrawBoxColor(RadialFashionTD[18], 50);
	TextDrawSetShadow(RadialFashionTD[18], 0);
	TextDrawSetOutline(RadialFashionTD[18], 0);
	TextDrawBackgroundColor(RadialFashionTD[18], 255);
	TextDrawFont(RadialFashionTD[18], 4);
	TextDrawSetProportional(RadialFashionTD[18], 1);

	RadialFashionTD[19] = TextDrawCreate(240.000, 208.000, "ld_dual:white");
	TextDrawLetterSize(RadialFashionTD[19], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[19], 19.000, 2.500);
	TextDrawAlignment(RadialFashionTD[19], 1);
	TextDrawColor(RadialFashionTD[19], 0x3f3f3f8c);
	TextDrawUseBox(RadialFashionTD[19], 1);
	TextDrawBoxColor(RadialFashionTD[19], 50);
	TextDrawSetShadow(RadialFashionTD[19], 0);
	TextDrawSetOutline(RadialFashionTD[19], 0);
	TextDrawBackgroundColor(RadialFashionTD[19], 255);
	TextDrawFont(RadialFashionTD[19], 4);
	TextDrawSetProportional(RadialFashionTD[19], 1);

	RadialFashionTD[20] = TextDrawCreate(246.000, 207.000, "ld_dual:white");
	TextDrawLetterSize(RadialFashionTD[20], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[20], 5.500, 5.000);
	TextDrawAlignment(RadialFashionTD[20], 1);
	TextDrawColor(RadialFashionTD[20], 0x3f3f3f8c);
	TextDrawUseBox(RadialFashionTD[20], 1);
	TextDrawBoxColor(RadialFashionTD[20], 50);
	TextDrawSetShadow(RadialFashionTD[20], 0);
	TextDrawSetOutline(RadialFashionTD[20], 0);
	TextDrawBackgroundColor(RadialFashionTD[20], 255);
	TextDrawFont(RadialFashionTD[20], 4);
	TextDrawSetProportional(RadialFashionTD[20], 1);

	RadialFashionTD[21] = TextDrawCreate(244.000, 201.000, "ld_dual:white");
	TextDrawLetterSize(RadialFashionTD[21], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[21], 10.000, 5.000);
	TextDrawAlignment(RadialFashionTD[21], 1);
	TextDrawColor(RadialFashionTD[21], 0xffffffcc);
	TextDrawUseBox(RadialFashionTD[21], 1);
	TextDrawBoxColor(RadialFashionTD[21], 50);
	TextDrawSetShadow(RadialFashionTD[21], 0);
	TextDrawSetOutline(RadialFashionTD[21], 0);
	TextDrawBackgroundColor(RadialFashionTD[21], 255);
	TextDrawFont(RadialFashionTD[21], 4);
	TextDrawSetProportional(RadialFashionTD[21], 1);

	RadialFashionTD[22] = TextDrawCreate(246.000, 202.000, "ld_dual:white");
	TextDrawLetterSize(RadialFashionTD[22], 0.600, 2.000);
	TextDrawTextSize(RadialFashionTD[22], 5.000, 2.500);
	TextDrawAlignment(RadialFashionTD[22], 1);
	TextDrawColor(RadialFashionTD[22], 0x3f3f3f8c);
	TextDrawUseBox(RadialFashionTD[22], 1);
	TextDrawBoxColor(RadialFashionTD[22], 50);
	TextDrawSetShadow(RadialFashionTD[22], 0);
	TextDrawSetOutline(RadialFashionTD[22], 0);
	TextDrawBackgroundColor(RadialFashionTD[22], 255);
	TextDrawFont(RadialFashionTD[22], 4);
	TextDrawSetProportional(RadialFashionTD[22], 1);
}

CreateRadialVehTD()
{
	RadialVehTD[0] = TextDrawCreate(250.000, 150.000, "_");
	TextDrawTextSize(RadialVehTD[0], 138.000, 161.000);
	TextDrawAlignment(RadialVehTD[0], 1);
	TextDrawColor(RadialVehTD[0], -1);
	TextDrawSetShadow(RadialVehTD[0], 0);
	TextDrawSetOutline(RadialVehTD[0], 0);
	TextDrawBackgroundColor(RadialVehTD[0], 0);
	TextDrawFont(RadialVehTD[0], 5);
	TextDrawSetProportional(RadialVehTD[0], 0);
	TextDrawSetPreviewModel(RadialVehTD[0], 561);
	TextDrawSetPreviewRot(RadialVehTD[0], -90.000, 0.000, 0.000, 1.000);
	TextDrawSetPreviewVehCol(RadialVehTD[0], 31, 0);

	RadialVehTD[1] = TextDrawCreate(316.000, 133.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialVehTD[1], 1.000, 39.000);
	TextDrawAlignment(RadialVehTD[1], 1);
	TextDrawColor(RadialVehTD[1], 255);
	TextDrawSetShadow(RadialVehTD[1], 0);
	TextDrawSetOutline(RadialVehTD[1], 0);
	TextDrawBackgroundColor(RadialVehTD[1], 255);
	TextDrawFont(RadialVehTD[1], 4);
	TextDrawSetProportional(RadialVehTD[1], 1);

	RadialVehTD[2] = TextDrawCreate(316.000, 133.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialVehTD[2], 27.000, 1.000);
	TextDrawAlignment(RadialVehTD[2], 1);
	TextDrawColor(RadialVehTD[2], 255);
	TextDrawSetShadow(RadialVehTD[2], 0);
	TextDrawSetOutline(RadialVehTD[2], 0);
	TextDrawBackgroundColor(RadialVehTD[2], 255);
	TextDrawFont(RadialVehTD[2], 4);
	TextDrawSetProportional(RadialVehTD[2], 1);

	RadialVehTD[3] = TextDrawCreate(338.000, 176.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialVehTD[3], 27.000, 1.000);
	TextDrawAlignment(RadialVehTD[3], 1);
	TextDrawColor(RadialVehTD[3], 255);
	TextDrawSetShadow(RadialVehTD[3], 0);
	TextDrawSetOutline(RadialVehTD[3], 0);
	TextDrawBackgroundColor(RadialVehTD[3], 255);
	TextDrawFont(RadialVehTD[3], 4);
	TextDrawSetProportional(RadialVehTD[3], 1);

	RadialVehTD[4] = TextDrawCreate(275.000, 175.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialVehTD[4], 33.000, 1.000);
	TextDrawAlignment(RadialVehTD[4], 1);
	TextDrawColor(RadialVehTD[4], 255);
	TextDrawSetShadow(RadialVehTD[4], 0);
	TextDrawSetOutline(RadialVehTD[4], 0);
	TextDrawBackgroundColor(RadialVehTD[4], 255);
	TextDrawFont(RadialVehTD[4], 4);
	TextDrawSetProportional(RadialVehTD[4], 1);

	RadialVehTD[5] = TextDrawCreate(265.000, 235.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialVehTD[5], 33.000, 1.000);
	TextDrawAlignment(RadialVehTD[5], 1);
	TextDrawColor(RadialVehTD[5], 255);
	TextDrawSetShadow(RadialVehTD[5], 0);
	TextDrawSetOutline(RadialVehTD[5], 0);
	TextDrawBackgroundColor(RadialVehTD[5], 255);
	TextDrawFont(RadialVehTD[5], 4);
	TextDrawSetProportional(RadialVehTD[5], 1);

	RadialVehTD[6] = TextDrawCreate(318.000, 290.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialVehTD[6], 1.000, 39.000);
	TextDrawAlignment(RadialVehTD[6], 1);
	TextDrawColor(RadialVehTD[6], 255);
	TextDrawSetShadow(RadialVehTD[6], 0);
	TextDrawSetOutline(RadialVehTD[6], 0);
	TextDrawBackgroundColor(RadialVehTD[6], 255);
	TextDrawFont(RadialVehTD[6], 4);
	TextDrawSetProportional(RadialVehTD[6], 1);

	RadialVehTD[7] = TextDrawCreate(329.000, 288.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialVehTD[7], 1.000, 34.000);
	TextDrawAlignment(RadialVehTD[7], 1);
	TextDrawColor(RadialVehTD[7], 255);
	TextDrawSetShadow(RadialVehTD[7], 0);
	TextDrawSetOutline(RadialVehTD[7], 0);
	TextDrawBackgroundColor(RadialVehTD[7], 255);
	TextDrawFont(RadialVehTD[7], 4);
	TextDrawSetProportional(RadialVehTD[7], 1);

	RadialVehTD[8] = TextDrawCreate(292.000, 329.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialVehTD[8], 27.000, 1.000);
	TextDrawAlignment(RadialVehTD[8], 1);
	TextDrawColor(RadialVehTD[8], 255);
	TextDrawSetShadow(RadialVehTD[8], 0);
	TextDrawSetOutline(RadialVehTD[8], 0);
	TextDrawBackgroundColor(RadialVehTD[8], 255);
	TextDrawFont(RadialVehTD[8], 4);
	TextDrawSetProportional(RadialVehTD[8], 1);

	RadialVehTD[9] = TextDrawCreate(329.000, 322.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialVehTD[9], 27.000, 1.000);
	TextDrawAlignment(RadialVehTD[9], 1);
	TextDrawColor(RadialVehTD[9], 255);
	TextDrawSetShadow(RadialVehTD[9], 0);
	TextDrawSetOutline(RadialVehTD[9], 0);
	TextDrawBackgroundColor(RadialVehTD[9], 255);
	TextDrawFont(RadialVehTD[9], 4);
	TextDrawSetProportional(RadialVehTD[9], 1);

	RadialVehTD[10] = TextDrawCreate(355.000, 316.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialVehTD[10], 35.000, 13.000);
	TextDrawAlignment(RadialVehTD[10], 1);
	TextDrawColor(RadialVehTD[10], 255);
	TextDrawSetShadow(RadialVehTD[10], 0);
	TextDrawSetOutline(RadialVehTD[10], 0);
	TextDrawBackgroundColor(RadialVehTD[10], 255);
	TextDrawFont(RadialVehTD[10], 4);
	TextDrawSetProportional(RadialVehTD[10], 1);
	TextDrawSetSelectable(RadialVehTD[10], 1);

	RadialVehTD[11] = TextDrawCreate(257.000, 322.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialVehTD[11], 35.000, 13.000);
	TextDrawAlignment(RadialVehTD[11], 1);
	TextDrawColor(RadialVehTD[11], 255);
	TextDrawSetShadow(RadialVehTD[11], 0);
	TextDrawSetOutline(RadialVehTD[11], 0);
	TextDrawBackgroundColor(RadialVehTD[11], 255);
	TextDrawFont(RadialVehTD[11], 4);
	TextDrawSetProportional(RadialVehTD[11], 1);
	TextDrawSetSelectable(RadialVehTD[11], 1);

	RadialVehTD[12] = TextDrawCreate(230.000, 229.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialVehTD[12], 35.000, 13.000);
	TextDrawAlignment(RadialVehTD[12], 1);
	TextDrawColor(RadialVehTD[12], 255);
	TextDrawSetShadow(RadialVehTD[12], 0);
	TextDrawSetOutline(RadialVehTD[12], 0);
	TextDrawBackgroundColor(RadialVehTD[12], 255);
	TextDrawFont(RadialVehTD[12], 4);
	TextDrawSetProportional(RadialVehTD[12], 1);
	TextDrawSetSelectable(RadialVehTD[12], 1);

	RadialVehTD[13] = TextDrawCreate(240.000, 169.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialVehTD[13], 35.000, 13.000);
	TextDrawAlignment(RadialVehTD[13], 1);
	TextDrawColor(RadialVehTD[13], 255);
	TextDrawSetShadow(RadialVehTD[13], 0);
	TextDrawSetOutline(RadialVehTD[13], 0);
	TextDrawBackgroundColor(RadialVehTD[13], 255);
	TextDrawFont(RadialVehTD[13], 4);
	TextDrawSetProportional(RadialVehTD[13], 1);
	TextDrawSetSelectable(RadialVehTD[13], 1);

	RadialVehTD[14] = TextDrawCreate(365.000, 170.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialVehTD[14], 35.000, 13.000);
	TextDrawAlignment(RadialVehTD[14], 1);
	TextDrawColor(RadialVehTD[14], 255);
	TextDrawSetShadow(RadialVehTD[14], 0);
	TextDrawSetOutline(RadialVehTD[14], 0);
	TextDrawBackgroundColor(RadialVehTD[14], 255);
	TextDrawFont(RadialVehTD[14], 4);
	TextDrawSetProportional(RadialVehTD[14], 1);
	TextDrawSetSelectable(RadialVehTD[14], 1);

	RadialVehTD[15] = TextDrawCreate(343.000, 127.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialVehTD[15], 35.000, 13.000);
	TextDrawAlignment(RadialVehTD[15], 1);
	TextDrawColor(RadialVehTD[15], 255);
	TextDrawSetShadow(RadialVehTD[15], 0);
	TextDrawSetOutline(RadialVehTD[15], 0);
	TextDrawBackgroundColor(RadialVehTD[15], 255);
	TextDrawFont(RadialVehTD[15], 4);
	TextDrawSetProportional(RadialVehTD[15], 1);
	TextDrawSetSelectable(RadialVehTD[15], 1);

	RadialVehTD[16] = TextDrawCreate(349.000, 128.000, "TRUNK");
	TextDrawLetterSize(RadialVehTD[16], 0.210, 0.999);
	TextDrawAlignment(RadialVehTD[16], 1);
	TextDrawColor(RadialVehTD[16], -1);
	TextDrawSetShadow(RadialVehTD[16], 0);
	TextDrawSetOutline(RadialVehTD[16], 0);
	TextDrawBackgroundColor(RadialVehTD[16], 150);
	TextDrawFont(RadialVehTD[16], 1);
	TextDrawSetProportional(RadialVehTD[16], 1);

	RadialVehTD[17] = TextDrawCreate(368.000, 171.000, "SENJATA");
	TextDrawLetterSize(RadialVehTD[17], 0.210, 0.999);
	TextDrawAlignment(RadialVehTD[17], 1);
	TextDrawColor(RadialVehTD[17], -1);
	TextDrawSetShadow(RadialVehTD[17], 0);
	TextDrawSetOutline(RadialVehTD[17], 0);
	TextDrawBackgroundColor(RadialVehTD[17], 150);
	TextDrawFont(RadialVehTD[17], 1);
	TextDrawSetProportional(RadialVehTD[17], 1);

	RadialVehTD[18] = TextDrawCreate(360.000, 317.000, "LAMPU");
	TextDrawLetterSize(RadialVehTD[18], 0.210, 0.999);
	TextDrawAlignment(RadialVehTD[18], 1);
	TextDrawColor(RadialVehTD[18], -1);
	TextDrawSetShadow(RadialVehTD[18], 0);
	TextDrawSetOutline(RadialVehTD[18], 0);
	TextDrawBackgroundColor(RadialVehTD[18], 150);
	TextDrawFont(RadialVehTD[18], 1);
	TextDrawSetProportional(RadialVehTD[18], 1);

	RadialVehTD[19] = TextDrawCreate(264.000, 323.000, "HOOD");
	TextDrawLetterSize(RadialVehTD[19], 0.210, 0.999);
	TextDrawAlignment(RadialVehTD[19], 1);
	TextDrawColor(RadialVehTD[19], -1);
	TextDrawSetShadow(RadialVehTD[19], 0);
	TextDrawSetOutline(RadialVehTD[19], 0);
	TextDrawBackgroundColor(RadialVehTD[19], 150);
	TextDrawFont(RadialVehTD[19], 1);
	TextDrawSetProportional(RadialVehTD[19], 1);

	RadialVehTD[20] = TextDrawCreate(237.000, 230.000, "KUNCI");
	TextDrawLetterSize(RadialVehTD[20], 0.210, 0.999);
	TextDrawAlignment(RadialVehTD[20], 1);
	TextDrawColor(RadialVehTD[20], -1);
	TextDrawSetShadow(RadialVehTD[20], 0);
	TextDrawSetOutline(RadialVehTD[20], 0);
	TextDrawBackgroundColor(RadialVehTD[20], 150);
	TextDrawFont(RadialVehTD[20], 1);
	TextDrawSetProportional(RadialVehTD[20], 1);

	RadialVehTD[21] = TextDrawCreate(245.000, 170.000, "BAGASI");
	TextDrawLetterSize(RadialVehTD[21], 0.210, 0.999);
	TextDrawAlignment(RadialVehTD[21], 1);
	TextDrawColor(RadialVehTD[21], -1);
	TextDrawSetShadow(RadialVehTD[21], 0);
	TextDrawSetOutline(RadialVehTD[21], 0);
	TextDrawBackgroundColor(RadialVehTD[21], 150);
	TextDrawFont(RadialVehTD[21], 1);
	TextDrawSetProportional(RadialVehTD[21], 1);

	RadialVehTD[22] = TextDrawCreate(358.000, 222.000, "LD_BEAT:chit");
	TextDrawTextSize(RadialVehTD[22], 31.000, 37.000);
	TextDrawAlignment(RadialVehTD[22], 1);
	TextDrawColor(RadialVehTD[22], 255);
	TextDrawSetShadow(RadialVehTD[22], 0);
	TextDrawSetOutline(RadialVehTD[22], 0);
	TextDrawBackgroundColor(RadialVehTD[22], 255);
	TextDrawFont(RadialVehTD[22], 4);
	TextDrawSetProportional(RadialVehTD[22], 1);
	TextDrawSetSelectable(RadialVehTD[22], 1);

	RadialVehTD[23] = TextDrawCreate(369.000, 230.000, "X");
	TextDrawLetterSize(RadialVehTD[23], 0.409, 2.199);
	TextDrawAlignment(RadialVehTD[23], 1);
	TextDrawColor(RadialVehTD[23], -1);
	TextDrawSetShadow(RadialVehTD[23], 0);
	TextDrawSetOutline(RadialVehTD[23], 0);
	TextDrawBackgroundColor(RadialVehTD[23], 150);
	TextDrawFont(RadialVehTD[23], 1);
	TextDrawSetProportional(RadialVehTD[23], 1);

}

CreateRadialCardTD()
{
	RadialCardTD[22] = TextDrawCreate(141.000, 194.000, "LD_BUM:blkdot"); //tunjukkan ktp
	TextDrawTextSize(RadialCardTD[22], 34.000, 35.000);
	TextDrawAlignment(RadialCardTD[22], 1);
	TextDrawColor(RadialCardTD[22], 0x00000066);
	TextDrawSetShadow(RadialCardTD[22], 0);
	TextDrawSetOutline(RadialCardTD[22], 0);
	TextDrawBackgroundColor(RadialCardTD[22], 255);
	TextDrawFont(RadialCardTD[22], 4);
	TextDrawSetProportional(RadialCardTD[22], 1);
	TextDrawSetSelectable(RadialCardTD[22], 1);

	RadialCardTD[23] = TextDrawCreate(186.000, 194.000, "LD_BUM:blkdot"); //lihat sim
	TextDrawTextSize(RadialCardTD[23], 34.000, 35.000);
	TextDrawAlignment(RadialCardTD[23], 1);
	TextDrawColor(RadialCardTD[23], 0x00000066);
	TextDrawSetShadow(RadialCardTD[23], 0);
	TextDrawSetOutline(RadialCardTD[23], 0);
	TextDrawBackgroundColor(RadialCardTD[23], 255);
	TextDrawFont(RadialCardTD[23], 4);
	TextDrawSetProportional(RadialCardTD[23], 1);
	TextDrawSetSelectable(RadialCardTD[23], 1);

	RadialCardTD[24] = TextDrawCreate(232.000, 194.000, "LD_BUM:blkdot"); //TunjukansimB
	TextDrawTextSize(RadialCardTD[24], 34.000, 35.000);
	TextDrawAlignment(RadialCardTD[24], 1);
	TextDrawColor(RadialCardTD[24], 0x00000066);
	TextDrawSetShadow(RadialCardTD[24], 0);
	TextDrawSetOutline(RadialCardTD[24], 0);
	TextDrawBackgroundColor(RadialCardTD[24], 255);
	TextDrawFont(RadialCardTD[24], 4);
	TextDrawSetProportional(RadialCardTD[24], 1);
	TextDrawSetSelectable(RadialCardTD[24], 1);

	RadialCardTD[25] = TextDrawCreate(96.000, 194.000, "LD_BUM:blkdot"); //lihat ktp
	TextDrawTextSize(RadialCardTD[25], 34.000, 35.000);
	TextDrawAlignment(RadialCardTD[25], 1);
	TextDrawColor(RadialCardTD[25], 0x00000066);
	TextDrawSetShadow(RadialCardTD[25], 0);
	TextDrawSetOutline(RadialCardTD[25], 0);
	TextDrawBackgroundColor(RadialCardTD[25], 255);
	TextDrawFont(RadialCardTD[25], 4);
	TextDrawSetProportional(RadialCardTD[25], 1);
	TextDrawSetSelectable(RadialCardTD[25], 1);

	RadialCardTD[1] = TextDrawCreate(166.000, 238.000, "LD_BEAT:chit"); //close
	TextDrawTextSize(RadialCardTD[1], 30.000, 30.000);
	TextDrawAlignment(RadialCardTD[1], 1);
	TextDrawColor(RadialCardTD[1], 0x00000066);
	TextDrawSetShadow(RadialCardTD[1], 0);
	TextDrawSetOutline(RadialCardTD[1], 0);
	TextDrawBackgroundColor(RadialCardTD[1], 255);
	TextDrawFont(RadialCardTD[1], 4);
	TextDrawSetProportional(RadialCardTD[1], 1);
	TextDrawSetSelectable(RadialCardTD[1], 1);

	RadialCardTD[0] = TextDrawCreate(177.000, 245.000, "X");
	TextDrawLetterSize(RadialCardTD[0], 0.349, 1.590);
	TextDrawAlignment(RadialCardTD[0], 1);
	TextDrawColor(RadialCardTD[0], 0xffffffcc);
	TextDrawSetShadow(RadialCardTD[0], 0);
	TextDrawSetOutline(RadialCardTD[0], 0);
	TextDrawBackgroundColor(RadialCardTD[0], 150);
	TextDrawFont(RadialCardTD[0], 1);
	TextDrawSetProportional(RadialCardTD[0], 1);

	RadialCardTD[2] = TextDrawCreate(103.000, 205.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[2], 21.000, 12.000);
	TextDrawAlignment(RadialCardTD[2], 1);
	TextDrawColor(RadialCardTD[2], 0xffffffcc);
	TextDrawSetShadow(RadialCardTD[2], 0);
	TextDrawSetOutline(RadialCardTD[2], 0);
	TextDrawBackgroundColor(RadialCardTD[2], 255);
	TextDrawFont(RadialCardTD[2], 4);
	TextDrawSetProportional(RadialCardTD[2], 1);

	RadialCardTD[3] = TextDrawCreate(118.000, 206.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[3], 5.000, 7.000);
	TextDrawAlignment(RadialCardTD[3], 1);
	TextDrawColor(RadialCardTD[3], 0x3f3f3f8c);
	TextDrawSetShadow(RadialCardTD[3], 0);
	TextDrawSetOutline(RadialCardTD[3], 0);
	TextDrawBackgroundColor(RadialCardTD[3], 255);
	TextDrawFont(RadialCardTD[3], 4);
	TextDrawSetProportional(RadialCardTD[3], 1);

	RadialCardTD[4] = TextDrawCreate(104.000, 206.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[4], 13.000, 2.000);
	TextDrawAlignment(RadialCardTD[4], 1);
	TextDrawColor(RadialCardTD[4], 0x3f3f3f8c);
	TextDrawSetShadow(RadialCardTD[4], 0);
	TextDrawSetOutline(RadialCardTD[4], 0);
	TextDrawBackgroundColor(RadialCardTD[4], 255);
	TextDrawFont(RadialCardTD[4], 4);
	TextDrawSetProportional(RadialCardTD[4], 1);

	RadialCardTD[5] = TextDrawCreate(104.000, 209.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[5], 13.000, 2.000);
	TextDrawAlignment(RadialCardTD[5], 1);
	TextDrawColor(RadialCardTD[5], 0x3f3f3f8c);
	TextDrawSetShadow(RadialCardTD[5], 0);
	TextDrawSetOutline(RadialCardTD[5], 0);
	TextDrawBackgroundColor(RadialCardTD[5], 255);
	TextDrawFont(RadialCardTD[5], 4);
	TextDrawSetProportional(RadialCardTD[5], 1);

	RadialCardTD[6] = TextDrawCreate(148.000, 205.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[6], 21.000, 12.000);
	TextDrawAlignment(RadialCardTD[6], 1);
	TextDrawColor(RadialCardTD[6], 0xffffffcc);
	TextDrawSetShadow(RadialCardTD[6], 0);
	TextDrawSetOutline(RadialCardTD[6], 0);
	TextDrawBackgroundColor(RadialCardTD[6], 255);
	TextDrawFont(RadialCardTD[6], 4);
	TextDrawSetProportional(RadialCardTD[6], 1);

	RadialCardTD[7] = TextDrawCreate(163.000, 206.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[7], 5.000, 7.000);
	TextDrawAlignment(RadialCardTD[7], 1);
	TextDrawColor(RadialCardTD[7], 0x3f3f3f8c);
	TextDrawSetShadow(RadialCardTD[7], 0);
	TextDrawSetOutline(RadialCardTD[7], 0);
	TextDrawBackgroundColor(RadialCardTD[7], 255);
	TextDrawFont(RadialCardTD[7], 4);
	TextDrawSetProportional(RadialCardTD[7], 1);

	RadialCardTD[8] = TextDrawCreate(149.000, 206.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[8], 13.000, 2.000);
	TextDrawAlignment(RadialCardTD[8], 1);
	TextDrawColor(RadialCardTD[8], 0x3f3f3f8c);
	TextDrawSetShadow(RadialCardTD[8], 0);
	TextDrawSetOutline(RadialCardTD[8], 0);
	TextDrawBackgroundColor(RadialCardTD[8], 255);
	TextDrawFont(RadialCardTD[8], 4);
	TextDrawSetProportional(RadialCardTD[8], 1);

	RadialCardTD[9] = TextDrawCreate(149.000, 209.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[9], 13.000, 2.000);
	TextDrawAlignment(RadialCardTD[9], 1);
	TextDrawColor(RadialCardTD[9], 0x3f3f3f8c);
	TextDrawSetShadow(RadialCardTD[9], 0);
	TextDrawSetOutline(RadialCardTD[9], 0);
	TextDrawBackgroundColor(RadialCardTD[9], 255);
	TextDrawFont(RadialCardTD[9], 4);
	TextDrawSetProportional(RadialCardTD[9], 1);

	RadialCardTD[10] = TextDrawCreate(193.000, 205.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[10], 21.000, 12.000);
	TextDrawAlignment(RadialCardTD[10], 1);
	TextDrawColor(RadialCardTD[10], 0xffffffcc);
	TextDrawSetShadow(RadialCardTD[10], 0);
	TextDrawSetOutline(RadialCardTD[10], 0);
	TextDrawBackgroundColor(RadialCardTD[10], 255);
	TextDrawFont(RadialCardTD[10], 4);
	TextDrawSetProportional(RadialCardTD[10], 1);

	RadialCardTD[11] = TextDrawCreate(194.000, 208.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[11], 5.000, 7.000);
	TextDrawAlignment(RadialCardTD[11], 1);
	TextDrawColor(RadialCardTD[11], 0x3f3f3f8c);
	TextDrawSetShadow(RadialCardTD[11], 0);
	TextDrawSetOutline(RadialCardTD[11], 0);
	TextDrawBackgroundColor(RadialCardTD[11], 255);
	TextDrawFont(RadialCardTD[11], 4);
	TextDrawSetProportional(RadialCardTD[11], 1);

	RadialCardTD[12] = TextDrawCreate(200.000, 209.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[12], 11.000, 2.000);
	TextDrawAlignment(RadialCardTD[12], 1);
	TextDrawColor(RadialCardTD[12], 0x3f3f3f8c);
	TextDrawSetShadow(RadialCardTD[12], 0);
	TextDrawSetOutline(RadialCardTD[12], 0);
	TextDrawBackgroundColor(RadialCardTD[12], 255);
	TextDrawFont(RadialCardTD[12], 4);
	TextDrawSetProportional(RadialCardTD[12], 1);

	RadialCardTD[13] = TextDrawCreate(200.000, 212.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[13], 11.000, 2.000);
	TextDrawAlignment(RadialCardTD[13], 1);
	TextDrawColor(RadialCardTD[13], 0x3f3f3f8c);
	TextDrawSetShadow(RadialCardTD[13], 0);
	TextDrawSetOutline(RadialCardTD[13], 0);
	TextDrawBackgroundColor(RadialCardTD[13], 255);
	TextDrawFont(RadialCardTD[13], 4);
	TextDrawSetProportional(RadialCardTD[13], 1);

	RadialCardTD[14] = TextDrawCreate(239.000, 205.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[14], 21.000, 12.000);
	TextDrawAlignment(RadialCardTD[14], 1);
	TextDrawColor(RadialCardTD[14], 0xffffffcc);
	TextDrawSetShadow(RadialCardTD[14], 0);
	TextDrawSetOutline(RadialCardTD[14], 0);
	TextDrawBackgroundColor(RadialCardTD[14], 255);
	TextDrawFont(RadialCardTD[14], 4);
	TextDrawSetProportional(RadialCardTD[14], 1);

	RadialCardTD[15] = TextDrawCreate(240.000, 208.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[15], 5.000, 7.000);
	TextDrawAlignment(RadialCardTD[15], 1);
	TextDrawColor(RadialCardTD[15], 0x3f3f3f8c);
	TextDrawSetShadow(RadialCardTD[15], 0);
	TextDrawSetOutline(RadialCardTD[15], 0);
	TextDrawBackgroundColor(RadialCardTD[15], 255);
	TextDrawFont(RadialCardTD[15], 4);
	TextDrawSetProportional(RadialCardTD[15], 1);

	RadialCardTD[16] = TextDrawCreate(246.000, 209.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[16], 11.000, 2.000);
	TextDrawAlignment(RadialCardTD[16], 1);
	TextDrawColor(RadialCardTD[16], 0x3f3f3f8c);
	TextDrawSetShadow(RadialCardTD[16], 0);
	TextDrawSetOutline(RadialCardTD[16], 0);
	TextDrawBackgroundColor(RadialCardTD[16], 255);
	TextDrawFont(RadialCardTD[16], 4);
	TextDrawSetProportional(RadialCardTD[16], 1);

	RadialCardTD[17] = TextDrawCreate(246.000, 212.000, "LD_BUM:blkdot");
	TextDrawTextSize(RadialCardTD[17], 11.000, 2.000);
	TextDrawAlignment(RadialCardTD[17], 1);
	TextDrawColor(RadialCardTD[17], 0x3f3f3f8c);
	TextDrawSetShadow(RadialCardTD[17], 0);
	TextDrawSetOutline(RadialCardTD[17], 0);
	TextDrawBackgroundColor(RadialCardTD[17], 255);
	TextDrawFont(RadialCardTD[17], 4);
	TextDrawSetProportional(RadialCardTD[17], 1);

	RadialCardTD[18] = TextDrawCreate(100.000, 219.000, "LIHAT IDCARD");
	TextDrawLetterSize(RadialCardTD[18], 0.119, 0.699);
	TextDrawAlignment(RadialCardTD[18], 1);
	TextDrawColor(RadialCardTD[18], 0xffffffcc);
	TextDrawSetShadow(RadialCardTD[18], 0);
	TextDrawSetOutline(RadialCardTD[18], 0);
	TextDrawBackgroundColor(RadialCardTD[18], 150);
	TextDrawFont(RadialCardTD[18], 1);
	TextDrawSetProportional(RadialCardTD[18], 1);

	RadialCardTD[19] = TextDrawCreate(145.000, 219.000, "BERI IDCARD");
	TextDrawLetterSize(RadialCardTD[19], 0.129, 0.699);
	TextDrawAlignment(RadialCardTD[19], 1);
	TextDrawColor(RadialCardTD[19], 0xffffffcc);
	TextDrawSetShadow(RadialCardTD[19], 0);
	TextDrawSetOutline(RadialCardTD[19], 0);
	TextDrawBackgroundColor(RadialCardTD[19], 150);
	TextDrawFont(RadialCardTD[19], 1);
	TextDrawSetProportional(RadialCardTD[19], 1);

	RadialCardTD[20] = TextDrawCreate(193.000, 219.000, "LIHAT SIM");
	TextDrawLetterSize(RadialCardTD[20], 0.129, 0.699);
	TextDrawAlignment(RadialCardTD[20], 1);
	TextDrawColor(RadialCardTD[20], 0xffffffcc);
	TextDrawSetShadow(RadialCardTD[20], 0);
	TextDrawSetOutline(RadialCardTD[20], 0);
	TextDrawBackgroundColor(RadialCardTD[20], 150);
	TextDrawFont(RadialCardTD[20], 1);
	TextDrawSetProportional(RadialCardTD[20], 1);

	RadialCardTD[21] = TextDrawCreate(240.000, 219.000, "BERI SIM");
	TextDrawLetterSize(RadialCardTD[21], 0.129, 0.699);
	TextDrawAlignment(RadialCardTD[21], 1);
	TextDrawColor(RadialCardTD[21], 0xffffffcc);
	TextDrawSetShadow(RadialCardTD[21], 0);
	TextDrawSetOutline(RadialCardTD[21], 0);
	TextDrawBackgroundColor(RadialCardTD[21], 150);
	TextDrawFont(RadialCardTD[21], 1);
	TextDrawSetProportional(RadialCardTD[21], 1);
}

ShowRadialTD(playerid)
{
	HideServerNameTD(playerid);
	HideSpeedoTD(playerid);
	HideHBETD(playerid);
	HideStatsTD(playerid);
	//HideRadioVoiceInfoTD(playerid);

    for(new x; x < 34; x++)
    {
        TextDrawShowForPlayer(playerid, RadialTD[x]);
    }
    SelectTextDraw(playerid, 0xff91a4cc);
}

HideRadialTD(playerid)
{
    for(new x; x < 34; x++)
    {
        TextDrawHideForPlayer(playerid, RadialTD[x]);
    }
}

ShowRadialTD2(playerid)
{
	HideServerNameTD(playerid);
	HideSpeedoTD(playerid);
	HideHBETD(playerid);
	HideStatsTD(playerid);
	//HideRadioVoiceInfoTD(playerid);

    for(new x; x < 24; x++)
    {
        TextDrawShowForPlayer(playerid, RadialTD2[x]);
    }
    SelectTextDraw(playerid, 0xff91a4cc);
}

HideRadialTD2(playerid)
{
    for(new x; x < 24; x++)
    {
        TextDrawHideForPlayer(playerid, RadialTD2[x]);
    }
}
ShowRadialFashionTD(playerid)
{
    for(new x; x < 28; x++)
    {
        TextDrawShowForPlayer(playerid, RadialFashionTD[x]);
    }
    SelectTextDraw(playerid, 0xff91a4cc);
}

HideRadialFashionTD(playerid)
{
    for(new x; x < 28; x++)
    {
        TextDrawHideForPlayer(playerid, RadialFashionTD[x]);
    }
}

ShowRadialVehTD(playerid)
{
    for(new x; x < 24; x++)
    {
        TextDrawShowForPlayer(playerid, RadialVehTD[x]);
    }
    SelectTextDraw(playerid, 0xff91a4cc);
}

HideRadialVehTD(playerid)
{
    for(new x; x < 24; x++)
    {
        TextDrawHideForPlayer(playerid, RadialVehTD[x]);
    }
}

ShowRadialCardTD(playerid)
{
    for(new x; x < 26; x++)
    {
        TextDrawShowForPlayer(playerid, RadialCardTD[x]);
    }
    SelectTextDraw(playerid, 0xff91a4cc);
}

HideRadialCardTD(playerid)
{
    for(new x; x < 26; x++)
    {
        TextDrawHideForPlayer(playerid, RadialCardTD[x]);
    }
}