new Text: StarterpackTD[27];

CreateStarterTD()
{
    StarterpackTD[0] = TextDrawCreate(0.000, -1.000, "LOADSC8:loadsc8");
    TextDrawTextSize(StarterpackTD[0], 643.000, 450.000);
    TextDrawAlignment(StarterpackTD[0], 1);
    TextDrawColor(StarterpackTD[0], -1);
    TextDrawSetShadow(StarterpackTD[0], 0);
    TextDrawSetOutline(StarterpackTD[0], 0);
    TextDrawBackgroundColor(StarterpackTD[0], 255);
    TextDrawFont(StarterpackTD[0], 4);
    TextDrawSetProportional(StarterpackTD[0], 1);

    StarterpackTD[1] = TextDrawCreate(-18.000, -9.000, "LD_SPAC:white");
    TextDrawTextSize(StarterpackTD[1], 665.000, 534.000);
    TextDrawAlignment(StarterpackTD[1], 1);
    TextDrawColor(StarterpackTD[1], 160);
    TextDrawSetShadow(StarterpackTD[1], 0);
    TextDrawSetOutline(StarterpackTD[1], 0);
    TextDrawBackgroundColor(StarterpackTD[1], 255);
    TextDrawFont(StarterpackTD[1], 4);
    TextDrawSetProportional(StarterpackTD[1], 1);

    StarterpackTD[2] = TextDrawCreate(252.000, 141.000, "STARTER");
    TextDrawLetterSize(StarterpackTD[2], 0.649, 5.099);
    TextDrawAlignment(StarterpackTD[2], 1);
    TextDrawColor(StarterpackTD[2], -1);
    TextDrawSetShadow(StarterpackTD[2], 1);
    TextDrawSetOutline(StarterpackTD[2], 1);
    TextDrawBackgroundColor(StarterpackTD[2], 0);
    TextDrawFont(StarterpackTD[2], 1);
    TextDrawSetProportional(StarterpackTD[2], 1);

    StarterpackTD[3] = TextDrawCreate(346.000, 141.000, "PACK");
    TextDrawLetterSize(StarterpackTD[3], 0.649, 5.099);
    TextDrawAlignment(StarterpackTD[3], 1);
    TextDrawColor(StarterpackTD[3], -849584897);
    TextDrawSetShadow(StarterpackTD[3], 1);
    TextDrawSetOutline(StarterpackTD[3], 1);
    TextDrawBackgroundColor(StarterpackTD[3], 0);
    TextDrawFont(StarterpackTD[3], 1);
    TextDrawSetProportional(StarterpackTD[3], 1);

    StarterpackTD[4] = TextDrawCreate(235.000, 180.000, "-");
    TextDrawLetterSize(StarterpackTD[4], 12.650, 1.500);
    TextDrawAlignment(StarterpackTD[4], 1);
    TextDrawColor(StarterpackTD[4], -1);
    TextDrawSetShadow(StarterpackTD[4], 1);
    TextDrawSetOutline(StarterpackTD[4], 1);
    TextDrawBackgroundColor(StarterpackTD[4], 0);
    TextDrawFont(StarterpackTD[4], 1);
    TextDrawSetProportional(StarterpackTD[4], 1);

    StarterpackTD[5] = TextDrawCreate(253.000, 191.000, "Selamat Datang Di BLOKGEDONG!");
    TextDrawLetterSize(StarterpackTD[5], 0.150, 1.099);
    TextDrawAlignment(StarterpackTD[5], 1);
    TextDrawColor(StarterpackTD[5], -1);
    TextDrawSetShadow(StarterpackTD[5], 1);
    TextDrawSetOutline(StarterpackTD[5], 1);
    TextDrawBackgroundColor(StarterpackTD[5], 0);
    TextDrawFont(StarterpackTD[5], 1);
    TextDrawSetProportional(StarterpackTD[5], 1);

    StarterpackTD[6] = TextDrawCreate(328.000, 191.000, "Ambil Benefitmu Sekarang");
    TextDrawLetterSize(StarterpackTD[6], 0.150, 1.099);
    TextDrawAlignment(StarterpackTD[6], 1);
    TextDrawColor(StarterpackTD[6], -1);
    TextDrawSetShadow(StarterpackTD[6], 1);
    TextDrawSetOutline(StarterpackTD[6], 1);
    TextDrawBackgroundColor(StarterpackTD[6], 0);
    TextDrawFont(StarterpackTD[6], 1);
    TextDrawSetProportional(StarterpackTD[6], 1);

    StarterpackTD[7] = TextDrawCreate(301.000, 211.000, "SPLASH2:splash2");
    TextDrawTextSize(StarterpackTD[7], 41.000, 43.000);
    TextDrawAlignment(StarterpackTD[7], 1);
    TextDrawColor(StarterpackTD[7], -1);
    TextDrawSetShadow(StarterpackTD[7], 0);
    TextDrawSetOutline(StarterpackTD[7], 0);
    TextDrawBackgroundColor(StarterpackTD[7], 255);
    TextDrawFont(StarterpackTD[7], 4);
    TextDrawSetProportional(StarterpackTD[7], 1);

    StarterpackTD[8] = TextDrawCreate(299.000, 261.000, "Benefit Berupa");
    TextDrawLetterSize(StarterpackTD[8], 0.170, 1.500);
    TextDrawAlignment(StarterpackTD[8], 1);
    TextDrawColor(StarterpackTD[8], -1);
    TextDrawSetShadow(StarterpackTD[8], 1);
    TextDrawSetOutline(StarterpackTD[8], 1);
    TextDrawBackgroundColor(StarterpackTD[8], 0);
    TextDrawFont(StarterpackTD[8], 1);
    TextDrawSetProportional(StarterpackTD[8], 1);

    StarterpackTD[9] = TextDrawCreate(240.000, 261.000, "-");
    TextDrawLetterSize(StarterpackTD[9], 3.959, 1.500);
    TextDrawAlignment(StarterpackTD[9], 1);
    TextDrawColor(StarterpackTD[9], -1);
    TextDrawSetShadow(StarterpackTD[9], 1);
    TextDrawSetOutline(StarterpackTD[9], 1);
    TextDrawBackgroundColor(StarterpackTD[9], 0);
    TextDrawFont(StarterpackTD[9], 1);
    TextDrawSetProportional(StarterpackTD[9], 1);

    StarterpackTD[10] = TextDrawCreate(344.000, 261.000, "-");
    TextDrawLetterSize(StarterpackTD[10], 3.959, 1.500);
    TextDrawAlignment(StarterpackTD[10], 1);
    TextDrawColor(StarterpackTD[10], -1);
    TextDrawSetShadow(StarterpackTD[10], 1);
    TextDrawSetOutline(StarterpackTD[10], 1);
    TextDrawBackgroundColor(StarterpackTD[10], 0);
    TextDrawFont(StarterpackTD[10], 1);
    TextDrawSetProportional(StarterpackTD[10], 1);

    StarterpackTD[11] = TextDrawCreate(254.000, 282.000, "LD_SPAC:white");
    TextDrawTextSize(StarterpackTD[11], 44.000, 52.000);
    TextDrawAlignment(StarterpackTD[11], 1);
    TextDrawColor(StarterpackTD[11], 155);
    TextDrawSetShadow(StarterpackTD[11], 0);
    TextDrawSetOutline(StarterpackTD[11], 0);
    TextDrawBackgroundColor(StarterpackTD[11], 255);
    TextDrawFont(StarterpackTD[11], 4);
    TextDrawSetProportional(StarterpackTD[11], 1);

    StarterpackTD[12] = TextDrawCreate(298.000, 282.000, "LD_SPAC:white");
    TextDrawTextSize(StarterpackTD[12], 44.000, 52.000);
    TextDrawAlignment(StarterpackTD[12], 1);
    TextDrawColor(StarterpackTD[12], 155);
    TextDrawSetShadow(StarterpackTD[12], 0);
    TextDrawSetOutline(StarterpackTD[12], 0);
    TextDrawBackgroundColor(StarterpackTD[12], 255);
    TextDrawFont(StarterpackTD[12], 4);
    TextDrawSetProportional(StarterpackTD[12], 1);

    StarterpackTD[13] = TextDrawCreate(342.000, 282.000, "LD_SPAC:white");
    TextDrawTextSize(StarterpackTD[13], 44.000, 52.000);
    TextDrawAlignment(StarterpackTD[13], 1);
    TextDrawColor(StarterpackTD[13], 155);
    TextDrawSetShadow(StarterpackTD[13], 0);
    TextDrawSetOutline(StarterpackTD[13], 0);
    TextDrawBackgroundColor(StarterpackTD[13], 255);
    TextDrawFont(StarterpackTD[13], 4);
    TextDrawSetProportional(StarterpackTD[13], 1);

    StarterpackTD[14] = TextDrawCreate(254.000, 262.000, "I");
    TextDrawLetterSize(StarterpackTD[14], 0.100, 9.299);
    TextDrawAlignment(StarterpackTD[14], 1);
    TextDrawColor(StarterpackTD[14], -1);
    TextDrawSetShadow(StarterpackTD[14], 1);
    TextDrawSetOutline(StarterpackTD[14], 1);
    TextDrawBackgroundColor(StarterpackTD[14], 0);
    TextDrawFont(StarterpackTD[14], 1);
    TextDrawSetProportional(StarterpackTD[14], 1);

    StarterpackTD[15] = TextDrawCreate(298.000, 262.000, "I");
    TextDrawLetterSize(StarterpackTD[15], 0.100, 9.299);
    TextDrawAlignment(StarterpackTD[15], 1);
    TextDrawColor(StarterpackTD[15], -1);
    TextDrawSetShadow(StarterpackTD[15], 1);
    TextDrawSetOutline(StarterpackTD[15], 1);
    TextDrawBackgroundColor(StarterpackTD[15], 0);
    TextDrawFont(StarterpackTD[15], 1);
    TextDrawSetProportional(StarterpackTD[15], 1);

    StarterpackTD[16] = TextDrawCreate(341.000, 262.000, "I");
    TextDrawLetterSize(StarterpackTD[16], 0.100, 9.299);
    TextDrawAlignment(StarterpackTD[16], 1);
    TextDrawColor(StarterpackTD[16], -1);
    TextDrawSetShadow(StarterpackTD[16], 1);
    TextDrawSetOutline(StarterpackTD[16], 1);
    TextDrawBackgroundColor(StarterpackTD[16], 0);
    TextDrawFont(StarterpackTD[16], 1);
    TextDrawSetProportional(StarterpackTD[16], 1);

    StarterpackTD[17] = TextDrawCreate(385.000, 262.000, "I");
    TextDrawLetterSize(StarterpackTD[17], 0.100, 9.299);
    TextDrawAlignment(StarterpackTD[17], 1);
    TextDrawColor(StarterpackTD[17], -1);
    TextDrawSetShadow(StarterpackTD[17], 1);
    TextDrawSetOutline(StarterpackTD[17], 1);
    TextDrawBackgroundColor(StarterpackTD[17], 0);
    TextDrawFont(StarterpackTD[17], 1);
    TextDrawSetProportional(StarterpackTD[17], 1);

    StarterpackTD[18] = TextDrawCreate(310.000, 293.000, "HUD:radar_dateFood");
    TextDrawTextSize(StarterpackTD[18], 19.000, 23.000);
    TextDrawAlignment(StarterpackTD[18], 1);
    TextDrawColor(StarterpackTD[18], -1);
    TextDrawSetShadow(StarterpackTD[18], 0);
    TextDrawSetOutline(StarterpackTD[18], 0);
    TextDrawBackgroundColor(StarterpackTD[18], 255);
    TextDrawFont(StarterpackTD[18], 4);
    TextDrawSetProportional(StarterpackTD[18], 1);

    StarterpackTD[19] = TextDrawCreate(358.000, 293.000, "HUD:radar_dateDrink");
    TextDrawTextSize(StarterpackTD[19], 14.000, 21.000);
    TextDrawAlignment(StarterpackTD[19], 1);
    TextDrawColor(StarterpackTD[19], -1);
    TextDrawSetShadow(StarterpackTD[19], 0);
    TextDrawSetOutline(StarterpackTD[19], 0);
    TextDrawBackgroundColor(StarterpackTD[19], 255);
    TextDrawFont(StarterpackTD[19], 4);
    TextDrawSetProportional(StarterpackTD[19], 1);

    StarterpackTD[20] = TextDrawCreate(258.000, 284.000, "_");
    TextDrawTextSize(StarterpackTD[20], 35.000, 44.000);
    TextDrawAlignment(StarterpackTD[20], 1);
    TextDrawColor(StarterpackTD[20], -1);
    TextDrawSetShadow(StarterpackTD[20], 0);
    TextDrawSetOutline(StarterpackTD[20], 0);
    TextDrawBackgroundColor(StarterpackTD[20], 0);
    TextDrawFont(StarterpackTD[20], 5);
    TextDrawSetProportional(StarterpackTD[20], 0);
    TextDrawSetPreviewModel(StarterpackTD[20], 468);
    TextDrawSetPreviewRot(StarterpackTD[20], -88.000, 90.000, 187.000, 1.000);
    TextDrawSetPreviewVehCol(StarterpackTD[20], 0, 0);

    StarterpackTD[21] = TextDrawCreate(265.000, 322.000, "Sanchez 1x");
    TextDrawLetterSize(StarterpackTD[21], 0.129, 0.699);
    TextDrawAlignment(StarterpackTD[21], 1);
    TextDrawColor(StarterpackTD[21], -1);
    TextDrawSetShadow(StarterpackTD[21], 1);
    TextDrawSetOutline(StarterpackTD[21], 1);
    TextDrawBackgroundColor(StarterpackTD[21], 0);
    TextDrawFont(StarterpackTD[21], 1);
    TextDrawSetProportional(StarterpackTD[21], 1);

    StarterpackTD[22] = TextDrawCreate(305.000, 322.000, "Chicken BBQ 15x");
    TextDrawLetterSize(StarterpackTD[22], 0.109, 0.699);
    TextDrawAlignment(StarterpackTD[22], 1);
    TextDrawColor(StarterpackTD[22], -1);
    TextDrawSetShadow(StarterpackTD[22], 1);
    TextDrawSetOutline(StarterpackTD[22], 1);
    TextDrawBackgroundColor(StarterpackTD[22], 0);
    TextDrawFont(StarterpackTD[22], 1);
    TextDrawSetProportional(StarterpackTD[22], 1);

    StarterpackTD[23] = TextDrawCreate(347.000, 322.000, "Coconut Water 10x");
    TextDrawLetterSize(StarterpackTD[23], 0.100, 0.699);
    TextDrawAlignment(StarterpackTD[23], 1);
    TextDrawColor(StarterpackTD[23], -1);
    TextDrawSetShadow(StarterpackTD[23], 1);
    TextDrawSetOutline(StarterpackTD[23], 1);
    TextDrawBackgroundColor(StarterpackTD[23], 0);
    TextDrawFont(StarterpackTD[23], 1);
    TextDrawSetProportional(StarterpackTD[23], 1);

    StarterpackTD[24] = TextDrawCreate(272.000, 340.000, "LD_SPAC:white");
    TextDrawTextSize(StarterpackTD[24], 90.000, 20.000);
    TextDrawAlignment(StarterpackTD[24], 1);
    TextDrawColor(StarterpackTD[24], -849584897);
    TextDrawSetShadow(StarterpackTD[24], 0);
    TextDrawSetOutline(StarterpackTD[24], 0);
    TextDrawBackgroundColor(StarterpackTD[24], 255);
    TextDrawFont(StarterpackTD[24], 4);
    TextDrawSetProportional(StarterpackTD[24], 1);
    TextDrawSetSelectable(StarterpackTD[24], 1);

    StarterpackTD[25] = TextDrawCreate(293.000, 344.000, "AMBIL SEKARANG");
    TextDrawLetterSize(StarterpackTD[25], 0.170, 1.199);
    TextDrawAlignment(StarterpackTD[25], 1);
    TextDrawColor(StarterpackTD[25], -1);
    TextDrawSetShadow(StarterpackTD[25], 1);
    TextDrawSetOutline(StarterpackTD[25], 1);
    TextDrawBackgroundColor(StarterpackTD[25], 0);
    TextDrawFont(StarterpackTD[25], 1);
    TextDrawSetProportional(StarterpackTD[25], 1);

    StarterpackTD[26] = TextDrawCreate(280.000, 363.000, "Hanya Tersedia Untuk Warga Baru");
    TextDrawLetterSize(StarterpackTD[26], 0.119, 0.899);
    TextDrawAlignment(StarterpackTD[26], 1);
    TextDrawColor(StarterpackTD[26], -849584897);
    TextDrawSetShadow(StarterpackTD[26], 1);
    TextDrawSetOutline(StarterpackTD[26], 1);
    TextDrawBackgroundColor(StarterpackTD[26], 0);
    TextDrawFont(StarterpackTD[26], 1);
    TextDrawSetProportional(StarterpackTD[26], 1);
}

ShowStarterpackTD(playerid)
{
    HideHBETD(playerid);
    HideStatsTD(playerid);
    //HideRadioVoiceInfoTD(playerid);
    HideServerNameTD(playerid);
    for(new x; x < 27; x++)
    {
        TextDrawShowForPlayer(playerid, StarterpackTD[x]);
    }
    SelectTextDraw(playerid, 0xff91a4cc);
}

HideStarterpackTD(playerid)
{
    for(new x; x < 27; x++)
    {
        TextDrawHideForPlayer(playerid, StarterpackTD[x]);
    }
    ShowHBETD(playerid);
    ShowStatsTD(playerid);
    ShowServerNameTD(playerid);
    CancelSelectTextDraw(playerid); 
}