new Text:NamaServerTD[15];

CreateServerNameTD()
{
	NamaServerTD[0] = TextDrawCreate(468.000, 21.000, "I");
	TextDrawLetterSize(NamaServerTD[0], 0.769, 3.199);
	TextDrawAlignment(NamaServerTD[0], 1);
	TextDrawColor(NamaServerTD[0], -92245249);
	TextDrawSetShadow(NamaServerTD[0], 1);
	TextDrawSetOutline(NamaServerTD[0], 1);
	TextDrawBackgroundColor(NamaServerTD[0], 0);
	TextDrawFont(NamaServerTD[0], 1);
	TextDrawSetProportional(NamaServerTD[0], 1);

	NamaServerTD[1] = TextDrawCreate(471.000, 40.000, "/");
	TextDrawLetterSize(NamaServerTD[1], 0.879, -1.300);
	TextDrawAlignment(NamaServerTD[1], 1);
	TextDrawColor(NamaServerTD[1], -92245249);
	TextDrawSetShadow(NamaServerTD[1], 1);
	TextDrawSetOutline(NamaServerTD[1], 1);
	TextDrawBackgroundColor(NamaServerTD[1], 0);
	TextDrawFont(NamaServerTD[1], 1);
	TextDrawSetProportional(NamaServerTD[1], 1);

	NamaServerTD[2] = TextDrawCreate(476.000, 47.000, "/");
	TextDrawLetterSize(NamaServerTD[2], 0.879, -1.300);
	TextDrawAlignment(NamaServerTD[2], 1);
	TextDrawColor(NamaServerTD[2], -92245249);
	TextDrawSetShadow(NamaServerTD[2], 1);
	TextDrawSetOutline(NamaServerTD[2], 1);
	TextDrawBackgroundColor(NamaServerTD[2], 0);
	TextDrawFont(NamaServerTD[2], 1);
	TextDrawSetProportional(NamaServerTD[2], 1);

	NamaServerTD[3] = TextDrawCreate(478.000, 49.000, "/");
	TextDrawLetterSize(NamaServerTD[3], 0.879, -1.300);
	TextDrawAlignment(NamaServerTD[3], 1);
	TextDrawColor(NamaServerTD[3], -92245249);
	TextDrawSetShadow(NamaServerTD[3], 1);
	TextDrawSetOutline(NamaServerTD[3], 1);
	TextDrawBackgroundColor(NamaServerTD[3], 0);
	TextDrawFont(NamaServerTD[3], 1);
	TextDrawSetProportional(NamaServerTD[3], 1);

	NamaServerTD[4] = TextDrawCreate(484.000, 20.000, "I");
	TextDrawLetterSize(NamaServerTD[4], 0.819, 3.599);
	TextDrawAlignment(NamaServerTD[4], 1);
	TextDrawColor(NamaServerTD[4], -92245249);
	TextDrawSetShadow(NamaServerTD[4], 1);
	TextDrawSetOutline(NamaServerTD[4], 1);
	TextDrawBackgroundColor(NamaServerTD[4], 0);
	TextDrawFont(NamaServerTD[4], 1);
	TextDrawSetProportional(NamaServerTD[4], 1);

	NamaServerTD[5] = TextDrawCreate(479.000, 18.000, "/");
	TextDrawLetterSize(NamaServerTD[5], 0.719, 1.799);
	TextDrawAlignment(NamaServerTD[5], 1);
	TextDrawColor(NamaServerTD[5], -1);
	TextDrawSetShadow(NamaServerTD[5], 1);
	TextDrawSetOutline(NamaServerTD[5], 1);
	TextDrawBackgroundColor(NamaServerTD[5], 0);
	TextDrawFont(NamaServerTD[5], 1);
	TextDrawSetProportional(NamaServerTD[5], 1);

	NamaServerTD[6] = TextDrawCreate(474.000, 29.000, "/");
	TextDrawLetterSize(NamaServerTD[6], 0.719, 1.799);
	TextDrawAlignment(NamaServerTD[6], 1);
	TextDrawColor(NamaServerTD[6], -1);
	TextDrawSetShadow(NamaServerTD[6], 1);
	TextDrawSetOutline(NamaServerTD[6], 1);
	TextDrawBackgroundColor(NamaServerTD[6], 0);
	TextDrawFont(NamaServerTD[6], 1);
	TextDrawSetProportional(NamaServerTD[6], 1);

	NamaServerTD[7] = TextDrawCreate(473.000, 32.000, "/");
	TextDrawLetterSize(NamaServerTD[7], 0.719, 1.799);
	TextDrawAlignment(NamaServerTD[7], 1);
	TextDrawColor(NamaServerTD[7], -1);
	TextDrawSetShadow(NamaServerTD[7], 1);
	TextDrawSetOutline(NamaServerTD[7], 1);
	TextDrawBackgroundColor(NamaServerTD[7], 0);
	TextDrawFont(NamaServerTD[7], 1);
	TextDrawSetProportional(NamaServerTD[7], 1);

	NamaServerTD[8] = TextDrawCreate(473.000, 32.000, "/");
	TextDrawLetterSize(NamaServerTD[8], 0.859, -1.200);
	TextDrawAlignment(NamaServerTD[8], 1);
	TextDrawColor(NamaServerTD[8], -1);
	TextDrawSetShadow(NamaServerTD[8], 1);
	TextDrawSetOutline(NamaServerTD[8], 1);
	TextDrawBackgroundColor(NamaServerTD[8], 0);
	TextDrawFont(NamaServerTD[8], 1);
	TextDrawSetProportional(NamaServerTD[8], 1);

	NamaServerTD[9] = TextDrawCreate(480.000, 40.000, "/");
	TextDrawLetterSize(NamaServerTD[9], 0.859, -1.200);
	TextDrawAlignment(NamaServerTD[9], 1);
	TextDrawColor(NamaServerTD[9], -1);
	TextDrawSetShadow(NamaServerTD[9], 1);
	TextDrawSetOutline(NamaServerTD[9], 1);
	TextDrawBackgroundColor(NamaServerTD[9], 0);
	TextDrawFont(NamaServerTD[9], 1);
	TextDrawSetProportional(NamaServerTD[9], 1);

	NamaServerTD[10] = TextDrawCreate(486.000, 48.000, "/");
	TextDrawLetterSize(NamaServerTD[10], 0.859, -1.200);
	TextDrawAlignment(NamaServerTD[10], 1);
	TextDrawColor(NamaServerTD[10], -1);
	TextDrawSetShadow(NamaServerTD[10], 1);
	TextDrawSetOutline(NamaServerTD[10], 1);
	TextDrawBackgroundColor(NamaServerTD[10], 0);
	TextDrawFont(NamaServerTD[10], 1);
	TextDrawSetProportional(NamaServerTD[10], 1);

	NamaServerTD[11] = TextDrawCreate(465.000, 51.000, "NEX");
	TextDrawLetterSize(NamaServerTD[11], 0.240, 0.999);
	TextDrawAlignment(NamaServerTD[11], 1);
	TextDrawColor(NamaServerTD[11], -1);
	TextDrawSetShadow(NamaServerTD[11], 1);
	TextDrawSetOutline(NamaServerTD[11], 1);
	TextDrawBackgroundColor(NamaServerTD[11], 0);
	TextDrawFont(NamaServerTD[11], 1);
	TextDrawSetProportional(NamaServerTD[11], 1);

	NamaServerTD[12] = TextDrawCreate(480.000, 51.000, "O");
	TextDrawLetterSize(NamaServerTD[12], 0.240, 0.999);
	TextDrawAlignment(NamaServerTD[12], 1);
	TextDrawColor(NamaServerTD[12], -92245249);
	TextDrawSetShadow(NamaServerTD[12], 1);
	TextDrawSetOutline(NamaServerTD[12], 1);
	TextDrawBackgroundColor(NamaServerTD[12], 0);
	TextDrawFont(NamaServerTD[12], 1);
	TextDrawSetProportional(NamaServerTD[12], 1);

	NamaServerTD[13] = TextDrawCreate(486.000, 51.000, "TIS");
	TextDrawLetterSize(NamaServerTD[13], 0.240, 0.999);
	TextDrawAlignment(NamaServerTD[13], 1);
	TextDrawColor(NamaServerTD[13], -1);
	TextDrawSetShadow(NamaServerTD[13], 1);
	TextDrawSetOutline(NamaServerTD[13], 1);
	TextDrawBackgroundColor(NamaServerTD[13], 0);
	TextDrawFont(NamaServerTD[13], 1);
	TextDrawSetProportional(NamaServerTD[13], 1);

	NamaServerTD[14] = TextDrawCreate(469.000, 62.000, "LD_SPAC:white");
	TextDrawTextSize(NamaServerTD[14], 23.000, 1.000);
	TextDrawAlignment(NamaServerTD[14], 1);
	TextDrawColor(NamaServerTD[14], -1);
	TextDrawSetShadow(NamaServerTD[14], 0);
	TextDrawSetOutline(NamaServerTD[14], 0);
	TextDrawBackgroundColor(NamaServerTD[14], 255);
	TextDrawFont(NamaServerTD[14], 4);
	TextDrawSetProportional(NamaServerTD[14], 1);
}

ShowServerNameTD(playerid)
{
	for(new x; x < 15; x++)
    {
    	TextDrawShowForPlayer(playerid, NamaServerTD[x]);
	}
}

HideServerNameTD(playerid)
{
    for(new x; x < 15; x++)
    {
        TextDrawHideForPlayer(playerid, NamaServerTD[x]);
    }
}
